### ISSUE TITLE
[Bug]: Updating provisioner configuration makes template configuration disappear

### ISSUE THREAD

**Issue by mirex05** [smallstep/cli#1009]
### Steps to Reproduce

Try to update previously configured ACME provisioner with template.

Provisioner config before update:
````
[
   {
      "type": "ACME",
      "name": "acme",
      "claims": {
         "enableSSHCA": true,
         "disableRenewal": false,
         "allowRenewalAfterExpiry": false
      },
      "options": {
         "x509": {
            "template": "{ ...template here... }",
            "templateData": {
               "country": "US",
               "organization": "ACME Corp",
               "organizationalUnit": "ACME Labs"
            }
         },
         "ssh": {}
      }
   }
````

But after updating provisioner config using, for example, command `step ca provisioner update acme --force-cn`, template disappears:
````
[
   {
      "type": "ACME",
      "name": "acme",
      "forceCN": true,
      "claims": {
         "enableSSHCA": true,
         "disableRenewal": false,
         "allowRenewalAfterExpiry": false
      },
      "options": {
         "x509": {},
         "ssh": {}
      }
   }
]
````

### Your Environment

* OS - Debian 12
* `step` CLI Version -  0.24.4 (linux/amd64)

### Expected Behavior

Template keeps in provisioner config.

### Actual Behavior

Templates config disappears, so need to configure it again using `step ca provisioner update acme --x509-template  --x509-template-data` command.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dopey** [comment]
Hey @mirex05 👋. Thanks for opening the issue!

Are you using databased backed provisioners or the default (file system backed)? Database backed provisioners require the admin API and would require you to input admin credentials when issuing commands like `step ca provisioner update`. While file system backed uses the local filesystem to update provisioners (in the `ca.json`) and does not require additional credentials.

**Comment by mirex05** [comment]
Hello @dopey! I`m using file backend, just noticed that after updating provisioner temlplate disappears. So, i see that this was now fixed, thank you!

**Comment by dopey** [comment]
It's fixed but only in the main branch of this repo for now (not in a release).

**Comment by mirex05** [comment]
Of course, waiting for next stable release now.
