### ISSUE TITLE
SHA256 checksum can change over time

### ISSUE THREAD

**Issue by maraino** [smallstep/cli#103]
### Description
The SHA256 sum of the source tar files of v0.9.0 has changed (https://github.com/smallstep/cli/archive/v0.9.0.tar.gz)
* homebrew: `0a0497535b80c4357e5412ce41c691567c24e42dc0513ade3ae341b6981627b3`
* actual: `e4791d58cc0a0651d6d9b98e371d0b6aea2a8ffa0fdf7b9e87acf58ca9d0c4db`

This seems that has been a common problem in the past, see https://github.com/Homebrew/homebrew-core/issues/18044

And I've found that at least the assh project has experienced the same issue:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/assh.rb
* homebrew: `e04de57ab048f1abee75e9e739514c4f47e6cbb8acacb9d58a6e2892df30dc42`
* actual: `17656a6ac562707d6e85df44c1ccd04276fb1c08f1ff6a002291f4cb88880069` 

See also https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745

**Comment by dopey** [comment]
fixed by -> 3e1e2dcfa54298e0fb86e0be86ab36d79f36473e

We're using our own uploaded tarballs instead of the ones provided by default by git.
