### ISSUE TITLE
[Bug]: cannot install certs on debian

### ISSUE THREAD

**Issue by ju1ius** [smallstep/cli#1043]
Hi,

### Steps to Reproduce

1. The step CLI is installed locally from the [latest debian package](https://github.com/smallstep/cli/releases/tag/v0.25.0)
2. A private CA is running from a docker container using the [official image](https://hub.docker.com/r/smallstep/step-ca):
    ```sh
    $ step ca health --ca-url=https://localhost:9000
    ok
    ```
3. Running the following command:
    ```sh
    $ step ca bootstrap --ca-url=https://localhost:9000 --fingerprint <ca-fingerprint> --install
    ```
    Produces the following output:
    ```
    The root certificate has been saved in /home/<user>/.step/certs/root_ca.crt.
    The authority configuration has been saved in /home/<user>/.step/config/defaults.json.
    Installing the root certificate in the system truststore...
    install is not supported on this system
    ```
4. Running the following command:
    ```sh
    $ step certificate install /home/<user>/.step/certs/root_ca.crt
    ```
    Produces the following output:
    ```
    failed to install /home/<user>/.step/certs/root_ca.crt: install is not supported on this system
    ```

### Your Environment

* OS - Debian Sid
* `step` CLI Version - 0.25.0 

### Expected Behavior

The root CA certificate should be installed in the specified  trustores.

### Actual Behavior

Installation fails.

### Additional context

Using the step cli built from source from the master branch yields the same results.

FWIW, `mkcert` has no problem installing certs on this machine.

See also: https://github.com/smallstep/truststore/issues/23

**Comment by maraino** [comment]
This should be fixed by https://github.com/smallstep/cli/pull/1053
