### ISSUE TITLE
Generated Ed25519 keypair is invalid

### ISSUE THREAD

**Issue by ndiezel0** [smallstep/cli#105]
### Subject of the issue
Generated Ed25519 private and public keys share same `d` and `x` respectively.

### Your environment
* OS - Ubuntu 18.04
* Version - Smallstep CLI/0.9.0-dev (linux/amd64) Release Date: 2019-03-26 22:21 UTC

### Steps to reproduce
Generate OKP key with
```step crypto jwk create pub.json priv.json --kty OKP --crv Ed25519```

Decrypt JWE of priv.json.
Compare `x` in pub.json and `d` in priv.json

### Expected behaviour
`x` in pub.json and `x` in priv.json MUST be the same.
For reference: https://tools.ietf.org/html/rfc8037#appendix-A.1

### Actual behaviour
`x` in pub.json is the same as `d` in priv.json

### Additional context
The issue seems to go back to this line of code in the library that step-cli uses:
https://github.com/square/go-jose/blob/v2.3.0/jwk.go#L488
Where go-jose uses public key in private key field.
It is evidenced by these lines from cryptomodule:
https://github.com/golang/crypto/blob/master/ed25519/ed25519.go#L90

**Comment by maraino** [comment]
```sh
$ step crypto jwk create pub.json priv.json --kty OKP --crv Ed25519
Please enter the password to encrypt the private JWK:
Your public key has been saved in pub.json.
Your private key has been saved in priv.json.
$ cat pub.json priv.json
{
  "use": "sig",
  "kty": "OKP",
  "kid": "Z4R40sOeX0tzKvWBAW-JO8mLUUvoDBFFRUclQreeXKY",
  "crv": "Ed25519",
  "alg": "EdDSA",
  "x": "wwInyZ8Q6p3pjC_5Rtvcvco8r2v8UMAqRPq2xuQT2ZE"
}{
  "protected": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjEwMDAwMCwicDJzIjoiaU0zRkFBUFd0aGVDbFNIcVhoNkhhZyJ9",
  "encrypted_key": "IvSNEJ_JQDhRFcSxkYpRbxf_HwYJ-A1ZpWUNQKyvArrv2ZFkh76_Wg",
  "iv": "TVwignMF6oGJcGUq",
  "ciphertext": "98zBNIX7bmmYI35Lu8OnbqHNxk3cahXBiasugfD9c4Jw_XVYmA-wgWu4_93iZOYoGZarUnM9V5Uo81ctNfmKfiJOUnXAK-w2_ErvAT_EcCfxhuzUdYRw_sZWjnDC7sCdZOeFiJrXQcGtXyDnCwsKRkMLJHyrjUmXlRuKHjUrM1rjQ2BWcGAxnAL2CiA1138ndqdFAEtxcDwaPxEQHXB28mKkhyvmC0ry2GnoyIA_T7nwpdJEdLIYgKKa0b5A2Q-aVo_wdp1pcdZLyKBfo5QR",
  "tag": "4VTCR9-TqMLpdPZIOGR_uQ"
}
$ cat priv.json | step crypto jwe decrypt
Please enter the password to decrypt the content encryption key:
{"use":"sig","kty":"OKP","kid":"Z4R40sOeX0tzKvWBAW-JO8mLUUvoDBFFRUclQreeXKY","crv":"Ed25519","alg":"EdDSA","x":"q22qpnU90uOXGSYftcYe8-3iR6N7ikJtkF78Hbw6uRg","d":"wwInyZ8Q6p3pjC_5Rtvcvco8r2v8UMAqRPq2xuQT2ZE"}
```

**Comment by maraino** [comment]
@ndiezel0: I've submitted a PR to go-jose, take a look if you can, https://github.com/square/go-jose/pull/224
Thanks for noticing this.
