### ISSUE TITLE
[Bug]: document for leaf certificate template contains typo

### ISSUE THREAD

**Issue by zhangyoufu** [smallstep/cli#1051]
### Steps to Reproduce

```shell
% step help certificate create | grep -F typeIs
          {{- if typeIs "*sa.PublicKey" .Insecure.CR.PublicKey }}
% step help certificate sign | grep -F typeIs
          {{- if typeIs "*sa.PublicKey" .Insecure.CR.PublicKey }}
```

### Your Environment

```
% step version
Smallstep CLI/0.25.0 (darwin/amd64)
Release Date: 2023-09-27 12:02 UTC
```

### Expected Behavior

The type should be `*rsa.PublicKey`

### Actual Behavior

The output is `*sa.PublicKey`

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
Hi @zhangyoufu, thank you for reporting this. I've opened a PR: #1052
