### ISSUE TITLE
JWS Sign doesn't use stdin content

### ISSUE THREAD

**Issue by ndiezel0** [smallstep/cli#109]
### Subject of the issue
You can't pipe commands with `step crypto jws sign`, as it ignores stdin.

### Your environment
* OS - Ubuntu 18.04
* Version - Smallstep CLI/0.9.2-dev (linux/amd64) Release Date: 2019-04-10 20:30 UTC

### Steps to reproduce
```bash
$ step crypto jwk create ed.pub.json ed.json --kty OKP --crv Ed25519Please enter the password to encrypt the private JWK: 
Your public key has been saved in ed.pub.json.
Your private key has been saved in ed.json.
$ echo "lolkek" | step crypto jws sign --key ed.json 
Please enter the password to decrypt ed.json: 
eyJhbGciOiJFZERTQSIsImtpZCI6IjF0dlBGR3VwWTJWbmRNbFMwMFZma2JDM1hvUWNEdjhRTm5xdjBiUnVkYkEifQ..Ob_pqlN3gs2P2kLYZKCF3z510V0T5v8NOq1M4kX8HK0cyDVqm1jaNHneg6Vo8tY_6ANyAavZDu7P9iqlyRIMDw
$ echo "eyJhbGciOiJFZERTQSIsImtpZCI6IjF0dlBGR3VwWTJWbmRNbFMwMFZma2JDM1hvUWNEdjhRTm5xdjBiUnVkYkEifQ..Ob_pqlN3gs2P2kLYZKCF3z510V0T5v8NOq1M4kX8HK0cyDVqm1jaNHneg6Vo8tY_6ANyAavZDu7P9iqlyRIMDw" | step crypto jws verify --key ed.pub.json --json
{
  "header": {
    "alg": "EdDSA",
    "kid": "1tvPFGupY2VndMlS00VfkbC3XoQcDv8QNnqv0bRudbA"
  },
  "payload": "",
  "signature": "Ob_pqlN3gs2P2kLYZKCF3z510V0T5v8NOq1M4kX8HK0cyDVqm1jaNHneg6Vo8tY_6ANyAavZDu7P9iqlyRIMDw"
}
```

### Expected behaviour
Piping work as per Documentation.

### Actual behaviour
STDIN is ignored

### Additional context
Using [Process Substitution](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html#Process-Substitution) is the workaround and should be used in [Documentation](https://smallstep.com/docs/cli/crypto/jws/) if it's not an easy thing to fix.

Example:

```bash
$ step crypto jws sign <(echo "lolkek") --key ed.json 
Please enter the password to decrypt ed.json: 
eyJhbGciOiJFZERTQSIsImtpZCI6IjF0dlBGR3VwWTJWbmRNbFMwMFZma2JDM1hvUWNEdjhRTm5xdjBiUnVkYkEifQ.bG9sa2VrCg.t7XOxH1zVL8WzGuZ69mCoIVC3xiamu_eEpBkeHR2IcZdRvTBFP6OH5MjWeG8BlMT7pSV07nNogD0lhwZ52nDCw
$ echo "eyJhbGciOiJFZERTQSIsImtpZCI6IjF0dlBGR3VwWTJWbmRNbFMwMFZma2JDM1hvUWNEdjhRTm5xdjBiUnVkYkEifQ.bG9sa2VrCg.t7XOxH1zVL8WzGuZ69mCoIVC3xiamu_eEpBkeHR2IcZdRvTBFP6OH5MjWeG8BlMT7pSV07nNogD0lhwZ52nDCw" | step crypto jws verify --key ed.pub.json --json
{
  "header": {
    "alg": "EdDSA",
    "kid": "1tvPFGupY2VndMlS00VfkbC3XoQcDv8QNnqv0bRudbA"
  },
  "payload": "bG9sa2VrCg",
  "signature": "t7XOxH1zVL8WzGuZ69mCoIVC3xiamu_eEpBkeHR2IcZdRvTBFP6OH5MjWeG8BlMT7pSV07nNogD0lhwZ52nDCw"
}

```

**Comment by maraino** [comment]
@ndiezel0: at this moment, the best workaround is use `-`:
```sh
$ echo "lolkek" | step crypto jws sign --key ed.json - | step crypto jws verify --key ed.pub.json --json
Please enter the password to decrypt ed.json:
{
  "header": {
    "alg": "EdDSA",
    "kid": "_3G12SlQ6V78Nrv7nZkC61JWJBqcog-tMBa1yHt7y9M"
  },
  "payload": "bG9sa2VrCg",
  "signature": "e3PUr_i15gOmwHj-fCSwDELpc0MbKKSo1lpr-Qsw-hHB29rXtPC_NzZgYNpILrKrK0IwbfZpel2hxTpESX9RDA"
}
```

It's not properly documented in the examples on `step crypto jws --help` but it's in the usage of `step crypto jws sign --help`

We need to improve the management of Stdin/Stdout instead of forcing extra parameters on other commands

**Comment by ndiezel0** [comment]
As per `step crypto jws sign --help`:

> By **default**, the payload to sign is read from STDIN...

So at least clarification in documentation is certainly required.

**Comment by maraino** [comment]
After some more testing, this issue happens in Linux but not on macOS, the use of `-` is not required on macOS. So there should be a problem with this code:
https://github.com/smallstep/cli/blob/master/command/crypto/jws/sign.go#L287-L295

**Comment by maraino** [comment]
Looks like the solution that will work on both on Linux and macOS is:
```go
diff --git a/command/crypto/jws/sign.go b/command/crypto/jws/sign.go
index 0d25d1f..e28c611 100644
--- a/command/crypto/jws/sign.go
+++ b/command/crypto/jws/sign.go
@@ -289,7 +289,7 @@ func readPayload(filename string) ([]byte, error) {
                if err != nil {
                        return nil, errors.Wrap(err, "error reading data")
                }
-               if st.Size() == 0 {
+               if st.Size() == 0 && st.Mode()&os.ModeNamedPipe == 0 {
                        return []byte{}, nil
                }
                return utils.ReadAll(os.Stdin)
```

**Comment by alanmiller** [comment]
Is this the same error for **step ca token** command?  On linux all these attempts fail with
 `too many positional arguments were provided in 'step ca token <subject>'`

`echo "mypas" | step ca token <subject> <other args> - `
`step ca token  myhost.mydomain <subject> <other args> - <(echo "mypass")`

When I remove the dash in attempt 1 I am prompted for the password and the command succeeds:

**Comment by maraino** [comment]
@alanmiller: No `step ca token` does not accept parameters from stdin. And at this moment we are not accepting passwords being passed that way. If you want to bypass the password prompt you should use
```sh
step ca token foo.bar.zar --password-file mypass.txt
```

**Comment by alanmiller** [comment]
@maraino I am using  `--password-file` option but it still prompts for the password to decrypt the intermediate_ca_key e.g.:
`Please enter the password to decrypt /home/alan/.step/secrets/intermediate_ca_key`

**Comment by maraino** [comment]
This only happens if you are using the `--offline` mode, right? You can add the intermediate password in your `$STEPPATH/config/ca.json`. Something like:
```js
{
   "root": "/Users/mariano/.step/certs/root_ca.crt",
   "crt": "/Users/mariano/.step/certs/intermediate_ca.crt",
   "key": "/Users/mariano/.step/secrets/intermediate_ca_key",
   "password": "my-secret-password",
   ...
}
```


More information:
https://github.com/smallstep/certificates/blob/master/docs/GETTING_STARTED.md

**Comment by alanmiller** [comment]
@maraino Yes, I am using `--offline` mode. And **Yes!**, adding the password to ca.json works for me. Thanks!
