### ISSUE TITLE
[Bug]: Missing Armv7 build artifact in releases

### ISSUE THREAD

**Issue by TimothyHarder** [smallstep/cli#1126]
### Steps to Reproduce

NA

### Your Environment

NA

### Expected Behavior

armv7 build artifact in releases

### Actual Behavior

Arm64 artifacts are found, but not armv7 for step-cli.

### Additional Context

Armv7 is found for step-ca, [and is a target build](https://smallstep.com/docs/step-cli/installation/#linux-binaries), but not found in the releases for step-cli.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
@TimothyHarder it seems we do create armv7 binaries, but they're not named `step-cli`; just `step`: https://github.com/smallstep/cli/releases/download/v0.25.2/step_linux_0.25.2_armv7.tar.gz. I'm not sure why it doesn't have `-cli`; will discuss in upcoming open source triage.

**Comment by TimothyHarder** [comment]
@hslatman Thank you! My Pi Zero was falling over trying to compile it. I will reference the `step` binary for armv7.
