### ISSUE TITLE
[Bug]:  Version number mismatch between downloaded deb package and installed

### ISSUE THREAD

**Issue by acbekoac** [smallstep/cli#1137]
### Steps to Reproduce

adjust the version number within the deb Package

### Your Environment

* OS -Debian 11
* `step` CLI Version - 0.25.2

### Expected Behavior

The version number shown during "dpki -i" should match the one in the name of the deb package

### Actual Behavior

sudo dpkg -i /tmp/step-ca_amd64_0.25.3-rc3.deb 
(Lese Datenbank ... 34685 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../step-ca_amd64_0.25.3-rc3.deb ...
Entpacken von step-ca (0.25.2) über (0.25.2) ...
step-ca (0.25.2) wird eingerichtet ...

sudo dpkg -i /tmp/step-cli_amd64_0.25.3-rc3.deb 
(Lese Datenbank ... 34685 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../step-cli_amd64_0.25.3-rc3.deb ...
Entpacken von step-cli (0.25.2) über (0.25.2) ...
step-cli (0.25.2) wird eingerichtet ...

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
Hey @acbekoac,

It's possible the mismatch happens due to the `-rc3` suffix. The version should be set automatically based on the git tag. We'll cut the `v0.26.0` soon, so I'm curious if it'll be set correctly for that.

**Comment by hslatman** [comment]
Hey @acbekoac, we've released https://github.com/smallstep/cli/releases/tag/v0.26.0. Are you seeing the correct tag now?

**Comment by acbekoac** [comment]
Hi,

I can see the correct version now - see my script debug below

./check_for_newer_smallstep_version.sh 
+ LOCAL_VERSION=
+ REMOTE_VERSION=
+ readonly VERSION_URL=https://github.com/smallstep/cli/releases
+ VERSION_URL=https://github.com/smallstep/cli/releases
+ [[ -f /usr/bin/step ]]
++ /usr/bin/step version
++ sed -e 's/.*CLI\///;s/ (.*//'
++ grep CLI
+ LOCAL_VERSION=0.26.0
++ curl -s https://github.com/smallstep/cli/releases
++ head -n 1
++ grep '<h2.*Step CLI '
++ sed -e 's/.*Step CLI v//;s/ (.*//'
+ REMOTE_VERSION=0.26.0
+ [[ 0.26.0 == \0\.\2\6\.\0 ]]
+ echo 'Step-CLI/CA - latest version installed'
Step-CLI/CA - latest version installed
+ exit 0


Issue seems fixed, so case can be closed

thx

**Comment by hslatman** [comment]
Great, thank you for your report, @acbekoac 🙂  Feel free to reopen in case it happens again.
