### ISSUE TITLE
question: did you move the 0.26.0 tag?

### ISSUE THREAD

**Issue by colemickens** [smallstep/cli#1145]
### Steps to Reproduce

Did you move the 0.26.0 tag after publishing?

1. I noticed that we had a hash mismatch for 0.26.0 sources.
2. While looking into it, I noticed that one of the nixpkgs automation accounts sent *two different PRs* for the same pacakge bump, indeed both with different hashes.

In light of recent events, I'd like to understand how this is possible and happened. And, if you did move the tag, I'd ask you that you consider *not* doing this in the future.

### Your Environment

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Additional Context

*n/a*

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
Hi @colemickens, no, as far as we know, we did not move the tag. Feel free to reopen if it reoccurs.
