### ISSUE TITLE
[Bug]: Binaries are not available for latest 0.28.1 release

### ISSUE THREAD

**Issue by tedo-benchling** [smallstep/cli#1320]
### Steps to Reproduce

Documentation for installation on debian tell you to go latest releases and download .deb package on https://smallstep.com/docs/step-cli/installation/#debian-ubuntu

```
wget https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.deb
```
Fails with a 404

### Your Environment

* OS - Debian linux
* `step` CLI Version - N/A

### Expected Behavior

Should be able to download from that URL

### Actual Behavior

404 error is returned

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jsirianni** [comment]
I am seeing the same thing, unable to download latest AMD64 DEB package.

**Comment by hslatman** [comment]
We're aware of the issue. It should be fixed after https://github.com/smallstep/cli/pull/1319 gets merged.

**Comment by hslatman** [comment]
A new release was created: https://github.com/smallstep/cli/releases/tag/v0.28.2.
