### ISSUE TITLE
Provisioner prompt barfs on unknown provisioner (if cli and certificates have incompatible versions)

### ISSUE THREAD

**Issue by dopey** [smallstep/cli#134]
### Subject of the issue
The `cli` fails with an exception when it encounters an unknown provisioner in the ca config. This can happen when the versions for the `certificates` and `cli` are incompatible

### Expected behaviour
1) Provide a useful error - letting the user know that the `cli` likely needs to be updated.
2) Log a) unkown provisioner b) steps that should be taken to fix, and attempt to continue execution. 

### Actual behaviour
Catastrophic failure

**Comment by sourishkrout** [comment]
Done.
