### ISSUE TITLE
When initializing the CA with --ssh the global claims in the ca.json should set `enableSSHCA: true`

### ISSUE THREAD

**Issue by dopey** [smallstep/cli#149]
### Provisioners are not initially enabled for SSH even after init-ing the CA using `--ssh`
After initializing `step-ca` with `--ssh` I would expect that the default provisioner is enabled for ssh. Otherwise the experience is very confusing. The user is told they can't create ssh certificates, even though they just initialized the CA using the `--ssh` option.

### Expected behaviour
SSH certificates should work out of the box without extra user intervention in the ca.json (which is currently required).

### Additional context
Consider setting the global claims attribute to `true` (if `--ssh`) and letting new provisioners set it to false when necessary.

**Comment by robomfeinberg** [comment]
I tested this from the branch. `step ca init --ssh` does work as expected. Thanks!
