### ISSUE TITLE
AUR package sha256 hash is wrong

### ISSUE THREAD

**Issue by nazar554** [smallstep/cli#152]
See the comment on AUR. That hash seems to be `Default.aspx` if you Google for it, maybe `updpkgsums` was ran before that actual release on GitHub (and it generated hash of a 404 page).

https://aur.archlinux.org/packages/step-cli-bin/

**Comment by dopey** [comment]
hmm, weird. I'll look into this today.

**Comment by dopey** [comment]
I believe this should be fixed now. Think maybe you're right about having run it before the release was ready. Thanks for letting us know! (And of course lmk if it's still broken. tested locally and it seemed to work).
