### ISSUE TITLE
Add support to create csr for intermediate certs

### ISSUE THREAD

**Issue by maraino** [smallstep/cli#159]
### Description
Right now `step certificate create` can only create certificate signing requests (CSR) for leaf certificates. We should be able to create CSRs for intermediate certificates too. 

```sh
# To create a leaf csr the commands will be
step certificate create --csr ...  (currently supported)
step certificate create --csr --profile leaf

# To create an intermediate csr
step certificate create --csr --profile intermediate

# This should display an error
step certificate create --csr --profile root
```

**Comment by wesselvdv** [comment]
Any idea when someone is going to work on this? This would solve an issue we're experiencing with deploying new intermediate CA per account for our customers. If we could have the Root CA sign a CSR instead of having to pass along the Intermediate private key that'd be very awesome!

**Comment by dopey** [comment]
Hey @wesselvdv it's likely that we won't be able to give this issue the time it deserves until early next year. However, if you were willing to run a bespoke build just for your purposes, then it shouldn't be difficult for you to make the right modifications. Couple questions:

1) Are you using just the `cli` or are you also using the [step-ca](https://github.com/smallstep/certificates)? 
2) Do you have a golang dev environment and would you be comfortable making a few changes to the `cli` codebase and then running the build that you would make from your branch? It would likely be a special build that could only create intermediate certificates given a CSR.

**Comment by wesselvdv** [comment]
> Hey @wesselvdv it's likely that we won't be able to give this issue the time it deserves until early next year. However, if you were willing to run a bespoke build just for your purposes, then it shouldn't be difficult for you to make the right modifications. Couple questions:
> 
> 1. Are you using just the `cli` or are you also using the [step-ca](https://github.com/smallstep/certificates)?
> 2. Do you have a golang dev environment and would you be comfortable making a few changes to the `cli` codebase and then running the build that you would make from your branch? It would likely be a special build that could only create intermediate certificates given a CSR.

Yes, I am using both. Any pointers where I would have to make some changes?

If found the following that I think would require some changes:

https://github.com/smallstep/certificates/blob/0a96062b7696db218cf42c046e8dbec19b176114/authority/tls.go#L87

https://github.com/smallstep/cli/blob/9b30694cc931de061faf0fa96cffb90b29ec1aba/command/certificate/create.go#L306

Especially the lines of code in the CLI would require some more extensive changes?

**Comment by dopey** [comment]
Take a look at this branch https://github.com/smallstep/cli/tree/no-path-len. The changes are really small, all it's doing is removing the path-len constraint for root and intermediate profiles. If you rebuild `certificates` after updating the version of `cli` using `go get github.com/smallstep/cli@no-path-len`, then you should be able to bootstrap your `pki` using a certificate chain that allows downstream chains of any length. 

When you run `step ca init` you'll get a root and intermediate cert without pathlen constraints (which you'll need for signing and verifying intermediate CSRs). 

Unfortunately, I don't know off the top of my head the OID extensions that mark a certificate as a CA, but I imagine you'll need to set that in the CSR (golang doesn't appear to have a friendly way of doing this in a CSR -> https://golang.org/pkg/crypto/x509/#CertificateRequest). Then you'll need to get `x509util.NewLeafProfileWithCSR(...)` (called here https://github.com/smallstep/certificates/blob/master/authority/tls.go#L87) to respect those extensions when generating the certificate template. 

Let me know once you've taken a look and if you have any questions.

**Comment by wesselvdv** [comment]
Got it to work! I’ll detail it here when I have time.

**Comment by dopey** [comment]
Hey, that's awesome! Details would be super helpful when you have the chance, as we've had interest from other users in setting this up.

**Comment by wesselvdv** [comment]
You can see the changes I made in my forks:

https://github.com/Synadia/cli
https://github.com/Synadia/certificates

I had to add a `NewIntermediateProfileWithCSR` to the crypto utility in the `cli` so I could just swap the 'NewLeafProfileWithCSR' with `NewIntermediateProfileWithCSR` in the `certificates`.

Go is quite annoying with it's module dependencies if you're forking. Had to add a `replace` directive in `go.mod` to make sure it would build with our fork instead of the original.

**Comment by dopey** [comment]
Awesome! `NewIntermediateProfileWithCSR` is a great idea.

One note. https://github.com/Synadia/cli/commit/563cf6ea5ae943cb11d0dca2467d8609dc47f467#diff-5c9981940f4324608b7694cfa5ebce48R41-R42 - I think you want to be setting `cert.ExtraExtensions = csr.Extensions`. The documentation (https://godoc.org/crypto/x509#Certificate) is a bit confusing, but `ExtraExtensions` are used when marshaling the certificate, and `Extensions` should only be populated when unmarshaling the certificate. Here (https://github.com/smallstep/certificates/blob/master/authority/tls.go#L172-L179) is an example of what we do in `renew`.

With respect to go mod. We run into the same thing all the time. We're running on a ton of branches right now so we're always using the `replace` directives.

Question for you, how are you creating intermediate CSRs? I assume you're not using `step` for that.

**Comment by wesselvdv** [comment]
> One note. [Synadia@563cf6e#diff-5c9981940f4324608b7694cfa5ebce48R41-R42](https://github.com/Synadia/cli/commit/563cf6ea5ae943cb11d0dca2467d8609dc47f467#diff-5c9981940f4324608b7694cfa5ebce48R41-R42) - I think you want to be setting `cert.ExtraExtensions = csr.Extensions`

Thanks for the pointer, I'll go ahead and change it! I have to be honest that I just copied over literally what is used in in `NewLeafProfileWithCSR` in https://github.com/smallstep/cli/blob/0e978e59cc617219928c5ceb63ea19892a6dc5d3/crypto/x509util/leafProfile.go#L58-L59. My knowledge on the subject of certificates is rather absent, so I just went with the defaults you guys are using for others.

> Question for you, how are you creating intermediate CSRs? I assume you're not using `step` for that.

I am actually, I am using it with an AWS provisioner to bootstrap entire certificate chains (Root + Intermediate) for our `IoT Core` devices. Where the Root CA lives in our root account, and we have multiple Intermediate CAs living in our customer accounts. (test, acc, prod, demo etc.) We end up with the following chain:

`Root CA: [Root Certificate, Intermediate Certificate]` -> `Intermediate CA: [Intermediate Certificate, Intermediate Certificate]` -> `Leaf Certificate`.

I automated the entire process using Terraform so we can rollout new Intermediate CAs easily when bootstrapping our customer accounts. The only missing piece was getting the `Intermediate CA root` certificate using a CSR with an AWS provisioner, else I would either have to share the root ca intermediate private key, the password of the root ca provisioner or I would have to login to the Root CA to generate one 'offline'.

**Comment by dopey** [comment]
> Thanks for the pointer, I'll go ahead and change it! I have to be honest that I just copied over literally what is used in in `NewLeafProfileWithCSR` in

Yeah, that's due to a bug in our code that I haven't gotten around to fixing. People don't normally get caught on it, but if you were to submit a non-`step` generated CSR then you'd probably hit it. I'll make a note to fix that.

Ok, cool. I understand how your code is working. Instead of using a intermediate CSR (that would be a CSR that has an OID extension specifying that it should be `IsCA: true` - `step` can't do this for you right now), the NewIntermediateProfileWithCSR just uses the default intermediate template which has `IsCA: True`. Clever! I think when we get around to implementing this ourselves we'll need to respect the extension from the CSR.

Really cool that you've been able to get things automated as you described. And thanks for letting us know about the process and the changes you needed to make. We'll use this as a "use-case"  that we want solved out of the box when we're developing the next release.

**Comment by maraino** [comment]
Creating a CSR with the intermediate extensions is probably not the right solution, signing an intermediate CSR is now supported like this:

```sh
# Create a CSR
step certificate create --csr "My Intermediate CA" intermediate.csr intermediate.key
# Sign the intermediate
step certificate sign --profile intermediate-ca intermediate.csr root_ca.crt root_ca.key
```

On `step-ca` the signing of an intermediate is supported templates.

**Comment by maraino** [comment]
Creating a CSR with the intermediate extensions is probably not the right solution, signing an intermediate CSR is now supported like this:

```sh
# Create a CSR
step certificate create --csr "My Intermediate CA" intermediate.csr intermediate.key
# Sign the intermediate
step certificate sign --profile intermediate-ca intermediate.csr root_ca.crt root_ca.key
```

On `step-ca` the signing of an intermediate is supported templates.
