### ISSUE TITLE
Add support for exporting to PKCS12

### ISSUE THREAD

**Issue by alanchrt** [smallstep/cli#161]
### What would you like to be added

The ability to export keys and certs packaged in PKCS12 format.

### Why this is needed

It may make sense to be more broad than just PKCS12, but it would be nice to have this one since it seems to be preferred by Java (and I think MS) software.

**Comment by maraino** [comment]
Consider the use of the package https://godoc.org/software.sslmate.com/src/go-pkcs12, a fork of the frozen golang.org/x/crypto/pkcs12

**Comment by doug-fitzmaurice-rowden** [comment]
Implemented in #372

**Comment by maraino** [comment]
Fixed with #372
