### ISSUE TITLE
step-ca does not listen on address for `step ca init -address`

### ISSUE THREAD

**Issue by matutter** [smallstep/cli#165]
### Subject of the issue
The `-address` argument passed to `step ca init` does not change the address `step-ca` server will listen on because the "ca.json" doesn't contain the value. In the reproducer below `step-ca` will serve on port 8443 regardless of `$CA_PORT` used with `-address` option.

### Your environment
* OS - `ubuntu:bionic` (official docker image)
* Version - latest

### Steps to reproduce

[Repo here](https://github.com/matutter/step-ca-example)

**docker-entrypoint.sh**

```bash
#!/bin/bash

echo CA_PORT=$CA_PORT

step ca init \
  -name="The Step CA Test" \
  -dns=localhost \
  -address=127.0.0.1:$CA_PORT \
  -provisioner=XXXXXXXXXX@XXXXXXX.com \
  -password-file=/files/ca.password && \
step-ca --password-file=/files/ca.password /.step/config/ca.json
```

**docker-compose up output**

```
ca_1  | CA_PORT=10433
ca_1  | 
ca_1  | Generating root certificate... 
ca_1  | all done!
ca_1  | 
ca_1  | Generating intermediate certificate... 
ca_1  | all done!
ca_1  | 
ca_1  | ✔ Root certificate: /root/.step/certs/root_ca.crt
ca_1  | ✔ Root private key: /root/.step/secrets/root_ca_key
ca_1  | ✔ Root fingerprint: 2f70cfc7f3f09e089df345c896f2d0e7825c82fdefa002b733a50582e8140bde
ca_1  | ✔ Intermediate certificate: /root/.step/certs/intermediate_ca.crt
ca_1  | ✔ Intermediate private key: /root/.step/secrets/intermediate_ca_key
ca_1  | ✔ Default configuration: /root/.step/config/defaults.json
ca_1  | ✔ Certificate Authority configuration: /root/.step/config/ca.json
ca_1  | ✔ Database: /root/.step/db
ca_1  | 
ca_1  | ...
ca_1  | 
ca_1  | 2019/09/28 13:56:42 Serving HTTPS on 127.0.0.1:8443 ...
```

### Expected behaviour
`step-ca` should start a server listening on `127.0.0.1:10443`.

### Actual behaviour
`step-ca` will start a server listening on `127.0.0.1:8443`.

### Additional context

I'm following the [Getting Started Guide](https://smallstep.com/docs/getting-started/) on a single host.

**Comment by maraino** [comment]
Hi @matutter, I've downloaded your docker-compose setup, and the ca is starting in the right port:
```
Attaching to step-ca-example_ca_1, step-ca-example_server_1
ca_1      | STEPPATH=/.step
ca_1      | CA_PORT=10433
ca_1      | SERVER_HOSTNAME=localhost
ca_1      |
ca_1      | Generating root certificate...
ca_1      | all done!
ca_1      |
ca_1      | Generating intermediate certificate...
ca_1      | all done!
ca_1      |
ca_1      | ✔ Root certificate: /.step/certs/root_ca.crt
ca_1      | ✔ Root private key: /.step/secrets/root_ca_key
ca_1      | ✔ Root fingerprint: 93c392296882490ae5d7d9b1f730ffcd8f82d1a9ac1a186427548b8a0e0bf2cd
ca_1      | ✔ Intermediate certificate: /.step/certs/intermediate_ca.crt
ca_1      | ✔ Intermediate private key: /.step/secrets/intermediate_ca_key
ca_1      | ✔ Default configuration: /.step/config/defaults.json
ca_1      | ✔ Certificate Authority configuration: /.step/config/ca.json
ca_1      | ✔ Database: /.step/db
ca_1      |
ca_1      | Your PKI is ready to go. To generate certificates for individual services see 'step help ca'.
ca_1      |
ca_1      | FEEDBACK 😍 🍻
ca_1      |       The step utility is not instrumented for usage statistics. It does not
ca_1      |       phone home. But your feedback is extremely valuable. Any information you
ca_1      |       can provide regarding how you’re using `step` helps. Please send us a
ca_1      |       sentence or two, good or bad: feedback@smallstep.com or join
ca_1      |       https://gitter.im/smallstep/community.
ca_1      | 2019/09/30 18:07:54 Serving HTTPS on ca:10433 ...
```

I've also verified on my environment that the `step ca init` command that you provides is working properly.

**Comment by matutter** [comment]
I’ve since updated that project. Sorry for not commenting earlier.

The issue can be seen by removing the quotes ‘-address=localhost:8888’ and ‘-address=“localhost:8888”’ are parsed differently.

**Comment by matutter** [comment]
After trying again, even with the older commit, I also cannot reproduce it. I'm curious if this was a result of copy-n-pasting from [the docs](https://smallstep.com/docs/cli/ca/init/) because they use a the `–` character next to commands and not `-`. The shell doesn't parse the former as a correct argument.
