### ISSUE TITLE
Provide an output directory argument for `step ca init`

### ISSUE THREAD

**Issue by matutter** [smallstep/cli#166]
### What would you like to be added

An option to `step ca init` that sets the directory where files are created. It could be an explicit argument like `--out` or a positional argument.

```bash
# Output to /ca, step ca init [OPTIONS]
step ca init -out=/ca
# Output to /ca, step ca init [OPTIONS] [OUT]
step ca init /ca
```

### Why this is needed

I've been trying use of step-ca with Ansible and there are some complicated cases  when using the non-interactive CLI.

This is the command being run and it has different behavior based on some non-obvious conditions.

First I init the CA.

```bash
  step ca init \
    -name="The Step CA Tutorial" \
    -dns=localhost \
    -address="0.0.0.0:$CA_PORT" \
    -provisioner=mcutter.svc@gmail.com \
    -password-file=/files/ca.password
```

Then to run the server I have to have the path to `ca.json`. But where is it?

- When run as `root` the file is `/root/.step/config/ca.json`
- When run as another user the file is `/home/$USER/.step/config/ca.json`
- When run as another user without a $HOME directory the file is `/.site/config/ca.json` 

So to automate `step ca init` I have to check for all these cases about the the user's environment.

**Comment by mmalone** [comment]
Try setting the `STEPPATH` environment variable.

You can also use `step path` (or `$(step path)`) to generically locate the root directory. It returns `$STEPPATH` if set, else `~/.step` (the default).

Do these mechanisms do what you need?

**Comment by matutter** [comment]
Thanks. That actually solved the issue nicely and consistently between every `step` command. Might want to mention that earlier in [the docs](https://smallstep.com/docs/getting-started/).

**Comment by mmalone** [comment]
Yea good call. Definitely some sort of docs issue since you weren’t able to immediately find it!

FYI all command-line flags also have env var equivalents. Just uppercase the flag name, add `STEP_` to the beginning, and replace `-` with `_`. So `-ca-url` becomes `STEP_CA_URL`.
