### ISSUE TITLE
Not implemented error

### ISSUE THREAD

**Issue by ShotgunSpider** [smallstep/cli#168]
Hi i've installed the step-cli and step-ca packages from this link https://github.com/smallstep
i've done the getting started guide on setting up step-ca but even if i run the example commands i just get the error that the CA is correct and Not Implemented, any idea if i'm missing any steps?

**Comment by maraino** [comment]
Hi @ShotgunSpider, can you tell us which commands returns the not implemented error and which OS are you using?

**Comment by ShotgunSpider** [comment]
i'm running the example step ssh certificate mariano@work id_ecdsa and im running on ubuntu 19.04

**Comment by ShotgunSpider** [comment]
I actually found another post about this https://github.com/smallstep/cli/issues/160
i've ran with --ssh and got the keys for ssh created as well but now i got the error 
SSH Agent: error connecting with ssh-agent: dial unix: missing address

**Comment by maraino** [comment]
Ok now it makes more sense, `Not Implemented` was because ssh was not enabled, in the `step-ca` logs you will see a more detailed error `authorize: ssh signing is not enabled`, on `step` we are only passing the HTTP 501 error (Not Implemented)

And error connecting with ssh-agent: dial unix: missing address is because you might not have the ssh-agent running. Just run in your terminal `ssh-agent` and you will see that the environment variable `SSH_AUTH_SOCK` will be available and you will be able to connect.

In any case the certificate should be created.

**Comment by maraino** [comment]
> In any case the certificate should be created.

But the command cannot add it to the agent.

**Comment by maraino** [comment]
And you might need to run `eval $(ssh-agent)` instead of just `ssh-agent`

**Comment by ShotgunSpider** [comment]
ssh-agent is running, and step ssh is creating the keys/certs just that i still get the error ssh-agent: dial unix: missing address

**Comment by maraino** [comment]
This is because the environment variable `SSH_AUTH_SOCK` is not set or is set to the wrong address. On my system, the OS sets up the agent by default and all terminal sessions have that variable set, I don't really know what's the best way to do this on ubuntu.

**Comment by ShotgunSpider** [comment]
what OS do you use for step? i installed on ubuntu but i prefer to use centos

**Comment by maraino** [comment]
@ShotgunSpider We mainly use macOS and archlinux, for both we get the SSH_AUTH_SOCK automatically set, I'm sure ubuntu and centos has an easy way to set this up.
As a workaround, you can set this up using something like https://github.com/wwalker/ssh-find-agent, see this blog post http://blog.joncairns.com/2013/12/understanding-ssh-agent-and-ssh-add/

**Comment by dopey** [comment]
If there's no further updates on this issue we'll go ahead and close it. But @ShotgunSpider if you're still running into issues feel free to reopen and comment, or hop in our [Gitter](https://gitter.im/smallstep/community) for real time help.
