### ISSUE TITLE
`step certificate create` profile documentation mismatch

### ISSUE THREAD

**Issue by grawity** [smallstep/cli#174]
It might be that I'm severely misunderstanding how path length constraints work, but:

### Subject of the issue

The documentation of `step certificate create` says this regarding profiles:

> `intermediate-ca` Generate a certificate that can be used to sign additional leaf or intermediate certificates.

However, the profile always generates certs with a path length constraint of 0, which (as I understand it) only allows the intermediate to issue leaf certs and not any further intermediates.

(Similarly, CAs generated with the `root-ca` profile have a path length constraint of 1, limiting them to one level of intermediate certs anyway.)

### Your environment

Smallstep CLI/0.13.3 (linux/amd64)

### Steps to reproduce

    step certficate create foo foo.crt foo.key --profile root.ca
    step certificate create bar bar.crt bar.key --profile intermediate-ca --ca foo.crt --ca-key foo.key
    openssl x509 -in bar.crt -noout -text | grep -A1 "Basic Constraints"

### Expected behaviour

Either the pathlen shouldn't be present, or the docs should be updated to remove "...or intermediate".

### Actual behaviour

Pathlen of 0 is present.

**Comment by dopey** [comment]
Hey @grawity, you're definitely right that there is a mismatch in documentation and actual code here. I'll go ahead and update the documentation. 

We do plan on making the MaxPathLen (along with most other attributes) configurable (https://github.com/smallstep/cli/issues/110). It's on our roadmap, but if you'd like to lend support inside that issue, it will definitely help us prioritize. Also, if you have feedback about how we plan on exposing said configurability, we'd definitely love to hear that as well.

In the mean time if you'd still like to use step and are able to build from source, it's pretty simple to change that hardcoded value for [root](https://github.com/smallstep/cli/blob/master/crypto/x509util/rootProfile.go#L49) and [intermediate](https://github.com/smallstep/cli/blob/master/crypto/x509util/intermediateProfile.go#L37) profiles.

**Comment by dopey** [comment]
Documentation updated: cc493a453664484276718a8ab07df924d4e9cd61. Let me know if you think it's ok to close this issue for now (since the one linked above is a more generalized use case.

**Comment by dopey** [comment]
And thanks for pointing this out! Apologies for the confusion.

**Comment by grawity** [comment]
Thanks, good to hear it'll be configurable at some point.
