### ISSUE TITLE
Creating JWS with PS algorithm does not create a valid signature

### ISSUE THREAD

**Issue by MartinKanters** [smallstep/cli#175]
### Subject of the issue
When creating a JWS with a PS algorithm will create a signature which is not regarded as valid by jwt.io or jose4j.

### Your environment
* OS - Ubuntu (WSL) and MacOS
* Version - respectively 10 and Catalina (10.15)
* Step version = CLI/0.11.0-dev (linux/amd64) and Smallstep CLI/0.13.3 (darwin/amd64)

### Steps to reproduce
1. Creating keypair:
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out private-key.pem
openssl rsa -pubout -in private-key.pem -out public-key.pem

2. Creating JWS
step crypto jwt sign --iss my-iss   --kid my-kid   --key private-key.pem   --alg PS256   --jti my-jti   --subtle

Then go to jwt.io and upload your JWS together with the public key from the keypair.

### Expected behaviour
You see the message "Signature Verified"

### Actual behaviour
You see the message "Invalid Signature"

### Additional context
- Doing the same steps with an RS algorithm works fine. 
- [Jose4J](https://bitbucket.org/b_c/jose4j/wiki/Home) also doesn't regard the signature is valid. 
- step crypto jwt verify _does_ regard the signature as valid.

**Comment by maraino** [comment]
Hi @MartinKanters, thanks for finding this, I've found that the root cause was in the version of the go-jose dependency, and was fixed a few months ago 
https://github.com/square/go-jose/commit/467354d5a5957a305c7c9fae4c71259c81bcc1af

We will update the version to get this fixed.

**Comment by maraino** [comment]
That fix is not yet present in the last release of go-jose, I've requested a new release with the fix https://github.com/square/go-jose/issues/266. We'll wait a reasonable time to get a new release, but if go-jose does not produces one we can always fix it using the v2 branch.

**Comment by MartinKanters** [comment]
Hi @maraino, thanks for looking into this!
We'll be waiting for the next version then, we like the tool a lot.

**Comment by maraino** [comment]
Hi @MartinKanters the master branch is now using the new square/go-jose@v2.4.0 that fixes the salt issue in RSA-PSS algorithms. We're not going to do a release yet, but I've created a new release candidate, [v0.14.0-rc.1](https://github.com/smallstep/cli/releases), that includes the fix and some other new features,

**Comment by MartinKanters** [comment]
Hey @maraino, sorry for the late response and thanks for the rc! We would like to recommend our users to use step-cli, but we are waiting for a full release. When are you planning to do the full release?

**Comment by avassem85** [comment]
Ey @maraino, You know when you are going to do a full release?
