### ISSUE TITLE
Set/Unset MaxPathLen for Root-CA via cli

### ISSUE THREAD

**Issue by jkralik** [smallstep/cli#183]
### What would you like to be added
I would like to have option to set MaxPathLen for Root-CA. In my use case i need to unset it.

https://github.com/smallstep/cli/blob/94de6318ae45e0d3d1f769c7728d8eb845bd1b48/crypto/x509util/rootProfile.go#L49

### Why this is needed
It is needed for OCF: https://openconnectivity.org/specs/OCF_Security_Specification.pdf - line 2511.

**Comment by dopey** [comment]
Hey @jkralik, thanks for opening up the issue. We have an existing issue (#110) that is similar in nature, but broader in scope - ability to set all the attributes inside a certificate. 

Our preferred way to address this would be to use the template method described in that issue. However, that solution is probably a few months out, given current planning cycles.

Is that setting preventing you from using `step`? If so, are you able to build `step` locally from source (should be pretty easy if you have `go` and `make` installed). If you're unable to build locally and are blocked by this feature then we'd be happy to build a version for you.

**Comment by jkralik** [comment]
For now we are creating root certificate via own utility and then import it via `step ca init --root <path> --key <path>`.
