### ISSUE TITLE
Add support for OAuth 2.0 PKCE

### ISSUE THREAD

**Issue by maraino** [smallstep/cli#187]
## Description
Add support for OAuth 2.0 Proof Key for Code Exchange (PKCE) 
https://tools.ietf.org/html/rfc7636

We can also add support for it in https://github.com/smallstep/certificates

Notes:
* it's supported at least by Okta.

**Comment by unreality** [comment]
Has this already been completed? I looked into implementing this and found the OAuth client is already generating the required verification code, code verifier (https://github.com/smallstep/cli/blob/b30347b800addab0d04d5bd782570bbe6b6060f0/command/oauth/cmd.go#L892) etc and sending them to the OpenID endpoint? (https://github.com/smallstep/cli/blob/b30347b800addab0d04d5bd782570bbe6b6060f0/command/oauth/cmd.go#L917)

**Comment by mmalone** [comment]
Lol, yea. Looks like it. Thanks! I'm gonna close this.
