### ISSUE TITLE
Add support for RHEL/CentOS

### ISSUE THREAD

**Issue by ghost** [smallstep/cli#190]
### What would you like to be added

Please add support for RHEL/CentOS. Ideally, it would be great to update the documentation to include instructions for CentOS 7/8 and to also generate RPM packages.

Instead of creating and maintaining your own RPM repository, you may submit your packages to the EPEL repository.

### Why this is needed

RHEL is a major server Linux distro by RedHat and CentOS is a community-driven distro based on RHEL.

By generating RHEL/CentOS rpm packages, _step_ becomes available to millions of systems.

Thank you.

**Comment by dopey** [comment]
Hey @robo2bobo, thanks for opening an issue / feature request! We've actually gotten this request a couple of times from our [gitter community](https://gitter.im/smallstep/community) as well, so there's definitely a need for it. 

The last few months for us have been heads-down working towards a release. Once that release is ready to go we'll definitely prioritize making a RHEL build. 

Having said that, if you (or anyone with experience) have any guidance on CI/CD for submitting packages to the EPEL repository, we'd definitely be interested to see or hear about examples. The team doesn't have much experience with RHEL/CentOS which is the only reason we hadn't prioritized a package before. 

We had a request for an ArchLinux package (which we also have little to no experience with) and luckily one of the maintainers was able to help us cobble a package together.

**Comment by robo2bobo** [comment]
Unfortunately I have no experience with rpm packages, but you could ask in the #epel irc channel in freenode for more details, I'm sure they have helped many people with how to create rpm packages.

**Comment by robo2bobo** [comment]
no interest, closing

**Comment by dopey** [comment]
Hey @robo2bobo we're still planning on doing this - probably in the near term. Sorry for the radio silence, but we've been heads down working on product stuff towards an upcoming release that focuses on ssh usability. Once that's released, making the `cli` and `ca` easily accessible on different operating systems is on our short list.

Would you mind if I reopen, just in case other folks are searching for the same thing?

**Comment by mkkeffeler** [comment]
Can confirm this is very much needed!

**Comment by maraino** [comment]
Reopening this issue, as this is something we plan to do.

**Comment by sourishkrout** [comment]
Related to https://github.com/smallstep/cli/issues/163.

**Comment by rabin-io** [comment]
If anyone need rpm packages for step-cli or step-ca I currently package them manually from the release binaries, 
you can find them here: 

- https://build.opensuse.org/package/show/home:rabin-io/step-cli
- https://build.opensuse.org/package/show/home:rabin-io/step-ca

**Comment by elyscape** [comment]
@dopey @maraino Since you use GoReleaser to build the project, you could use [its nFPM integration](https://goreleaser.com/customization/nfpm/) to build RPMs.

**Comment by maraino** [comment]
@elyscape that looks helpful. @tashian did you do the goreleaser integration?

**Comment by tashian** [comment]
I'm taking a look at this option in goreleaser

**Comment by tashian** [comment]
Hi everyone,

With #587 merged, GoReleaser is now building an RPM for CLI releases.
step CLI v0.18.1 will ship with an rpm package!
We'd love your feedback on it.

Thanks @elyscape for your help with our nFPM configuration.
We also have an open issue for [packaging an RPM for `step-ca`](https://github.com/smallstep/certificates/issues/768).

One possible issue: With the `.deb` package, we use Debian Alternatives to create the `step` command, as a symlink to the binary, which is called `step-cli`. This is because there's a statistics package that also has a `step` command. I'm not sure how to handle this sort of ambiguity in the `.rpm` package.

**Comment by elyscape** [comment]
> I'm not sure how to handle this sort of ambiguity in the `.rpm` package.

RPM-based distros also have the alternates system. I'll look into contributing a PR sometime this week.
