### ISSUE TITLE
Review utility of internal `assert` testing package and discuss alternatives

### ISSUE THREAD

**Issue by dopey** [smallstep/cli#21]
We have our own internal testing package for verifying assertions (called `assert`). I believe this package was created to address deficiencies (missing functions, e.g. `FatalError()`, `Fatal()`) in more popular libraries. I have reviewed the current state of the `require` package and it seems to have the functionality that we wanted. 

Switching to `require` (or a similar package) will give us access to a many more features that our implementation does not have. A more popular package will also make it much easier and straightforward for new contributors to grok existing tests and write new ones.

@maraino we discussed this a while ago, so interested in hearing your opinion on two questions:
1) Is `require` a superset of `assert`? Would it be a full substitute, and offer more features on top, or would we be missing certain features that we already have?
2) Is `require` the most appealing alternative?

**Comment by maraino** [comment]
We can use both. 

In my opinion, testify is overcomplicated, `smallstep/assert` tries to be a small assert package with just enough methods, right now it has 14, the only one not really required would be the `HasPrefix`, as it can be achieved using the standard package in a simple way.

`testify/assert` has 90+, and that's only counting the top functions. They even have methods that I haven't found any difference when I tried to use them, Equal and Exactly, the documentation suggests they are different, and the second one checks the type too. But the only difference I've been able to find is the error message. And that's without talking about the verbosity of the errors, I need 4 lines to know that 1 != 2. It might be helpful in some cases but not in most.
