### ISSUE TITLE
Ability to specify certificate expiry when signing requests

### ISSUE THREAD

**Issue by willanta** [smallstep/cli#213]
It would be useful to be able to specify an expiry when signing a certificate request. It seems to pick the default 24 hours.

Ideally everything has short lived certificates but in the real world a huge amount of devices do not support renewal. I have create a second intermediate for these legacy longer expiry certs but there doesn't seem to be a way of changing the expiry when signing.

**Comment by mmalone** [comment]
Both `step ca certificate` and `step certificate create` take a `-not-after` flag that accepts a date or a duration (e.g., `2160h` for 90 days). Is that what you’re looking for?

If you’re using the `step ca` command group you’ll also need to set the `maxTLSCertDuration` property in `~/.step/config/ca.json` to something long enough for your needs. You can also set the `defaultTLSCertDuration` to change the default from 24h to something else. (You can actually set both of these per-provisioner.) Remember to restart (or `HUP`) the CA after changing the config. There’s more info on this in the [CA config docs](https://smallstep.com/docs/certificates/configuration/).

**Comment by willanta** [comment]
No. I am generating a certificate using step certificate sign.

**Comment by mmalone** [comment]
Ah, in that case I believe we just use whatever the requested validity period is in the CSR. If that’s not the case I think that’s a bug. How are you creating the CSR?

**Comment by willanta** [comment]
So a little context first. I am testing replacing an internal CA and I need to support longish lived certs for legacy devices and short lived certs for newer things. Unfortunately each new device I try and generate certs for presents a new set of problems, mainly due to poor implementations on the device side. Most of the devices (Cisco, Dell) that I am generating CSRs from do not let me specify a validity period, just CN,O,OU etc.

I guess I could change the default durations, generate the certs I need then change back.

**Comment by mmalone** [comment]
That sounds frustrating. I _think_ `defaultTLSCertDuration` would work for you if you were using `step-ca` and the `step ca` command group. If the CSR just doesn’t have an expiry it should get the default. But that won’t work with `step certificate sign`, as that command group is designed for more ad-hoc use and doesn’t look at the `ca.json` config.

You could try running `step-ca`. If you really don’t want an online CA you can run `step ca init`, set the `defaultTLSCertDuration`, then run `step ca sign` with the `-offline` flag.

I’m gonna leave this open since, having heard your use case, it seems like we should add a flag to `step certificate sign` to set the expiry if it’s not in the CSR (or maybe even override it if it is).

**Comment by mmalone** [comment]
Out of curiosity, are the devices you're testing networking devices? Do you know if they speak SCEP or some other protocol for automated certificate management? If not, how do you generate the CSRs? Do you have to connect via console and generate one using openssl or something?

We like to collect use cases to help prioritize roadmap. Appreciate any details you're able to provide!

**Comment by willanta** [comment]
Most of the devices with issues are networking (HP/Cisco) and out of band management ranging from brand new to 4 years old. None of them support EC and require RSA. Almost all have a gui or command line interface to generate the CSR. Some of them are getting rejected as they do silly things like not include a SAN so then the CA refuses to sign them. None of them support including the chain (the cert plus the intermediate bundle) in the certificate import which is why I was wanting to use a separate intermediate that would be distributed with the root to end users.

**Comment by willanta** [comment]
Also no, none of them do automated cert management.

**Comment by mmalone** [comment]
Ah. Wow. Lots of constraints there. That context is super helpful, thanks.

Have you opened an issue about the issue with intermediates? I found this one, which seems close: https://github.com/smallstep/cli/issues/207. Would that do what you need?

Have you been able to work around the SAN issue? If we're currently _requiring_ a SAN we may want to reconsider in light of this issue.

**Comment by willanta** [comment]
I was thinking of opening up another issue to do with creating another intermediate but haven't got around to it yet.

I have not been able to get around the SAN issue. At the moment I am thinking it's only legacy stuff that is affected and I should see it less and less over time. I am in two minds about whether to open an issue - I like the fact that standards are being enforced but then again I have the luxury that I only have a handful of devices affected.

**Comment by mmalone** [comment]
Gotcha.

I also have mixed feelings about stuff like SANs being required: while they are "standard", the standards they're part of are specifically related to Web PKI in web browsers. For internal use cases those standards aren't as relevant. Particularly when you control both the client & server and really just need something that works within the constraints of your particular environment. I'm sympathetic.

Anyways, thanks for the feedback and definitely keep us in the loop if any of these things become more serious blockers!

**Comment by shawjo** [comment]
I also have the same issue with the OP in that I have some devices that I can't get to auto-renew, as such, I need the ability to sign a csr with a longer time.  I am using step certificate sign.

**Comment by rabin-io** [comment]
Like to add my +1 here,  for now I overcome this problem with openssl command,

```shell
openssl x509 -req -sha256 \
  -CA "$(step path)/certs/intermediate_ca.crt" \
  -CAkey "$(step path)/secrets/intermediate_ca_key" \
  -CAcreateserial \
  -days 360 \
  -in dev1.csr \
  -out dev1.crt 
```

**Comment by mkkeffeler** [comment]
we also are running into this issue with our legacy clients not having SANS come in attached to the CSR already, the not after issue looks to be resolved based on this example from the step ca sign --help command

      Sign a new certificate with a 1h validity:

          $ TOKEN=$(step ca token internal.example.com)
          $ step ca sign --token $TOKEN --not-after=1h internal.csr internal.crt


But requiring that SAN without a way to retroactively add it at least after a CSR was made (or by force when signing, if we want to enforce it) is very much a hinderance in legacy settings

**Comment by dopey** [comment]
I _believe_ this issue has been addressed. I can now run `step certificate sign --not-after ...` and I can add SANs to an existing CSR by using certificate templates. If there's some functionality that's still missing please let me know and I'll reopen. Or open up a new issue for that specific piece.
