### ISSUE TITLE
From line 270 in add.go the docu doesn't render correctly

### ISSUE THREAD

**Issue by thomic** [smallstep/cli#218]
### Subject of the issue
Documentation which can be found here:

https://smallstep.com/docs/cli/ca/provisioner/add/

does not render correctly from Line 270 in add.go of provisioner

https://github.com/smallstep/cli/blob/e050b985e0b2f5766c8674c2ff0a433515f73ba0/command/ca/provisioner/add.go#L270

No clue why, as this seems to be the correct syntax here.

**Comment by dopey** [comment]
I think this is fixed? Not entirely sure though. If you're still seeing the issue please re-open.
