### ISSUE TITLE
step ca certificate: --http-listen option doesn't seem to work.

### ISSUE THREAD

**Issue by AlastairGrowcott** [smallstep/cli#225]
I am using step-ca for the first time after certbot gave up the ghost (or at least boulder did) and I cannot get certbot to work with step-ca (a guide on that would be great).

I am running a service in a docker image. The service only exposes HTTPS on port 443 and step-ca only seems to use HTTP challenges so I got docker to forward port 8888. My command to obtain a certificate within the docker container is:

step ca certificate phabricator.dynautics.local srv.crt srv.key --kty=RSA --standalone --http-listen=:8888

The step-ca server I have running reports:

INFO[1809]                                               duration=24.817069ms duration-ns=24817069 fields.time="2020-03-03T10:39:29Z" method=POST name=ca nonce=QjMzVzRydjg2VlYxWEo5ZmNtMUUyTnZiaEh4bUtIaUE path=/acme/acme-smallstep/challenge/Pxr7pnpsiIWpYT5dsAWH7rbrEXLlMzR0 protocol=HTTP/2.0 referer= remote-address=192.168.0.35 request-id=bpf37oa57rt95e3n5vd0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"S2hSqDZ5juguMuTFstjTq2w31hdouRIc\",\"url\":\"https://ca.dynautics.local/acme/acme-smallstep/challenge/Pxr7pnpsiIWpYT5dsAWH7rbrEXLlMzR0\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"error doing http GET for url **http://phabricator.dynautics.local/**.well-known/acme-challenge/S2hSqDZ5juguMuTFstjTq2w31hdouRIc: Get http://phabricator.dynautics.local/.well-known/acme-challenge/S2hSqDZ5juguMuTFstjTq2w31hdouRIc: dial tcp **192.168.0.35:80**: connect: connection refused\"}}" size=526 status=200 user-agent=Go-http-client/2.0 user-id=

The challenge is still going to port 80, not 8888. My docker host is using port 80, so I cannot use that.

With certbot, certbot would specify the URL for the challenge to the server, including the port number. It could also piggyback on the Apache config and supported HTTPS challenges. If there was a decent ACME server that worked with certbot I would be so happy.

**Comment by mmalone** [comment]
Hrm. Can you link to any docs / issues / code / anything with more info on Boulder supporting HTTP challenge on a port other than 80? In [section 8.3 of the ACME spec](https://tools.ietf.org/html/rfc8555#section-8.3) it says that, for the HTTP challenge, the validation request "MUST be sent to TCP port 80 on the HTTP server."

To clarify, `step` only supports the HTTP challenge but `step-ca` supports HTTP and DNS. We've also [accepted a PR](https://github.com/smallstep/certificates/pull/180) that adds ALPN challenge support to `step-ca`, which will be in the next release (coming very soon). So you should be able to use `certbot` (or some other ACME client) to get a cert using the DNS challenge (and using the ALPN challenge, with the next release).

Also, there are some instructions on using `certbot` and a bunch of other ACME clients with `step-ca` in the release blog post [here](https://smallstep.com/blog/private-acme-server/#certbot-uploads-acme-certbot-png-certbot-example).

I hope this helps! If you have any other feedback or follow-up questions please let us know!

**Comment by AlastairGrowcott** [comment]
You're right. I was a bit confused as I was specifying a non-standard port in the certbot command line for the CA server. Certbot was actually working using HTTPS. On my VM webserver port 80 is closed as I am only using HTTPS. So I guess the problem is that `step-ca` doesn't support HTTPS challenges.

I think that the ACME spec is lacking here though because a lot of webservers do run on non-standard ports, especially when using one server to host multiple web services and using Apache with virtual hosts on different ports. And especially there is a problem if you have a server with multiple web services in different docker containers. With LetsEncrypt aimed mainly at public web services which almost all use port 80 the ACME spec makes a bit more sense, but for internal CAs serving to webservers on a corporate LAN supporting alternative ports becomes more necessary.

It might be worth adding as an additional feature in `step-ca`.

**Comment by mmalone** [comment]
Yea, this is good feedback. I'm not convinced yet, but if this keeps coming up we'll look into it further. My guess is that the HTTP challenge is restricted to port 80 in the spec for security reasons. As it is, anyone who can run a process that listens on port 80 can get a certificate for any hostname that resolves to a particular machine. It's easy enough to restrict who can run stuff on port 80, but much harder to lock things down if the challenge made a request to an arbitrary port.

Still, you make a good point: for internal stuff it's common to run on non-standard ports. I'm sure we'll run into this again. Instead of an arbitrary port, we could have some CA-side setting to check a different port. But I think the right answer is probably to use a different challenge. For now we have DNS. The ALPN challenge will be released soon, which I think is what you mean by "HTTPS challenge".

**Comment by AlastairGrowcott** [comment]
I just found the certbot option I was talking about originally:

--tls-sni-01-port <port number>

**Comment by mmalone** [comment]
Ah, that appears to be for the SNI challenge which, unfortunately, [is deprecated](https://community.letsencrypt.org/t/march-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209) due to security concerns. The [ALPN challenge](https://tools.ietf.org/html/rfc8737) that I mentioned above is coming to `step-ca` in the next release is a good replacement for most use cases. However, the ALPN spec says that the challenge "MUST use TCP port 443".

Can you use the DNS challenge? If you can't listen on port 80 or 443 that's probably your best bet.

**Comment by AlastairGrowcott** [comment]
In this particular use case, I can't use port 80 but 443 would be fine, so ALPN will be good when it arrives.

I am also finding that I need to stop my Apache web server while setting up the certificate. As per another issue raised for step-cli, the renew command doesn't work for me so I have to do a whole new challenge which means I need to stop anything else listening on port 80. I do this with cron in the middle of the night so it isn't really a big issue, but a bigger more international company might find that an issue. Using a different port to the main webserver port (or integrating better with Apache as certbot did) would be a good improvement to allow the web server to continue operating while sorting out a new certificate.

This is definitely the wrong place to say this, but I am really impressed by step-ca. Boulder from LetsEncrypt was painful to install and use and required numerous bug fixes which were hard to make as I am unfamiliar with the design and the language it is written in. Also, one day it simply stopped working for no apparent reason. I had made no changes that I am aware of. By contrast the step-ca server is easy to obtain and install (making the package automatically set up a service on Linux would be awesome), and the client is easy to use too. It is properly maintained as a production tool whereas Boulder was only intended as a test tool. I am really happy you guys came along.
