### ISSUE TITLE
'step ssh revoke' appears not to work

### ISSUE THREAD

**Issue by TopherIsSwell** [smallstep/cli#233]
### Subject of the issue
I can't revoke ssh certificates using ```step ssh revoke```, I have to use ```step ca revoke```.

### Your environment
* OS - Centos 7.7 and/or Alpine:latest
* Version - 0.14.0 RC3

### Steps to reproduce
With a working step-ca set up with an SSH CA, and on a bootstrapped step client with ssh-agent running, try the following:
provision an SSH certificate:
```bash
step ssh login my-user-name```
verify this works
```ssh my-user-name@someserver```
Get the certificate serial:
```bash
step ssh list --raw my-user-name | step ssh inspect```
Revoke the certificate (might be easier to just type in the serial number: this won't work on Mac):
```bash
step ssh revoke $(step ssh list --raw my-user-name | step ssh inspect | grep -Po '(?<=Serial: )\d+')```
See if the certificate still works (for me this still works):
```ssh my-user-name@someserver```
Revoke the cert using the ca command:
```bash
step ca revoke $(step ssh list --raw my-user-name | step ssh inspect | grep -Po '(?<=Serial: )\d+')```
test if the certificate still works (for me, it no longer works):
```ssh my-user-name@someserver```

### Expected behaviour
The ```step ssh revoke``` should behave the same as the ```step ca revoke``` command but for ssh certificates. Alternatively, perhaps there shouldn't be a ```step ssh revoke``` command and we should always relegate to the ```ca``` command for revocation.

### Actual behaviour
```step ssh revoke``` gives positive feedback (seemingly regardless of what you put in for the serial, but does not revoke the certificate. ```step ca revoke``` must be used, and that works as expected.

### Additional context
I'm not sure if this is a bug in the command line or in the step-ca certificates server, but since the revocation API does appear to be working, I'm assuming this is an issue with the CLI.

**Comment by dopey** [comment]
Hey @TopherIsSwell, thanks for opening the issue!

Ok, so first off our "revocation" for both x509 and SSH certificates is only passive. Which means that we prevent you from renew-ing the certificate but we don't do anything else to actively prevent you from using the certificate. The certificate stops being valid for for auth purposes when it expires.

So, the fact that `step ssh revoke <your-cert>` doesn't do anything makes sense. It wouldn't have any effect. `step-ca` prevents you from renewing SSH user certificates anyway, so you would never be able to renew that cert. 

Now, as to why revoke-ing an SSH cert through `step ca revoke` would have any effect, I'm at a bit of a loss. Will do some sleuthing.

**Comment by TopherIsSwell** [comment]
Hm. I'm unable to reproduce the behavior of ```step ca revoke```, perhaps when I was testing, the certificate expired and I thought it was the ca revocation that did it. If this is the expected behavior then I'll close this issue. 

Thank you for your help.

**Comment by dopey** [comment]
@TopherIsSwell No worries. Still glad to have the issue because it may help someone else with a similar question.

I believe this is the expected behavior, but it needs to be documented better. We're working on that  bit :)
