### ISSUE TITLE
Step CLI breaks on URLs with trailing slashes

### ISSUE THREAD

**Issue by froztbyte** [smallstep/cli#245]
### Subject of the issue

```
% step certificate inspect https://google.com/
failed to connect: dial tcp: lookup google.com/: no such host
```

### Your environment

```
% step version
Smallstep CLI/0.13.3 (darwin/amd64)
Release Date: 2019-10-02 18:36 UTC
```

### Steps to reproduce

```
% step certificate inspect https://google.com/
failed to connect: dial tcp: lookup google.com/: no such host
```

### Expected behaviour

URLs with a trailing slash (or perhaps even "whole URL"?) should be supported as input.

If not that, perhaps the error returned should more accurately reflect the failure mode?

### Actual behaviour

An incorrect error is returned, describing a name lookup failure

**Comment by dopey** [comment]
Thanks for the bug report! I've put this in the backlog for now. It should be a quick fix so I imagine we'll be able to slot it in during one of the next sprints.
