### ISSUE TITLE
Unable to start step-ca on RPi 3 (ARM7)

### ISSUE THREAD

**Issue by LookoutHill** [smallstep/cli#256]
### Subject of the issue
When I run "step-ca /root/.step/config/ca.json" I receive this error:

Error opening database of Type badger with source /root/.step/db: error opening Badger database: Unable to mmap RDWR log file: invalid argument

### Your environment
Raspberry Pi 3 Model B
Linux hostname 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux
step-certificates 0.14.2

### Steps to reproduce

Following the getting started guide at: https://smallstep.com/docs/getting-started/
1. Run "step ca init" and fill in requested values.
2. Run "step-ca /root/.step/config/ca.json".

### Expected behaviour

I expected the step-certificates server to start.

### Actual behaviour

The following error is printed and the server is not started:

Error opening database of Type badger with source /root/.step/db: error opening Badger database: Unable to mmap RDWR log file: invalid argument

### Additional context
N/A

**Comment by LookoutHill** [comment]
I was hoping to use the default db, but since it works fine with MariaDB I'm going to go with this.

**Comment by dopey** [comment]
Hey, thanks for opening an issue! I _think_ this may be related to an existing issue (https://github.com/smallstep/certificates/issues/156). Basically badgerV1 not working on certain operating systems. 

Near the bottom of that issue I posted about a release candidate specifically built with badgerV2. If you're able to try that, let me know how it goes. You will need to completely delete your `$(step path)/db` directory first. So that there are no remnants of the previous DB.

**Comment by LookoutHill** [comment]
@dopey I installed the 0.14.3-rc.1.badger2 version, deleted the entire folder /root/.step, and reran step ca init, but this didn't fix my issue, however the error message is different now:

badger 2020/04/13 22:03:37 INFO: All 0 tables opened in 0s
Error opening database of Type badger with source /root/.step/db: error opening database: error opening Badger
 database: During db.vlog.open: Error while creating log file in valueLog.open: Mmap value log file. Path=/roo
t/.step/db/000000.vlog. Error=cannot allocate memory

**Comment by LookoutHill** [comment]
Looks like this could be related to, https://github.com/smallstep/certificates/issues/211, but I'm running on a Raspberry Pi 3 not a 4.

**Comment by dopey** [comment]
@LookoutHill Yep, I think it's related. 

Are you able to build the certificates executable yourself? If so, there's branch of certificates called `max/32bitTest` that should work for you. Otherwise, I can create a release candidate for you to try out. Lmk.

**Comment by LookoutHill** [comment]
@dopey I'm receiving this error while trying to build:

go: github.com/smallstep/cli@v0.14.0-rc.1.0.20200127233252-e55637e57819: unknown revision e55637e57819
go: error loading module requirements
make: *** [Makefile:59: download] Error 1

**Comment by dopey** [comment]
I just updated that branch. Would you mind trying once more. Sorry 😬

**Comment by LookoutHill** [comment]
Go is NOT endearing itself to me. The build process is very opaque. The source file, https://github.com/smallstep/certificates/blob/max/32bitTest/kms/softkms/softkms.go, is importing "crypto/ed25519" instead of "golang.org/x/crypto/ed25519". I adjusted this file on my local filesystem, but running make gives me the same error. WTH?!? It's not like go is reverting my change, just ignoring it. =(

**Comment by dopey** [comment]
What version of golang are you on? I'm using 1.14.2 locally, and travis is using 1.13.X, both of which seem to be working.

**Comment by LookoutHill** [comment]
1.11.6 I've forked and I'm trying to commit to my fork in case go is pulling stuff from github. The lack of precise compiler output sucks. Do you know a way to tell "go build", "Tell me everything, dammit."

**Comment by LookoutHill** [comment]
I guess I'm getting an education tonight.

**Comment by dopey** [comment]
I made a release so we can hopefully get past the build errors: https://github.com/smallstep/certificates/releases.
Not sure which of those package options will suit you best.

**Comment by LookoutHill** [comment]
Thanks 0.14.3-rc.2.32bitbadger2 is working.

**Comment by dopey** [comment]
woooooooo! Nice. Don't quote me on this 100% but we should be able to get these changes into the v0.15.0 release. I'll leave the issue open until we've got the changes in master.

**Comment by dopey** [comment]
Just merged code to the certificates repo that should fix this issue. If you build from source (and [properly configure](https://github.com/smallstep/certificates/blob/master/docs/database.md#badger) your db in the ca.json), this should now work out of the box.

**Comment by maraino** [comment]
@LookoutHill With the version `master` I can run in a raspberry pi 3 using the following db config in the ca.json

```json
   "db": {
      "type": "badgerV2",
      "dataSource": "/home/pi/.step/db",
      "badgerFileLoadingMode": "fileio"
   }
```
