### ISSUE TITLE
Encode additional info in Subject

### ISSUE THREAD

**Issue by daenney** [smallstep/cli#258]
In many cases, the subject is not only supposed to contain a CommonName, but also other information. For example, if you'd like to use step to maintain an external CA for a Kubernetes cluster, you need to generate certs with `O=systems:master` [among other things](https://kubernetes.io/docs/setup/best-practices/certificates/).

It seems I can just do `step certificate create "some-name O=systems:master" ...` but I have no idea if that's supposed to work like that. The OpenSSL approach to it is `-subj /CN=/O=` etc.

**Comment by dopey** [comment]
@maraino is this done now that we have templates?

**Comment by maraino** [comment]
As long as the subject fields are standard this can be done in certificate templates, for example here one that uses the default subject country but a fixed organization and no common name

```
{
	"subject": {
             "country": "{{ .Subject.country}}",
             "organization": "systems:master"
         },
	"sans": {{ toJson .SANs }},
{{- if typeIs "*rsa.PublicKey" .Insecure.CR.PublicKey }}
	"keyUsage": ["keyEncipherment", "digitalSignature"],
{{- else }}
	"keyUsage": ["digitalSignature"],
{{- end }}
	"extKeyUsage": ["serverAuth", "clientAuth"]
}
```
