### ISSUE TITLE
go.mod: verifying module: checksum mismatch

### ISSUE THREAD

**Issue by skyjia** [smallstep/cli#261]
### Subject of the issue
I failed to import `github.com/smallstep/cli` v0.14.2 in my project with go modules enabled. It reports an error as below:

```sh
github.com/jinmukeji/plat-pkg/v2/auth/jwt imports
	github.com/smallstep/cli/crypto/pemutil: github.com/smallstep/cli@v0.14.2: verifying module: checksum mismatch
	downloaded: h1:W7+mWO/0sKIKzHEO8m+9Ye8eMzlzyISshBpFnvR+CmI=
	sum.golang.org: h1:0Z1MtcgJfVS9RstNokWSNqE20xPwdiEhZgNuZxYRWRI=
```

However, if it's downgraded to v0.13.3, such error is gone.

### Your environment
* OS - macOS
* Version - 10.15.4

Please advise.

**Comment by truatpasteurdotfr** [comment]
same here but on linux CentOS-7 with the git  version and the latest released one:
```
verifying github.com/smallstep/certificates@v0.14.2: checksum mismatch
	downloaded: h1:i7zkpP+UEv+ivTaB2Wzk1AnJU/xP9RIH80FGRZ5eF3g=
	go.sum:     h1:EEGmyHNawWIw+QFMztFxegSa6NMnInhC/dRfpz38n6o=
```

**Comment by dopey** [comment]
What `go` version are y'all on? I'm at:

```
go version go1.14.2 darwin/amd64
```

No issues on MacOS 10.15.3.

**Comment by truatpasteurdotfr** [comment]
[tru@elitebook840g3 ~]$ go version
go version go1.13.6 linux/amd64
[tru@elitebook840g3 ~]$ type go
go is hashed (/usr/bin/go)
[tru@elitebook840g3 ~]$ rpm -qf /usr/bin/go
golang-bin-1.13.6-1.el7.x86_64

That is the OS provided go version.

**Comment by truatpasteurdotfr** [comment]
I have side installed go/1.13.10.linux-amd64 and go/1.14.2.linux-amd64, the checksum error is no longer occuring with either newer version that the default 1.13.6 version.

**Comment by maraino** [comment]
@skyjia I've tried a couple of Go versions and in both I get the following entries in a go.sum:
```sh
github.com/smallstep/cli v0.14.2 h1:0Z1MtcgJfVS9RstNokWSNqE20xPwdiEhZgNuZxYRWRI=
github.com/smallstep/cli v0.14.2/go.mod h1:JOTzEzQ4/l863KUqs9qlAqPagWPOqu6lc3C59S1nYzU=
```

`go mod verify` succeeds and shows `all modules verified`. And the above sums match the entries that sum.golang.org provides:
```
$ curl https://sum.golang.org/lookup/github.com/smallstep/cli@v0.14.2
1076780
github.com/smallstep/cli v0.14.2 h1:0Z1MtcgJfVS9RstNokWSNqE20xPwdiEhZgNuZxYRWRI=
github.com/smallstep/cli v0.14.2/go.mod h1:JOTzEzQ4/l863KUqs9qlAqPagWPOqu6lc3C59S1nYzU=

go.sum database tree
1124804
H47dN2EP6uTYpEG0yy59fPO9V3RZNG1AqBB4hknSnJo=

— sum.golang.org Az3grlkrZhWh+i6xTUvj/DWnpzxsoPG4UrZBS7R5ntGYdCHX5HV6hR8Kb4uAIa+48JRuGyjFzwImY63oA+kxc7r0Iwk=
```

You can try to delete the cached files in `$GOPATH/pkg`, if you do not have a GOPATH defined you can get the default one running `go env | grep GOPATH`.

**Comment by maraino** [comment]
This problem was caused because the release was tagged twice. The best solution would be to import a newer version, that does not have this problem. 

The problem appears specially if `GOPROXY=direct`, using the default proxy you are generally able to download the depndency, the go code is actually the same, because only the Makefile changed between the re-tags.

**Comment by dopey** [comment]
I'm going to close this issue, but feel free to re-open if it's still not working for you.

**Comment by deepaksinghvi** [comment]
Faced the same issue and following was helpful:

1. Remove the entries from go.mod and go.sum manually for the package, 
2. go get -u <your versioned package or library name>
3. go mod vendor

And you are good to go.

**Comment by cihanmehmet** [comment]
go clean -modcache
rm go.sum
go mod tidy
go get -u
