### ISSUE TITLE
Creating certs with root-ca and intermediate-ca profiles includes DNS SAN extension

### ISSUE THREAD

**Issue by solidgoldbomb** [smallstep/cli#263]
### Subject of the issue
When creating a Root CA or Intermediate CA certificate using `step certificate create`, the resulting certificate always includes the cert CN in a SAN extension.  CA certs probably shouldn't have SAN extensions at all and many CNs are invalid DNS SANs.

This behaviour also produces a different certificate structure than the one you get by using `step ca init`.

### Your environment
* OS - Ubuntu 18.04
* Version - step 0.14.2

### Steps to reproduce
```
$ step certificate create --profile root-ca "Example Inc. Root CA" root-ca.crt root-ca.key
Please enter the password to encrypt the private key: 
Your certificate has been saved in root-ca.crt.
Your private key has been saved in root-ca.key.

$ step certificate inspect ./root-ca.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 58419960625675612273431578323333713204 (0x2bf346705ab61c61a1292d8072348d34)
    Signature Algorithm: ECDSA-SHA256
        Issuer: CN=Example Inc. Root CA
        Validity
            Not Before: Apr 20 14:48:39 2020 UTC
            Not After : Apr 18 14:48:39 2030 UTC
        Subject: CN=Example Inc. Root CA
        Subject Public Key Info:
            Public Key Algorithm: ECDSA
                Public-Key: (256 bit)
                X:
                    14:37:1e:0f:46:61:88:b5:54:49:b5:eb:33:5d:d5:
                    09:e4:ac:e9:7d:d6:bf:27:63:7b:97:e4:a2:4b:74:
                    fa:46
                Y:
                    9f:0c:0d:7e:72:99:3b:85:f7:09:d8:3b:9d:fd:97:
                    e5:20:5f:9e:af:1a:3b:82:b0:a2:d9:56:0e:70:ff:
                    75:6b
                Curve: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:1
            X509v3 Subject Key Identifier:
                B1:AF:98:27:78:63:E3:37:67:EC:AA:81:C9:17:45:07:F8:72:3D:B0
            X509v3 Subject Alternative Name:
                DNS:Example Inc. Root CA
    Signature Algorithm: ECDSA-SHA256
         30:46:02:21:00:ed:96:94:b6:6f:45:0d:b9:40:07:38:4a:c8:
         0e:d7:fe:f4:4e:aa:e8:a6:9c:d8:28:3d:4f:2d:39:93:6f:a1:
         c3:02:21:00:96:e1:b7:e5:9b:bd:54:d6:25:9f:b8:1e:1c:47:
         a7:15:2c:55:db:5f:95:e8:bc:52:a8:f2:b2:e5:39:73:68:fd
```

### Expected behaviour
Root CA and Intermediate CA certs should match those produced by `step ca init`.

### Actual behaviour
Root CA and Intermediate CA mistakenly contain SAN extension.

**Comment by solidgoldbomb** [comment]
Looks like the subject is being unconditionally forced into the sans list here: https://github.com/smallstep/cli/blob/master/command/certificate/create.go#L274

Maybe that bit of code needs to be conditional on the type or maybe removed entirely requiring the user to explicitly specify any SANs that they want.

Putting the subject into the SAN if otherwise empty was introduced in a078cb6e67194df.

**Comment by mmalone** [comment]
@solidgoldbomb thanks for doing the diligence on this. You rock.

I believe the intent here was to make the default behavior of this subcommand produce leaf certificates that are compliant with CA/Browser Forum baseline requirements. Baseline requirements say leaf certs must have a SAN (and actually discourages / deprecates use of the common name).

That said, you're right, this only makes sense for leaf certificates (i.e., we should be checking `if (len(sans) == 0) && (prof == "leaf")`). I don't know what the standards say about SANs in roots & intermediates, or how SANs are treated if they exist, but I did a bit of basic diligence and other public Web PKI CAs (specifically checked Let's Encrypt & pki.goog) aren't including SANs in their roots or intermediates.

You've done 90% of the work here, so if you want to submit the PR and officially get credit for this we'd certainly accept it. If you don't wanna do the work though, that's cool, should be a pretty easy fix for us to pick up for next release.

Out of curiosity, did this cause problems for you anywhere, or just an aesthetic / hygiene / best practice thing?

**Comment by solidgoldbomb** [comment]
Sure, I'll try to write up a PR for this.

CA/B BR doesn't seem to comment directly on the issue of including a SAN in a CA certificate but it is certainly invalid to include a malformed `SAN: dnsName:<a subject that isn't a DNS name>`. 

FWIW, there are approximately 36 Trusted Root CAs that include a SAN extension and they don't exactly look like the top tier ones:
 * [Censys Query](https://censys.io/certificates?q=tags%3A+root+and+tags%3A+trusted+and+parsed.extensions.subject_alt_name%3A+*)

Inverting that query shows that there are 388 Trusted Root CAs without SAN.

I stumbled across this issue while exploring what is possible with the step tools and considering the workflow for generating a single root CA and then using that to generate multiple intermediate CAs derived from a common root.  That led me to trying to separate the creation of the root CA rather than just using `step ca init`.  I fully expected to get an equally structured root CA in both cases but noticed the discrepancy in this bug that produces an invalid cert.
