### ISSUE TITLE
STEPDEBUG=1 set in base docker image for CLI

### ISSUE THREAD

**Issue by mmalone** [smallstep/cli#273]
We're setting `STEPDEBUG=1` in our base docker image. I'm not sure if this was intentional, or just left over from development, but it results in verbose stack traces for simple errors like passing the wrong number of positional arguments to subcommands.

The obvious fix is just removing this environment variable. If there are no objections I think we should just do that.

**Comment by maraino** [comment]
It has been there for a long time, ... I think it makes sense to remove it
