### ISSUE TITLE
Add --principals flag to take a comma separated list of principals (step ssh certificate)

### ISSUE THREAD

**Issue by dopey** [smallstep/cli#274]
### What would you like to be added

Add --principals flag to take a comma separated list of principals, rather than passing them individually as `--principal foo --principal bar --principal baz`.

```
step ssh certificate --principals "foo,bar,baz" max@smallstep.com id_ecdsa
```

### Why this is needed

Easier to script.

**Comment by sourishkrout** [comment]
This already works with: `step ssh certificate --principal foo --principal bar --principal baz max@smallstep.com id_ecdsa`.
