### ISSUE TITLE
Allow more url variations in "certificate inspect"

### ISSUE THREAD

**Issue by meanbeanlib** [smallstep/cli#275]
### What would you like to be added
Allow more url variations in "step certificate inspect".
e.g.
```
// this works
step certificate inspect https://www.google.com

// these don't
step certificate inspect https://www.google.com/
step certificate inspect www.google.com:443
step certificate inspect www.google.com
```

### Why this is needed
More convenience

**Comment by sourishkrout** [comment]
Trailing slash should already work: e.g. `step certificate inspect https://www.google.com/`

**Comment by sourishkrout** [comment]
Suggestion: the command could attempt to resolve the "target" as domain when file is non-existent potentially filtered by command TLDs & localhost

**Comment by meanbeanlib** [comment]
> Trailing slash should already work: e.g. `step certificate inspect https://www.google.com/`

Nice. Confirmed with latest 0.14.4 release
