### ISSUE TITLE
generated passwords are lovecraftian nightmares.

### ISSUE THREAD

**Issue by nimbius** [smallstep/cli#283]
Just tried generating a password during provisioner creation and was greeted with this 32 character unholiness:
 unr~A~%[d(`D0JmwaB)}z];fuJ'AN0U;

reasons this is yucky and awful:
- some of these are escape characters.
- some SQL and financial systems barf on certain characters. :(
- makes a lot of assumptions about the sanity of inputs for automated systems :(
- makes developers in a remote console with limited access to a paste buffer cry.

cool idea to make passwords cool and also neat:
- deprecate passwords.
- the awesome dudes at openwall have a library that generates **passphrases** 
- https://www.openwall.com/passwdqc/
- its got go bindings.  yay go! 
- its a library supported by security people from name brands like openbsd

**Comment by sswastik02** [comment]
Hi @hslatman,
Is this issue still valid? If so, I would like to work on it.

**Comment by dopey** [comment]
Hey @sswastik02 👋. Yes, I believe this issue is still valid, and we'd love for someone from the community to take it on!

**Comment by sswastik02** [comment]
Thanks for your reply @dopey 
Could you please give hints where edits would me made? As I am new to this repository.

**Comment by dopey** [comment]
https://github.com/smallstep/cli/blob/master/command/ca/init.go#L655, https://github.com/smallstep/cli-utils/blob/main/ui/ui.go#L217-L231

I think that's where you'd start poking around. You could probably just replace `randutil.ASCII` with `randutil.Alphanumeric`.

If you install `step` and run `step ca init`, fill in the first few prompts you'll see: 

```
Choose a password for your CA keys and first provisioner.
✔ [leave empty and we'll generate one]: █
error reading password: ^C
```

Which I believe is what this issue is about. The default generated password can be quite ugly.

**Comment by hslatman** [comment]
Hey @sswastik02, we'd like the CLI to remain pure Go, so relying on `libpasswdqc` is going to be problematic. If it provides sufficient value it could be put behind a build tag, but it likely won't be supported in the releases we produce.  

There might be alternative solutions providing similar functionality in Go. Those would be preferred. For this issue, changing the generated passwords to something that's more friendly in terminals seems sufficient, so it's not something that necessarily needs to be implemented, imo.

**Comment by sswastik02** [comment]
Hi @hslatman,
Your point is well taken. Would you recommend that I move forward by initiating a pull request in the appropriate repository? This would involve implementing the transition from ASCII to alphanumeric and properly referencing this issue.

**Comment by hslatman** [comment]
@sswastik02 sounds like a great way forward 🙂

**Comment by nimbius** [comment]
perhaps this could be of value?  https://github.com/legionus/go-passwdqc 

Thanks again for working on this :)

**Comment by sswastik02** [comment]
Hi @nimbius,

Thank you for sharing the repository for `passwdqc`. However, as @hslatman pointed out, CLI is preferred to be implemented in pure Go. Unfortunately, `legionus/go-passwdqc` relies on `libpasswdqc`, as indicated [here](https://github.com/legionus/go-passwdqc/blob/53368bdb9014da227dd705747d9f8bf80423b32a/passwdqc.go#L16), and it also uses `cgo`.

**Comment by sswastik02** [comment]
Hi @dopey, @hslatman, @nimbius 
I have opened a PR for this issue, please let me know if any changes are required.
