### ISSUE TITLE
step wont list provisioners, accepts duplicate provisioners.

### ISSUE THREAD

**Issue by nimbius** [smallstep/cli#284]
### Subject of the issue
step ca provisioner list does not display new provisioners created.

### Your environment
* OS - arch
* Version - latest

### Steps to reproduce
```
 step-cli ca provisioner add test@peanutbutter.ninja --create --ssh
 step-cli ca provisioner add test@peanutbutter.ninja --create --ssh
 step-cli ca provisioner add test@peanutbutter.ninja --create --ssh
```

then run 
`
step-cli ca provisioner list
`
only the initial provisioner created during init of the CA is shown.

cat ca.json shows the provisioners _were_ created though.

### Expected behaviour
provisioner should catch duplicates?
names should be unique...for sanity?
and of course, provisioners created should be displayed.

### Actual behaviour
only the initial provisioner at time of ca init is shown.

**Comment by dopey** [comment]
Hey, I think this is probably a documentation issue. Provisioners are not stored in the DB - they are only stored in the `ca.json` file. When you add or remove a provisioner, we modify the `ca.json` but the CA won't pick those changes up until the next "[reload/restart](https://github.com/smallstep/certificates/blob/master/docs/GETTING_STARTED.md#hot-reload)". We should probably add some documentation to the `ca provisioner add|remove` commands.

**Comment by dopey** [comment]
I made a new [issue](https://github.com/smallstep/cli/issues/285) to track the documentation for this. If you have any suggestions on where and when we could have surfaced documentation definitely leave a comment on that issue. (I was thinking it could be part of the output of `step ca provisioner add|remove` 🤷‍♂️)

**Comment by dopey** [comment]
I'm going to close this issue, but feel free to re-open if you feel the question is still unanswered.
