### ISSUE TITLE
otp verify doesn't use provided settings

### ISSUE THREAD

**Issue by periodic1236** [smallstep/cli#294]
### Subject of the issue
`step crypto otp verify` has several flags like `--skew`, `--alg`, and `--time` but they don't do anything. The code only makes use of the provided `--secret` value. That file can also contain a URI like that given by `otp generate --url`, but even if some of these settings like algorithm and length are part of the URI, they are also ignored.

Also, the names of some flags are wrong because of missing commas. Instead of either `--alg` or `--algorithm` being accepted, the command expects to receive `--'alg algorithm'`. Similarly for `--length`/`--digits`.

### Your environment
N/A

### Steps to reproduce
Run `step crypto otp generate --alg SHA256 --length 8 --url ...` and use the result to configure a TOTP authenticator app that properly supports these seldom-used options. Then try to verify a token with `step crypto otp verify --secret <path>`.

### Expected behaviour
Valid token should pass and return "ok"

### Actual behaviour
Result is "fail"

### Additional context
See above

**Comment by maraino** [comment]
Thanks @periodic1236, 🤫 I know who to blame 🤐

**Comment by mmalone** [comment]
I am ashamed.

**Comment by periodic1236** [comment]
Thanks for the fix!

The `otpauth://` URI generated by `otp generate --url` can also contain setup parameters, but you still have to specify them separately when using `otp verify`. If you can support that then this should reach parity with some of the other libraries. Cheers!
