### ISSUE TITLE
Add support for TLS Server Name Indication

### ISSUE THREAD

**Issue by davidnarayan** [smallstep/cli#295]
### What would you like to be added
I would like to be able use TLS Server Name Indication to specify which certificate on the remote host should be sent back to the client.

### Why this is needed
This is very handy in (e.g. development) scenarios where the hostname or DNS may not match the SANs on the certificate that are being used.

A simple workaround to get the certificate is to use the `--insecure` flag, but this option would allow full validation even with different server names.

**Comment by dopey** [comment]
Which commands are you referring to?

**Comment by davidnarayan** [comment]
> Which commands are you referring to?

This would apply to the following commands:
  - `step certificate inspect`
  - `step certificate fingerprint`
  - `step certificate verify`
  - `step certificate lint`

I've submitted a PR for this in #296.

**Comment by dopey** [comment]
Got it. Didn't see the PR, thanks!
