### ISSUE TITLE
"step crypto jwt sign" should provide an option for SAN

### ISSUE THREAD

**Issue by dharanikumar-s** [smallstep/cli#306]
### What would you like to be added
`step crypto jwt sign` should provide an option for adding san extension like `step ca token -san`.

### Why this is needed
It is required if provisioner exist outside ca and san is needed.

**Comment by maraino** [comment]
Hi @dharanikumar-s, we already provide a way to pass custom properties to the JWT payload, you just need to pipe them to `step crypto jwt sign`.

```sh
$ echo '{"sans": ["foo.doe.com", "bar.doe.com"]}' | \
> step crypto jwt sign --key priv.json --iss john@doe.com --aud https://doe.com --sub auth --exp $(date -v+1M +"%s") | \
> step crypto jwt inspect --insecure
Please enter the password to decrypt priv.json:
{
  "header": {
    "alg": "ES256",
    "kid": "Mcw0mGbDGtUe5_6KNQDSLAfB-dUoiWVGr0hQjmxkHvw",
    "typ": "JWT"
  },
  "payload": {
    "aud": "https://doe.com",
    "exp": 1593538812,
    "iat": 1593538754,
    "iss": "john@doe.com",
    "jti": "ae09dea4cda06e352783c5c19bde28de6ab1a3d0cf04c88cbf1321c77f61e643",
    "nbf": 1593538754,
    "sans": [
      "foo.doe.com",
      "bar.doe.com"
    ],
    "sub": "auth"
  },
  "signature": "3Oq5trSqJx6omX9I8xleIhra39q2M7nly1dGExdIu7ivOeisTWlQkJoR2BrzBHF3TV_I9j1kTjVR5iZWhrEJzA"
}
```

But you can also use `step ca token` without talking to the CA at all. One option is to have the ca.json in your environment and use `step ca token --offline`. You can use the flags `--kid` or `--issuer` to select the key you want to use, and `--password-file` with the password used to decrypt the key.

```sh
step ca token --offline --san foo.doe.com --san bar.doe.com --issuer john@doe.com
```

It's also possible to use it without the `ca.json` if you provide the key using `--key`, but you will need to provide the `--kid` and `--issuer` manually:

```sh
step ca token --offline --san foo.doe.com --san bar.doe.com --key priv.json --kid Mcw0mGbDGtUe5_6KNQDSLAfB-dUoiWVGr0hQjmxkHvw --issuer john@doe.com
```

Both options of `step ca token --offline` requires the environment bootstrapped with `step ca bootstrap --ca-url https://doe.com --fingerprint xxx`.

@dharanikumar-s I'm gonna close this issue, but feel free to reopen it if you have any issue.
