### ISSUE TITLE
Docker image for arm64 (raspberry pi).

### ISSUE THREAD

**Issue by blmhemu** [smallstep/cli#308]
### What would you like to be added
Docker image for arm64 (raspberry pi).

### Why this is needed
Supporting more platforms, especially for self hosted community.

**Comment by dopey** [comment]
Just added this. Should be available for all future releases. https://hub.docker.com/layers/smallstep/step-cli/0.14.7-rc.1/images/sha256-a96055c47b6d47d480621ad6a06bb6c9408addd0b54113af5617aa41d90a19cf?context=repo
