### ISSUE TITLE
Consider adding `fingerprint` to the output of `step certificate inspect`.

### ISSUE THREAD

**Issue by dopey** [smallstep/cli#319]
We already have the `step certificate fingerprint command`. The question is whether `fingerprint` would be useful or expected output in the context of `step certificate inspect`.

**Comment by dopey** [comment]
@mmalone do we want this? If not, let's close.

**Comment by mmalone** [comment]
What's the use case? The fingerprint isn't _part of_ the certificate, so it's not immediately obvious that this should be in the output from `inspect`. Unless there's a use case I'm fine with closing this.
