### ISSUE TITLE
Unable to renew SSH host certificate

### ISSUE THREAD

**Issue by tmcolby** [smallstep/cli#322]
### Subject of the issue
Unable to renew SSH host certificate

### Your environment
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)

### Steps to reproduce
```
step ssh certificate amya-iot-server-1 --sign --private-key ssh_host_ecdsa_key --host --principal someserver.mydomain.io ssh_host_ecdsa_key.pub  
[WORKS! - creates the certificate]  

step ssh inspect ssh_host_ecdsa_key-cert.pub 
[WORKS! - shows the certificate]

step ssh renew ssh_host_ecdsa_key-cert.pub ssh_host_ecdsa_key
[FAILS!]  
cannot create a new token: the CA does not have any provisioner configured  

step ca provisioner list  
[WORKS! - shows my two provisioners]
```

### Expected behaviour
should be able to renew the SSH host certificate

### Actual behaviour
get message `cannot create a new token: the CA does not have any provisioner configured `

### Additional context
running v0.14.6 of the cli and the ca

**Comment by dopey** [comment]
Hey @tmcolby, thanks for opening the issue. Hopefully this will be useful for other folks who stumble on this problem and maybe we'll adjust some of our default configuration to make this more smooth as well.

Here is a matrix showing the tasks that each provisioner is able to perform. The only provisioner authorized to renew SSH host certificates is the `SSHPOP` provisioner. I'm guessing you don't have one of these in your `step-ca` config yet (we should probably add one by default - I'll make another issue to track that). Adding an `sshpop` provisioner is easy though:

```
step ca provisioner add <provisioner-name> --type SSHPOP
```

Then restart or SIGHUP your CA and you should be able to renew SSH host certificates. 

Let me know if that works for you.

**Comment by dopey** [comment]
https://github.com/smallstep/certificates/issues/320

**Comment by tmcolby** [comment]
thanks, max, that did the trick.
