### ISSUE TITLE
Releases for win32/amd64 should be in zip format

### ISSUE THREAD

**Issue by joelatrr** [smallstep/cli#329]
### What would you like to be added
Heyo!  Just to make things simpler for folks that are using automation with your product, any way you can change the release artifact to a .zip format instead of a tarball? 
### Why this is needed
It's not *needed* as tar is in newer versions of windows, but it would make for uniform solutions in mixed environments.

**Comment by maraino** [comment]
Makes sense zip is way more common on MS Windows. @dopey

**Comment by dopey** [comment]
Hey @joelatrr, thanks for opening the issue. It's on our short list of "up next" items. Should be a quick addition.

**Comment by joelatrr** [comment]
thanks much, love the work ya'll are doing.
