### ISSUE TITLE
step-cli does not detect WSL 2 correctly

### ISSUE THREAD

**Issue by unreality** [smallstep/cli#332]
The new Windows Subsystem for Linux version 2 (released May 2020) changes the content of `/proc/sys/kernel/osrelease` slightly, eg:

`4.19.104-microsoft-standard`

IsWSL() in exec.go uses case-sensitive matching on 'Microsoft' || 'WSL' so step does not detect WSL 2 correctly.

A fix for line 37 of exec/exec.go:

`	return strings.Contains(strings.ToLower(string(b)), "microsoft") || strings.Contains(strings.ToLower(string(b)), "wsl")`

This works for WSL2, i havent tested for other versions, and there might be a better way to do it, im not a go dev :)

**Comment by maraino** [comment]
@unreality Hi, thanks for noticing this. Can you send us a PR, we will be happy to merge it. I don't use windows, and it will be a little bit harder to test it, I will need to create a vm, ...

**Comment by luckielordie** [comment]
Bit more context to this error for the search engines to pick up.
```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted
```
I've applied the fix provided by @unreality and tested it works with WSL2. I'll open a PR shortly.

**Comment by tommy-56** [comment]
Fix was implemented in latest release with no further problems occurring  when testing WSL

**Comment by strarsis** [comment]
@tommy-56: So does this mean that when smallstep CLI is used in WSL 2, that it will also install the certificate in the Windows host, too? That would be great!

**Comment by Atulsingh92** [comment]
> Fix was implemented in latest release with no further problems occurring when testing WSL

Sorry, what was the solution again??
