### ISSUE TITLE
Other architecture binaries in AUR PKGBUILD

### ISSUE THREAD

**Issue by tonyfinn** [smallstep/cli#342]
### What would you like to be added
You already build aarch64 binaries (and armv7) but the AUR PKGBUILD is x64 only. This means it cannot be installed on Arch Linux ARM.

To do this you can move architecture dependent sources into source_<arch> sections - for example, for step-cli-bin, adding aarch64 support is done by changing:

```bash
source=("https://github.com/smallstep/cli/releases/download/v${pkgver}/step_linux_${pkgver}_amd64.tar.gz"
	"https://github.com/smallstep/cli/raw/v${pkgver}/autocomplete/bash_autocomplete"
	"https://github.com/smallstep/cli/raw/v${pkgver}/autocomplete/zsh_autocomplete")

sha256sums=('4917800ee1cd99ec059dabbf2f40e9ba26ec4b05d70d19e58b526a11e962bde4'
            'add3e078e394e265f6b6a3bf12af81cc7897410ae5e6a0d4ee7714a5b856a7be'
            '3e65c7f99484497e39d20eed3e4ceb4006e8db62dc9987f83a789bb575636e18')
```

Note that the binaries, which

```bash
source=("https://github.com/smallstep/cli/raw/v${pkgver}/autocomplete/bash_autocomplete"
        "https://github.com/smallstep/cli/raw/v${pkgver}/autocomplete/zsh_autocomplete")
source_aarch64=("https://github.com/smallstep/cli/releases/download/v${pkgver}/step_linux_${pkgver}_arm64.tar.gz")
source_x86_64=("https://github.com/smallstep/cli/releases/download/v${pkgver}/step_linux_${pkgver}_amd64.tar.gz")

sha256sums=('add3e078e394e265f6b6a3bf12af81cc7897410ae5e6a0d4ee7714a5b856a7be'
            '3e65c7f99484497e39d20eed3e4ceb4006e8db62dc9987f83a789bb575636e18')
sha256sums_aarch64=("a6cd472fa5eec9356270fbae3ed17b63fc3918901618ac91c5cc265cdca867f7")
sha256sums_x86_64=("4917800ee1cd99ec059dabbf2f40e9ba26ec4b05d70d19e58b526a11e962bde4")
```

Note that the architecture independent sources (autocomplete files) are left in the `source` array, but architecture dependent sources are moved to `source_x86_64`/`source_aarch64`/(and if arm7: `source_armv7h`) arrays.

and changing:

```bash
arch=('x86_64')
```

to

```bash
arch=('x86_64' 'aarch64')
```

For more detail, see the Arch Wiki on PKGBUILD `source`: https://wiki.archlinux.org/index.php/PKGBUILD#source

### Why this is needed
This would allow installing step CLI more easily on raspberry pis and other SBCs running Arch Linux ARM.

**Comment by dopey** [comment]
Hey @tonyfinn, thanks for creating the issue!

We don't have any arch users on the team at this time, hence the barebones AUR repository offering. 

We've also been trying to avoid managing package repositories because there are a lot of them and we have pretty limited resources. Arch AUR is one of the few we do support because one of the maintainers reached out and offered to do most of the work for us. Hard to say no to that :)

Anyhow, I've open sourced the repos that we use for pushing changes to AUR: [step-ca-bin](https://github.com/smallstep/aur-step-ca-bin) and [step-cli-bin](https://github.com/smallstep/aur-step-cli-bin). If you wouldn't mind making the changes that you proposed, I'll happily pull/push them up to AUR to make the new builds available. Cheers!

**Comment by tonyfinn** [comment]
I created two PRs ([step-ca](https://github.com/smallstep/aur-step-ca-bin/pull/1) [step-cli](https://github.com/smallstep/aur-step-cli-bin/pull/1)) to add AArch64 support to the two packages. I did not do arm7, as I don't have any arm7 installations with which to verify my changes.

I cloned off the AUR mirror rather than the github mirror as it appears that the github mirror is a little out of date for both packages, there's a couple of commits and versions present on the AUR mirror that are not present on the github mirror. I'd guess you probably want to sync the AUR and github mirrors with the current contents before merging either PR.

**Comment by dopey** [comment]
Awesome! Many thanks. We're about to go through the process of making a new release, so I'll get these pushed up as part of that.

**Comment by dopey** [comment]
Actually, just pushed these up w/ the existing version. Lmk if they work / dont' work.

**Comment by dopey** [comment]
Closing this issue. Thanks for the help @tonyfinn! If there are further issues let's open them directly on the [step-ca](github.com/smallstep/aur-step-ca-bin) and [step-cli](github.com/smallstep/aur-step-cli-bin) arch pkg repos.

**Comment by tonyfinn** [comment]
Thanks, sorry for taking so long to close the loop but confirmed I could pull down the version pushed to the AUR and install on one of my Pis.
