### ISSUE TITLE
ca bootstrap with team wrongly requires ca-url

### ISSUE THREAD

**Issue by EmiiKhaos** [smallstep/cli#347]
### Subject of the issue
During host onboarding of Smallstep SSH, when configuring the host with `step ca bootstrap --team="[your smallstep team ID]"` it fails with `'step ca bootstrap --team' requires the '--ca-url' flag`.

### Your environment
* OS - RHEL 8
* Version - step-cli 0.15.0

### Steps to reproduce

1. Get a team on https://smallstep.com/sso-ssh/
2. Try to onboard a host https://smallstep.com/docs/sso-ssh/hosts/
3. `step ca bootstrap --team="[your smallstep team ID]"`

### Expected behaviour
It should configure the local step environment to the team step CA.

### Actual behaviour
It fails with `'step ca bootstrap --team' requires the '--ca-url' flag`.

### Additional context
A quick sight show the [bootstrap command first wants to retrieve the `--ca-url` flag](https://github.com/smallstep/cli/blob/v0.15.0/command/ca/bootstrap.go#L93) and fails instantly. Thus it never has the possibility to reach the team url to get the CA url.

This bug is introduced with 0.15.0, in 0.14.6 it works. In 0.15.0 the handling of the flags changed. [In 0.14.6 the required flag is checked withing the team switch statement.](https://github.com/smallstep/cli/blob/v0.14.6/command/ca/bootstrap.go#L92-L106)

**Comment by dopey** [comment]
Think we pushed a fix for this earlier today. Should be resolved in v0.15.2. Thanks for bringing this to our attention! I'll close close the issue, but if you find a problem feel free to re-open or leave a comment.
