### ISSUE TITLE
Do not copy root key if passed in step ca init

### ISSUE THREAD

**Issue by maraino** [smallstep/cli#356]
### Description

If `step ca init` is used with `--root` and `--key` flags, the key is cloned and saved in `$(step path)/secrets`. Neither `step` nor `step-ca` needs that key for normal usage, and we should not "clone" it.

**Comment by azazeal** [comment]
Hi @maraino, can you point me to where the key is cloned, please?

**Comment by azazeal** [comment]
Asking as I ran `step ca init --root=... -key=...` myself and ended up with an intermediary EC key in `secrets` and not the one passed as an argument.

Additionally, and based on the code [here](https://github.com/smallstep/cli/blob/41f9a6ce7628407fbacb1d08fbcbb83ce1e6b5a7/command/ca/init.go#L599), this seems to be already implemented.

Please let me know if I've missed something - alternatively you can go ahead and close this.

**Comment by maraino** [comment]
This was fixed with https://github.com/smallstep/cli/commit/1dd9c2a130d7f944f3e93c6c88345577402921d2
