### ISSUE TITLE
Error while configuring SSH client on Linux

### ISSUE THREAD

**Issue by alishir** [smallstep/cli#358]
### Coul not configure SSH client on Linux
When I tried to configure ssh client with ` step ssh config --team <my_team>`, I got the following error:
```
error getting team data: invalid character '<' looking for beginning of value
```

### Your environment
* OS - Debian
* Version - Testing

### Steps to reproduce
1. Register to smallsteps.com
2. Follow the instructions for SSH client configuration

**Comment by dopey** [comment]
Hey @alishir, it sounds like you're having an issue with the ssh product offered through the website. If you have continuing issues with the product we ask that you submit them via support@smallstep.com. 

With regards to this particular problem, are you copying the command with the `</>` to your terminal? The command should look like: `step ssh config --team myTeamName`. The `</>` characters are commonly used in examples to show that user input should go in place of that particular parameter. 

I'm going to close this issue, but please let us know if you're still having issues. cheers!
