### ISSUE TITLE
Add SHA256SUMS to GitHub releases entries

### ISSUE THREAD

**Issue by dnwe** [smallstep/cli#376]
### What would you like to be added

Add a SHA256SUMS file to https://github.com/smallstep/cli/releases

### Why this is needed

To confirm both file integrity and authenticity after downloading a release binary

**Comment by loganmarchione** [comment]
+1 would like to see this as well

**Comment by hslatman** [comment]
This is covered by the `checksums.txt` available on each release. This file is also signed using Cosign.

**Comment by dnwe** [comment]
Thanks, this was fixed in the interim as part of the move to using goreleaser (https://github.com/smallstep/cli/commit/bb7a30a4c9b431d4f946421f159fe74bef89dd33)
