### ISSUE TITLE
need --provisioner-password-file for sign with a csr

### ISSUE THREAD

**Issue by nforceroh** [smallstep/cli#378]
### What would you like to be added
Add ability to allow --provisioner-password-file like for step ca certificate to automate cert creation
`step ca sign certs/test.nf.lab.csr  certs/ test.nf.lab.crt --issuer user@example.com -f`
like for 
```
step ca certificate test.nf.lab certs/test.nf.lab.crt certs/test.nf.lab.key --set emailAddresses=user@example.com --issuer user@example.com **--provisioner-password-file**=./.passwd -f
✔ Provisioner: user@example.com (JWK) [kid: CPEj0a0y2TIZWAgc2sdfefPbIn0OKw7XD062BNLPOJQ]
✔ CA: https://ca.nf.lab:8443
✔ Certificate: certs/test.nf.lab.crt
✔ Private Key: certs/test.nf.lab.key
```

### Why this is needed
When I try to sign a cert, it requires input for the password, I tried with echo "passwd"|step .... and step ....<EOFpasswdEOF
doesn't accept it
I'm trying to automate certain things with ansible and this is a blocker

**Comment by maraino** [comment]
Hi @nforceroh, you're right, this should be an easy fix, but as a workaround, you might be able to use `step ca token` for this:
```sh
step ca sign --token $(step ca token hello.smallstep.com --password-file /tmp/password) hello.csr hello.crt
```

**Comment by maraino** [comment]
@nforceroh this has been just set to master, thanks for letting us know

**Comment by patsevanton** [comment]
Hello! 
what is binary step ?
Smallstep CA/0.26.1 (linux/amd64)
Release Date: 2024-04-22T20:39:11Z
or
Smallstep CLI/0.26.1 (linux/amd64)
Release Date: 2024-04-23T00:08:02Z
?
