### ISSUE TITLE
step ssh proxycommand: support for specifying a subject different from the ssh user

### ISSUE THREAD

**Issue by EdMcBane** [smallstep/cli#380]
### What would you like to be added
A new option to `step ssh proxycommand`, named `--subject` to specify the subject for the certificate to provision, in case one is required and it needs to be different from the remote user used to connect via ssh.

### Why this is needed
Multiple users, each with their own oidc identity and thus certificate subject, needing to authenticate as a common user on the target server. As of now this is not possible, e.g.:

`ssh ubuntu@ec2-13-251-208-55.eu-south-1.compute.amazonaws.com`

fails to provision a certificate, since it tries to request one with a subject "ubuntu", which is not allowed, my user being francesco.degrassi@domain.here.

**Comment by EdMcBane** [comment]
I'm willing to provide a PR if the issue is valid for you.
Thanks

**Comment by maraino** [comment]
Hi @EdMcBane, I'm not sure if I fully understand your question. I'm going to write a few options that might be related.

1. When you talk about "the subject for the certificate to provision", are you using the `--add-user` flag to create a certificate that can create other principals (users)? If this is the case, the ProxyCommand `step ssh proxycommand` it does not really support this option, although some specific configuration might work. It's better to change the Proxycommand to something like:
```
ProxyCommand ssh -T -F /dev/null -i /path/to/username-provisioner -p %p provisioner@%h
```

For more flexibility in auto provision of users, I would recommend you to check out our SaaS https://smallstep.com/sso-ssh/

2. You also say that
> Multiple users, each with their own oidc identity and thus certificate subject, needing to authenticate as a common user on the target server.

With this statement, I believe that you want all your users ssh to a custom account, e.g. `ubuntu` or `admin`, ... and as your certificates do not have that `ubuntu` principal they cannot properly authenticate. 

This case can be solved with certificate templates, to the OIDC provisioner you need to add a template file like:
```
{
	"type": "{{ .Type }}",
	"keyId": "{{ .KeyID }}",
	"principals": {{ append .Principals "ubuntu" | toJson }},
	"extensions": {{ toJson .Extensions }},
	"criticalOptions": {{ toJson .CriticalOptions }}
}
```

This is basically the default template but, in the principals, we appending the custom one `ubuntu` to all the certificates. So all your users can ssh using the joint account.

The OIDC provisioner in the ca.json should look like 

```
{
	"type": "OIDC",
	"name": "My OIDC",
	"clientID": "...",
	"clientSecret": "...",
	"configurationEndpoint": "https://...",
	"options": {
		"ssh": {
			"templateFile": "templates/certs/ssh/oidc.tpl"
		}
	}
}
```

Here "templateFile" is the path to the template above, you can add an absolute path there, that relative path is based on the STEPPATH of the user running step-ca, by default `$HOME/.step`.

3. Then there are also options that you can add to your `/etc/ssh/sshd_config` to use a specific principal, see for example `AuthorizedPrincipalsCommand` in `man sshd_config`.

Let me know if one of those options was the right one.

**Comment by mmalone** [comment]
For option #2 make sure you use an OIDC provider that _only_ your users have accounts with (e.g., Okta, not G Suite) and/or make sure you've restricted the domain names that are authorized to obtain a certificate by setting `"domains": ["okdomain.com"]` in your OIDC provisioner config.

**Comment by maraino** [comment]
@mmalone I've edited the example to include that.

**Comment by EdMcBane** [comment]
Hello @maraino, @mmalone,  and thanks for your support.
I might have been too brief in my original issue, I'll try to elaborate.

As you outline in (2), I want all my users, authenticated via OIDC, to ssh to a custom account (`ubuntu` in this case) on my servers.
In order to do that, as you outlined in (3), i've set up AuthorizedPrincipalsCommand on the target servers to allow any principal from my gsuite domain to authenticate as `ubuntu`.

Now, if I setup a new workstation with: 
```
step ca bootstrap \
       --ca-url $CA_URL \
       --fingerprint $CA_FINGERPRINT

step ssh login francesco.degrassi@domain.here --provisioner Google
```

and then connect to the host with `ssh ubuntu@server.here`, everything works.

But if I let the ssh certificate expire and try to ssh again with  `ssh ubuntu@server.here`
the CA refuses to grant me the cert, reporting that: `authority.SignSSH: ssh certificate principals does not match - got [ubuntu], want [francescodegrassi francesco.degrassi francesco.degrassi@domain.here]`

My understanding is that this is due to `step ssh proxycommand` using the ssh username (`ubuntu`) as principal for the new certificate when requiring to login before proxying (in `doLoginIfNeeded()`); thus my request to allow me to pass the requested principal for the certificate, which might need to be different from the user I'm trying to authenticate as on the remote host (that is, when using AuthorizedPrincipalsCommand).

I thought of using a new option like `--subject` or `--principal`  as such in `~/.step/ssh/config`:
```
Match exec "step ssh check-host %h"
	User francescodegrassi
	UserKnownHostsFile "/home/fdegrassi/.step/ssh/known_hosts"
	ProxyCommand step ssh proxycommand %r %h %p --provisioner="Google" --subject francescodegrassi
```

**Comment by maraino** [comment]
@EdMcBane: And why not just
```
Match exec "step ssh check-host %h"
	User francescodegrassi
	UserKnownHostsFile "/home/fdegrassi/.step/ssh/known_hosts"
	ProxyCommand step ssh proxycommand francescodegrassi %h %p --provisioner="Google"
```

**Comment by EdMcBane** [comment]
@maraino makes perfect sense and solves my issue.
I misunderstood the usage of the first argument by `step ssh proxycommand`, maybe misled by the following bit of the documentation.

```
POSITIONAL ARGUMENTS
      user
          The remote username, and the subject used to login.
```
which seemed to me to imply that the `user` argument would be used to login to the remote host (I'm _now_ aware it doesn't make sense due to how ProxyCommand works).

Thanks for your support, amazing user experience here.
