### ISSUE TITLE
Support `--password-file` option in `step certificate create` and `step certificate sign` commands 

### ISSUE THREAD

**Issue by casdevs** [smallstep/cli#391]
### What would you like to be added

Would it be possible to add the `--password-file` option to the following commands also?
* `step certificate create`
* `step certificate sign`

### Why this is needed

We would like to automate creating additional intermediate CAs in Docker containers and having their certs be signed by another (offline) step-ca instance. To ease the process of initializing the intermediate CAs and then replace their root and intermediate certs (as described in https://smallstep.com/docs/tutorials/intermediate-ca-new-ca#the-secure-way), we would like to automate generating CSRs with a randomly generated secure private key password, and then having the CSR signed by an already set up offline step-ca which also has its private key password stored in a `./secrets/password` file.

At the moment, this cannot be automated fully because both `step certificate create` and `step certificate sign` commands require the user to enter a private key password manually.
This was already mentioned in https://github.com/smallstep/certificates/issues/154#issuecomment-576537128, but I think it has gone unnoticed.

Although not being familiar with go, after looking into the source code it seems that adding the  `--password-file` option could be implemented without much effort by copying most of the code already used in the `step ca ...` commands.

Thanks,
Stefan

**Comment by patsevanton** [comment]
Hello! 
```
ls
intermediate_ca.crt  ipa.csr  root_ca.crt
```
i try use workaround:
```
sudo step certificate sign --profile intermediate-ca ipa.csr root_ca.crt --key <(step crypto key format --no-password --insecure --pem --password-file <(echo "very secret password") /etc/step-ca/secrets/root_ca_key) | sudo tee -a ipa.crt
error decrypting /etc/step-ca/secrets/root_ca_key: x509: decryption password incorrect
too many positional arguments were provided in 'step certificate sign <csr-file> <crt-file> <key-file>'
```
