### ISSUE TITLE
step certificate create not-after not set correctly

### ISSUE THREAD

**Issue by alphaDev23** [smallstep/cli#400]
Attempting to create a certificate which is valid for at least a year.  After creation, the certificate is only valid for a day.

        Validity
            Not Before: Dec 21 06:51:12 2020 UTC
            Not After : Dec 22 06:52:12 2020 UTC

step --version
Smallstep CLI/0.15.2 (linux/amd64)
Release Date: 2020-08-31 21:35 UTC

Executed, 'step certificate create --not-after 8760h --insecure --no-password --csr foo.example.com foo.csr foo.key' followed by, 'step-ca sign foo.csr foo.crt'

I also used time, 2021-12-31T07:20:50.52Z, in the first command but with the same result.  There is no example in the documentation that I saw for time; I'm unsure if the format is correct but the certificate was created.  Regardless, both time and duration are failing.  The root ca is valid until 2029.

**Comment by dopey** [comment]
Hey @alphaDev23! Thanks for opening the issue.

I think this is a "bug" in the cli, but not quite the bug you've described. Basically, a CSR has no concept of a validity period (`not-before` and `not-after`). Those values are completely defined by the signer (with no influence from the csr). You can `step certificate inspect foo.csr` to verify that no validity period values are stored there.

So, what you're getting is the default validity period, from the provisioner, being applied to your CSR. The "bug" is that we're not failing when you pass in the `--not-after` flag in combination with the `--csr` flag. I'll create a PR for that now. 

Lemme know if that does / doesn't makes sense.
