### ISSUE TITLE
step-ca sign not-after request lacked authority

### ISSUE THREAD

**Issue by alphaDev23** [smallstep/cli#402]
Executing 'step ca sign --not-after 2021-12-31T07:20:50.52Z foo.csr foo.crt' results in:

"The request lacked necessary authorization to be completed. Please see the certificate authority logs for more info.
Re-run with STEPDEBUG=1 for more info."

Without --not-after, the cert is signed without issue but is only valid for a day.  Same provisionerkey entered for both executed commands (copy/paste)

Re-executing 'STEPDEBUG=1 step ca sign --not-after 2021-12-31T07:20:50.52Z foo.csr foo.crt' just repeats the 1st error sentence twice.

For the CA, I'm using 'smallstep/step-ca:latest  95b0a1b4feee  3 months ago  77MB'.  '/var/log/' is empty and executing a find on *.log within the container as root does not produce any results so I'm unable to find the 'certificate authority logs' mentioned in the error message.

step --version
Smallstep CLI/0.15.2 (linux/amd64)
Release Date: 2020-08-31 21:35 UTC

Why is the above 'step ca sign --not-after' command failing, where are the certificate authority logs, and why when executing step-ca with STEPDEBUG=1, the same error is produced (as without the variable), substantively?

**Comment by dopey** [comment]
@alphaDev23 My guess is this is a configuration issue. When I run that command I see the following line in my CA logs: 

```
WARN[0030]                                               duration=1.747946ms duration-ns=1747946 error="authority.Sign: requested duration of 8989h22m44s is more than the authorized maximum certificate duration of 24h1m0s" fields.time="2020-12-21T12:59:06-05:00
...
```
By default, the global maximum certificate duration is 24hrs. If you'd like to change the global, or adjust the maximum by provisioner, you can do so by modifying the `step-ca` configuration file and then restarting the CA.

https://smallstep.com/docs/step-ca/configuration#example-configuration

`authority.claims` are the global claims. You can also set claims that are scoped to the provisioner (see `provisioner[0].claims` in the example). If you set your `maxTLSCertDuration` to something larger than what you're requesting, you should no longer see that error.

As to why you're unable to see the logs from `step-ca`, I'm not really sure. Are you running a `step-ca` docker container found on our dockerhub (https://hub.docker.com/repository/docker/smallstep/step-ca)?

**Comment by alphaDev23** [comment]
Changing the CA configuration resolved the issue.  Thank you.

Yes, I'm using the step-ca image on dockerhub, although the 'latest' image from 3 months ago.

**Comment by dopey** [comment]
Try using `docker logs -f <container>`. The logs are output to `stdout`, so they _should_ appear in docker logs. If you're using kubernetes, you'll want to use `kubectl logs`.

Going to mark this issue as closed since the configuration issue is resolved. If you're still having trouble seeing the logs, open a new issue/discussion (or join us over in gitter) and we'll be glad to help out.

**Comment by maraino** [comment]
Hi @alphaDev23, as @dopay says, the logs should be available using `docker logs`. You can also use "durations" with not after, for example `--not-after 1h` will make the certificate valid for 1h
