### ISSUE TITLE
Certificate Extractation feature request

### ISSUE THREAD

**Issue by tehmoon** [smallstep/cli#405]
Hi Step team!

### What would you like to be added

I wrote a tool more than 2 years ago that does the following two things:
- filter PEMs: output selected PEM blocks based on some filters. This is because I heavily use OpenSSL CLI to decode x509/asn.1 and there is no easy way to do x509 decode arbitrary certificates with: `openssl s_client -showcerts | openssl x509 -noout -text` 
  - position of the blocks
  - type of block
 - extract code signing certificates from Windows Portable Executable files on linux. There is an utility that exists to sign PE files on linux, but nothing that makes it pipeable to, let's say, openssl. There is a really good PE golang standard library [https://golang.org/pkg/debug/pe/](https://golang.org/pkg/debug/pe/) where I had fun digging through the windows docs to extract the right field. The format is in PKCS7 if I recall correctly.

### Why this is needed

I completely rewrote that tool and never ported those two features, mainly because it did not make sense anymore, but I still use them since I don't know of any portable alternative and I thought of making a standalone to extract certificates. But then, I wondered if it would not be better to integrate those two features in Step, sharing the love instead of doing that on my own.

Of course, I know that everybody is busy, so I'll be happy doing it with guidance, or just share the code if the team thinks it's valuable and makes sense.

**Comment by dopey** [comment]
Hey @tehmoon, thanks for opening the issue!

We've got a couple questions --

1. What's the use case for your first bullet point - "output selected PEM blocks based on filters"? We have the `step certificate inspect --format JSON` which you can then pipe to `jq`. But this  probably wouldn't allow for the expressiveness of a regular filter. So, what the need for this feature would be.

2. This sounds cool, and it's in an area where we don't have much expertise. Our main question was where code / functionality like this would live in our tool chain. If you're willing to open a PR, we'd be happy to take a closer look.

We're always open to people opening PRs or just sharing code. As you said, everyone's busy, but we're always happy to work with folks from the community who've spent time using and even modifying our tools. That's where we tend to get the best feedback.

**Comment by tehmoon** [comment]
@dopey thank you for taking the time to go through the issue and to answer!

1. Thank you so much for pointing out `step certificate inspect`. I was able to successfully achieve what I wanted with the `--bundle` option!!
2. Great! I can slowly get started and look at the code. I don't know all the features yet. I'm unsure where it fits yet but I think I'd like to implement:
    1. inspect
    2. verify
    3. signing could be challenging, especially that I have no idea how to make it work with USB tokens...

**Comment by maraino** [comment]
@tehmoon you might be able to implement the signing using the KeyManager interface:
https://github.com/smallstep/certificates/blob/00c6f0861267a679a2a1c6f670839f26ff91c718/kms/apiv1/options.go#L12-L17

From a KMS you can do `CreateSigner`, and then use the `crypto.Signer` to get the signed data. If you want to use a USB device to sign, we currently only support YubiKey, but this is not enabled by default as it requires `cgo`, but it can be enabled with the appropriate flags when building `step`.

This code shows how to use yubikey to sign a X.509 certificate, I'll guess what you need for an executable will be similar https://github.com/smallstep/certificates/blob/master/cmd/step-yubikey-init/main.go#L185-L216

Unfortunately, we don't have implemented the offline signing on step using the KeyManager interface, so I think it will be harder than it sounds. I also have some more or less a clear idea of how would external KMS will be used in `step`. For example to reference a specific key we should use RFC7512-like uris. For example, to refer to the slot 9a of a yubikey a possible uri would be `yubikey:slot-id=9a?pin=123456`

**Comment by tehmoon** [comment]
Thank you so much @maraino for taking the time to explain.

I'll look into it, could be a fun project to learn something new!

**Comment by maraino** [comment]
@tehmoon I would start with inspect and verify. In the interview for my first job, based on docs on how PE headers worked, I had to create a parser and show information about an executable. We later supported signed executables (that if I remember properly, you can modify some parts of the exe and pass the signature, it was a "feature")

**Comment by tehmoon** [comment]
@maraino gotcha! Yeah that's exactly how I did it as well. My code for inspection: https://github.com/tehmoon/cryptocli/blob/v0.10/command/codeSignCerts.go#L192 which I need to fully port here. For signing, as you mentioned, need to find where the code lies and then probably checksum it, finally build the certificate and sign with a key of some sort.

**Comment by maraino** [comment]
Have you seen https://github.com/mozilla-services/pkcs7? It's based on the same fork, than the one you're using.

**Comment by tehmoon** [comment]
@maraino I actually saw this when I was writing the description of this PR! It is great that there is now a more sustainable pkcs7 library in go!

**Comment by maraino** [comment]
@tehmoon Can you post here a usage example for `step certificate inspect --json ... | jq`. Or just create a PR adding it in the examples section of https://github.com/smallstep/cli/blob/master/command/certificate/inspect.go

If it useful to you it's probably useful for others.

**Comment by tehmoon** [comment]
The extract part is done. I'll find some time doing the verify part. Not sure when but I'll take the time here and there.

**Comment by maraino** [comment]
Fixed with #407
