### ISSUE TITLE
P12 creation error 

### ISSUE THREAD

**Issue by chuckf** [smallstep/cli#410]
### Subject of the issue
I'm trying to create a p12 file from a .crt and .key file that i created using the step client. However, I get an error that reads "No help topic for 'p12'". 

### Your environment
* OS - Fedora
* Version - 
Smallstep CLI/0.14.7-rc.2.temp-rc-latest (linux/amd64)
Release Date: 2020-08-02 21:04 UTC

### Steps to reproduce
1. Create a .crt and .key file for use with a server using the step client.
2. Run the command `step certificate p12 srv.p12 srv.crt srv.key`
3. Not resulting failure that reads `No help topic for 'p12'`

### Expected behaviour
i expect a file to be created called `srv.p12`

### Actual behaviour
Output in the terminal of a failure message that reads `No help topic for 'p12'`

### Additional context
This may be related in some way to #244 but that is an open request for the feature. 
I found the documentation on the website at https://smallstep.com/docs/step-cli/reference/certificate/p12

**Comment by dopey** [comment]
Hey @chuckf are you able to try a more recent version of smallstep cli? It's likely the `p12` command hadn't been added yet in v0.14.7.

**Comment by chuckf** [comment]
My apologies. I thought I had upgraded this system already. After the upgrade it is working as expected.

**Comment by dopey** [comment]
woot! No worries.
