### ISSUE TITLE
Installation Docs Bug - "wget -o" vs "wget -O"

### ISSUE THREAD

**Issue by chuckf** [smallstep/cli#411]
### Subject of the issue
When installing the step-ca and step-cli on Fedora using the commands from https://smallstep.com/docs/step-ca/installation#rhelcentos I ran into an issue where the tar command failed. This is due to `-o` being used in the wget command vs `-O`. The lower case `o` creates a log file of the wget command execution while the `-O` saves the download to a particular file name. 

### Your environment
* OS - Fedora 33
* Version - Latest docs at https://smallstep.com/docs/step-ca/installation#rhelcentos

### Steps to reproduce
Attempt to use the wget command with `-o` and receive an error at the cli:

`tar -xf step-ca.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

### Expected behaviour
Create a valid tar file

### Actual behaviour
Saves a log file

**Comment by tashian** [comment]
Fixed! Thanks Chuck for reporting this.
