### ISSUE TITLE
Automated way to change key password

### ISSUE THREAD

**Issue by jrsmith3** [smallstep/cli#416]
### What would you like to be added
I would like to be able to non-interactively change the password for a key using `step crypto change-pass`.

### Why this is needed
The best practices document [suggests](https://smallstep.com/docs/step-ca/certificate-authority-server-production#use-strong-passwords-and-store-them-well)

> After initializing your CA, we recommend that you immediately change the password for the intermediate CA private key

Currently the only option to change the password is to respond to the interactive prompts. As a result, it would be difficult to automate this operation with a utility like Ansible.

I [asked](https://github.com/smallstep/certificates/discussions/467) how to automate the `step crypto change-pass` command on the `certificates` repo discussion, and both @tashian and @maraino mentioned possibly adding a `--password-file` flag to `step crypto change-pass` to address this issue. I would like to respectfully suggest that two flags might be necessary: one to indicate the password to decrypt and another to indicate the password to encrypt.

Additionally, @maraino posted the following command sequence (using bash pipes) to accomplish a non-interactive key password change.

```bash
cat $(step path)/secrets/intermediate_ca_key | \
    step crypto key format --password-file /tmp/old-password.txt | \
    step crypto key format --password-file /tmp/new-password.txt
```

**Comment by tashian** [comment]
@mohe2015 this new feature may be of interest to you for NixOS CA init flow!

**Comment by mohe2015** [comment]
@tashian Thanks, it's likely useful for the manual setup but the NixOS module itself only cares about the config file in the new proposal. So the user needs to take care of creating and securely storing certificates by themselves.
