### ISSUE TITLE
Try out GoReleaser for release process

### ISSUE THREAD

**Issue by tashian** [smallstep/cli#418]
https://goreleaser.com/intro/

**Comment by maraino** [comment]
In the limitations, goreleaser mentions CGO, that is going to be important when we add CGO and non-CGO binaries, for supporting things like YubiKey and PKCS#11 modules in the cli. But it links to this project https://github.com/troian/golang-cross

**Comment by tashian** [comment]
I've written a basic config that builds multiarch binaries, archives, and docker images (non-CGO) using our naming & dir structure conventions.

To try it:
- [Install GoReleaser on your machine](https://goreleaser.com/install/)
- Checkout branch [`carl/goreleaser`](https://github.com/smallstep/cli/tree/carl/goreleaser).
- Run `goreleaser --snapshot --skip-publish --rm-dist`
- See the output in the `dist` folder.

Notes:
- GoReleaser will build files with a `v` prefix before the version number eg. `step_linux_v0.15.4-rc.4-next_amd64.tar.gz`. This is a goreleaser bug, but it only does this for snapshot builds; for actual releases it will not include the `v` prefix.
- I changed the `Dockerfile` to stop building `step` inside the container. This may work for now, but when we need CGO support it's not going to work.

TODOs to replace current Makefile/GH Actions build process:
- [ ] Configure & test DockerHub push
- [ ] Configure [Homebrew support](https://goreleaser.com/customization/homebrew/)
- [ ] Configure [Scoop packaging](https://goreleaser.com/customization/scoop/)
- [ ] Move to GitHub Actions workflow (see [GoReleaser GitHub Actions doc](https://goreleaser.com/ci/actions/))
- [ ] Configure [GitHub release creation](https://goreleaser.com/customization/release/)
- [ ] Configure [source archive](https://goreleaser.com/customization/source/)

(What else?)

Version 2:
- [ ] Add CGO support (this will be a fair bit of work)

**Comment by maraino** [comment]
Is it possible to build with `-trimpath`?

**Comment by tashian** [comment]
@maraino yes— I've added this.

**Comment by hslatman** [comment]
Closing this as GoReleaser is now in use.
