### ISSUE TITLE
Deb release missing after 0.15.3?

### ISSUE THREAD

**Issue by Beanow** [smallstep/cli#427]
### Subject of the issue

Looks like deb installers are no longer part of the release artifacts.
Couldn't find any threads about removing it, so assuming this is unintentional from moving to goreleaser?

### Your environment
* OS Ubuntu 18.04 LTS
* Version -

### Steps to reproduce

https://smallstep.com/docs/step-cli/installation#debian-linux

This has a deb: https://github.com/smallstep/cli/releases/tag/v0.15.3
This does not: https://github.com/smallstep/cli/releases/tag/v0.15.7

**Comment by dopey** [comment]
yep. :< damn. Will try and fix today / over the weekend. Got a little trigger happy with goreleaser.

**Comment by dopey** [comment]
This should be fixed in the next release. Thanks for bringing to our attention.
