### ISSUE TITLE
Password file with trailing newline fails to en-/decrypt

### ISSUE THREAD

**Issue by Beanow** [smallstep/cli#428]
### Subject of the issue

Using `--password-file` / `--ca-password-file` where the file contains a trailing newline fails to en-/decrypt.

For example: `pwgen -s 64 1 > my_pass` would have a trailing newline.

### Your environment
* OS Docker 20.10 linux/amd64
* Version `smallstep/step-cli:0.15.7`

### Steps to reproduce

```sh
#!/bin/bash
docker run --rm -i \
	smallstep/step-cli:0.15.7 \
	/bin/bash <<'EOF'
echo -n "helloworld!" > pw_clean

step certificate create \
	--profile root-ca \
	--password-file pw_clean \
	"root:clean" \
	root_clean.crt root_clean.key

step certificate create \
	--force \
	--profile root-ca \
	--key root_clean.key \
	--password-file pw_clean \
	"root:clean" \
	root_clean.crt

step certificate create \
	--profile intermediate-ca \
	--ca root_clean.crt \
	--ca-key root_clean.key \
	--ca-password-file pw_clean \
	--password-file pw_clean \
	"inter:clean" \
	inter_clean.crt inter_clean.key

echo "helloworld!" > pw_newline

step certificate create \
	--profile root-ca \
	--password-file pw_newline \
	"root:newline" \
	root_newline.crt root_newline.key

# error decrypting root_newline.key: x509: decryption password incorrect
step certificate create \
	--force \
	--profile root-ca \
	--key root_newline.key \
	--password-file pw_newline \
	"root:newline" \
	root_newline.crt

# error decrypting root_newline.key: x509: decryption password incorrect
step certificate create \
	--profile intermediate-ca \
	--ca root_newline.crt \
	--ca-key root_newline.key \
	--ca-password-file pw_newline \
	--password-file pw_newline \
	"inter:newline" \
	inter_newline.crt inter_newline.key
EOF

```

The above script will run 4 steps with 2 variants of the password:
1. echo a password into a file.
2. Create a root-ca.
3. Try to overwrite the root-ca certificate by decrypting the existing key & password.
4. Create an intermediate-ca by decrypting the root key & password.

The version without a trailing newline completes these just fine.
The version **with** a trailing newline will fail steps 3 and 4.

### Expected behaviour

Trailing newlines should be either consistently ignored or consistently used in en-/decryption.

### Actual behaviour

The newline does affect the encryption key, but is not properly reconstructed when decrypting.

### Additional context

-

**Comment by maraino** [comment]
Hi @Beanow, thanks for noticing, in that flow we were using the utility function that we usually use to read passwords from a file, I've fixed it for this flow in https://github.com/smallstep/cli/issues/428. I'll merge it to master when the CI finishes.
