### ISSUE TITLE
Debian package ist no available for download

### ISSUE THREAD

**Issue by jotihojr** [smallstep/cli#439]
### Subject of the issue

Version v0.15.3 is the last release where a deb package is available.
https://github.com/smallstep/cli/releases/tag/v0.15.3

### Your environment
* OS - 
* Version - 

### Steps to reproduce
Visit https://github.com/smallstep/cli/releases/latest

### Expected behaviour
*.deb file should be available for download

### Actual behaviour
Debian package file is not available.

### Additional context
According to https://github.com/smallstep/certificates#debian the Debian should be available.

**Comment by dopey** [comment]
Hey, thanks for opening the issue. I fixed this but forgot to push out a new release. Release is now pushed. Lmk if you see any more issues.

**Comment by dopey** [comment]
https://github.com/smallstep/cli/releases/tag/v0.15.8
