### ISSUE TITLE
New binary name conflicts with existing package on Debian

### ISSUE THREAD

**Issue by HHJB** [smallstep/cli#443]
### Subject of the issue
The newly change of step binary from step-cli to step conflicts with an existing package on Debian. The existing/conflicting package is 'step' (interactive physical simulator for KDE)

### Your environment
* OS - Debian
* Version - buster (all versions since 2014)

### Steps to reproduce
check package repository

### Expected behaviour
no conflict

### Actual behaviour
conflict (thinks it is the other step on apt-get upgrade)

### Additional context
Please revert to step-cli

**Comment by dopey** [comment]
@tashian just in case you didn't catch this. Switching the `deb` naming convention back to `step-cli`.

**Comment by tashian** [comment]
Rats.
