### ISSUE TITLE
SCP does not work with smallstep cli  on windows power shell

### ISSUE THREAD

**Issue by pizzasaurusrex** [smallstep/cli#455]
### Subject of the issue
Describe your issue here.

### Your environment
* OS - Windows
* Version - 

### Steps to reproduce
it works from scp on Linux, but not from Windows Powershell.

From a fresh Windows install. If we try to scp (from Powershell not WSL) it works. After we configure step (following Client Quick Start — Smallstep), we can't scp anymore, not even scp to not step registred host. 

It seems that the scp process goes in "background", we can't type password for example.

If I comment the lines added by step at the beginning of ~/.ssh/config, scp works again.

### Expected behaviour
SCP should work with step installed

### Actual behaviour
It exits successfully but the file is never uploaded

**Comment by tashian** [comment]
This may be an OpenSSH for Windows bug.
I'm able to reproduce this in Windows 10, in Windows Terminal, using the built-in SSH client (SSH for Windows v7.7p1):

```
PS C:\Users\lab> scp -vv localhost.key ec2-xxxx-206.compute-1.amazonaws.com:
Executing: program ssh.exe host ec2-xxx-206.compute-1.amazonaws.com, user (unspecified), command scp -v -t .
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\lab/.ssh/config
debug1: C:\\Users\\lab/.ssh/config line 2: Applying options for *
debug1: Reading configuration data /Users/lab/.step/ssh/config
debug2: checking match for 'exec "step ssh check-host %h"' host ec2-xxx-206.compute-1.amazonaws.com originally ec2-xxx-206.compute-1.amazonaws.com
true
debug2: match found
PS C:\Users\lab> debug1: Executing proxy command: exec C:\\Windows\\System32\\cmd.exe /c step ssh proxycommand --provisioner "okta" carl ec2-xxx-206.compute-1.amazonaws.com 22
debug1: key_load_public: No such file or directory
d
```

* The `match exec` for `step ssh check-host` appears to cause the whole scp process to run in the background (causing the PowerShell prompt that you see in the middle of the output)
* The transfer appears to complete and the process exits `0`, but no file ends up on the remote host
* I was also able to confirm the issue on [the latest OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta) v8.1p1

**Comment by tashian** [comment]
Just opened a PR to fix this. The issue was printing to stdout in the `step ssh check-host` call.

**Comment by tashian** [comment]
@pizzasaurusrex this is merged and once it's released they can upgrade to get this working.
in the meantime, if they want a short-term fix they can change the match exec line in `.step/ssh/config` to:

```
Match exec "step ssh check-host %h > NUL"
```
