### ISSUE TITLE
'step ca provisioner add' panics on fresh k8s install from helm chart

### ISSUE THREAD

**Issue by jf647** [smallstep/cli#473]
### Subject of the issue

On a freshly installed step-ca using the helm chart (chart version 1.15.13, which is using image cr.step.sm/smallstep/step-ca:0.15.13), trying to add an ACME provider crashes with a nil pointer exception.

### Your environment
* OS - server k8s 1.20.5 (linux amd64), client ubuntu 20.04.1 (amd64)
* Version - CLI version is 0.15.16

### Steps to reproduce

Install into a k8s cluster using the helm chart.  The values I provided (though I don't think they're germane to the problem):

```yaml
    service:
      type: LoadBalancer
    ca:
      name: whatever CA
      dns: ca.whatever.domain
      url: https://ca.whatever.domain
      db:
        size: 2Gi
```

Bootstrap CLI:

```shell
  step ca bootstrap --ca-url https://ca.whatever.domain --fingerprint fingerprint_I_grabbed_by_looking_at_the_configmap
```

Verify health and that we can get the root cert:

```shell
$ step ca health
ok
$ step ca root
-----BEGIN CERTIFICATE-----
yada
yada
yada
...
-----END CERTIFICATE-----
```

Try to add ACME provider as described [here](https://smallstep.com/docs/tutorials/acme-challenge)

```shell
$ STEPDEBUG=1 step ca provisioner add acme --type ACME
Smallstep CLI/0.15.16 (linux/amd64)
Release Date: 2021-04-15T22:33:22Z

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc45101]

goroutine 1 [running]:
main.panicHandler()
        command-line-arguments/main.go:121 +0x38b
panic(0xfe2e00, 0x199caf0)
        runtime/panic.go:965 +0x1b9
github.com/smallstep/cli/command/ca/provisioner.addAction(0xc00057ab00, 0x0, 0x0)
        github.com/smallstep/cli/command/ca/provisioner/add.go:334 +0x181
github.com/urfave/cli.HandleAction(0xfccb00, 0x11fb070, 0xc00057ab00, 0xc00057ab00, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:524 +0xb8
github.com/urfave/cli.Command.Run(0x114333b, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x119de1e, 0x31, 0x11ceb27, ...)
        github.com/urfave/cli@v1.22.4/command.go:174 +0x579
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00022c540, 0xc00057a6e0, 0x0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:407 +0x914
github.com/urfave/cli.Command.startApp(0x115670d, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11a4a6a, 0x38, 0x11b07c1, ...)
        github.com/urfave/cli@v1.22.4/command.go:373 +0x7ff
github.com/urfave/cli.Command.Run(0x115670d, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11a4a6a, 0x38, 0x11b07c1, ...)
        github.com/urfave/cli@v1.22.4/command.go:102 +0xa14
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00022c380, 0xc00057a000, 0x0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:407 +0x914
github.com/urfave/cli.Command.startApp(0x11423f0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1199887, 0x2d, 0x11ab9a1, ...)
        github.com/urfave/cli@v1.22.4/command.go:373 +0x7ff
github.com/urfave/cli.Command.Run(0x11423f0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1199887, 0x2d, 0x11ab9a1, ...)
        github.com/urfave/cli@v1.22.4/command.go:102 +0xa14
github.com/urfave/cli.(*App).Run(0xc00022c1c0, 0xc000030070, 0x7, 0x7, 0x0, 0x0)
        github.com/urfave/cli@v1.22.4/app.go:279 +0x808
main.main()
        command-line-arguments/main.go:97 +0x3ed
```

### Expected behaviour

A new provider is added

### Actual behaviour

NPE panic

### Additional context

The panic is caused by [this line](https://github.com/smallstep/cli/blob/118d57818c1a95c6014af8806a7a43e280af2bcb/command/ca/provisioner/add.go#L334), where the CLI tries to build a map of provisioners without checking if c.AuthorityConfig is nil first.

A safety check to prevent panic is probably called for in any case, but this may be a documentation / workflow issue.  The tutorials all seem to assume that you're running these commands on the same machine which is running step-ca, which isn't the case when you've installed into k8s.   Is `step ca provisioner add` meant to be usable remotely?

I can run `step ca provisioner list` remotely and see the dummy JWT provisioner that the helm chart sets up:

```shell
$ step ca provisioner list
[
   {
      "type": "JWK",
      "name": "admin",
      "key": {
         "use": "sig",
         "kty": "EC",
         "kid": "yada...",
         "crv": "P-256",
         "alg": "ES256",
         "x": "yada...",
         "y": "yada...",
      },
      "encryptedKey": "yada...yada...yada..."
   }
]
```

So there's obviously some element of the command being able to ask the server to operate on its configs as opposed to files on my local disk, but looking at the [authority package](https://pkg.go.dev/github.com/smallstep/certificates/authority) that is responsible for loading and saving, it doesn't seem to use any network calls.

Perhaps [this doc page](https://smallstep.com/docs/step-ca/getting-started#accessing-your-certificate-authority) needs a clause explaining that not every command can be run remotely?  That, paired with a classification for each CLI subcommand in its help (e.g. "this command can only be run locally on the step-ca server") would avoid this confusion.

If my assumption is correct, what is the proper workflow for a step-ca hosted in k8s?  Use `kubectl exec` to get a shell in the pod and then run the command there?

**Comment by dopey** [comment]
Hey @jf647 thanks for the very detailed issue! I was able to reproduce.

Should be pushing a fix shortly. Probably a bit longer till it makes it way into a release and then helm-charts.

**Comment by dopey** [comment]
Ah, shoot, didn't notice that you had a few questions in there as well.

> A safety check to prevent panic is probably called for in any case, but this may be a 
> documentation/ workflow issue. The tutorials all seem to assume that you're running these 
> commands on the same machine which is running step-ca, which isn't the case when you've 
> installed into k8s. Is step ca provisioner add meant to be usable remotely?

The `step-ca` CRUD commands are not meant for remote use (at this time - we're actively working on remote APIs). The CRUD commands (add / remove) only modify the local config.

The "easiest" route for adding provisioners in k8s helm chart distribution is to:
1) Run a local `step-ca`
2) Execute the `provisioner` add command locally on your local `step-ca` config file.
3) Apply the changes that you see locally to the `step-ca` config in the helm charts which should be held in a configmap. Generally this just involves copying a provisioner block.

The process is not great :/ Unfortunately, step-ca has no authentication currently built in to be able to accept provisioner add/remove/update requests. Hence why we only allow modification of the a local `step-ca` file. As I said, we're building those features now, but they're probably a few months from being released.

**Comment by dopey** [comment]
Closing this issue. Please let us know if you're still experiencing this issue and we will reopen.
