### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by klauern** [smallstep/cli#48]
One of the best features of Go is that it can fairly easily cross-compile to other operating systems, namely Windows.  Windows lacks a lot of good CLI tools for, well, pick just about anything, so I would like to see this tool have Windows support.

**Comment by sourishkrout** [comment]
Hi @klauern. Thanks for filing this issue. We currently have no timeline yet for Windows support and marked this issue as feature request.

We'd love to see you get involved. We should be able to produce Windows binaries which then will need to be tested and ideally have unit tests run on CI (Travis/AppVeyor) to make sure the functionality is and stays there.

**Comment by sourishkrout** [comment]
Hi @klauern. I wanted to let you know that as of the latest release we're including a Windows build `step.exe` with every new release: https://github.com/smallstep/cli/releases/tag/v0.14.2
Please note that we haven't gone through thorough testing to make sure all of the functionality is available on Windows. If you encounter any specific issues please feel free to open new tickets for these.
