### ISSUE TITLE
Error message gives inverted order of required flags

### ISSUE THREAD

**Issue by alexpovel** [smallstep/cli#480]
### Subject of the issue

There's an error message that reports on erroneous CLI flag usage, but it seems the wrong way around.

### Your environment
* OS - Windows 10
* Version - `Smallstep CLI/0.15.17-rc1.test-arm6 (windows/amd64)`

### Steps to reproduce

Run [this command](https://smallstep.com/docs/step-cli/reference/crypto/keypair#options), which fails:

```bash
$ step crypto keypair test.pub test.key --no-password
flag '--insecure' requires the '--no-password' flag
```

The docs tell us:

> **`--no-password`** Do not ask for a password to encrypt a private key. Sensitive key material will be written to disk unencrypted. This is not recommended. Requires `--insecure` flag.

So I guess the error message should be more like: `flag '--no-password' requires the '--insecure' flag`, aka the other way around.

**Comment by dopey** [comment]
Thanks @alexpovel! Was able to find a few more places where we got the order wrong. cheers!
