### ISSUE TITLE
redirect-url doesnt work

### ISSUE THREAD

**Issue by 89z** [smallstep/cli#510]
If I run a command like this:

~~~
step oauth --redirect-url=urn:ietf:wg:oauth:2.0:oob
~~~

I still get the localhost url:

~~~
https://accounts.google.com/o/oauth2/v2/auth?
client_id=1087160488420-8qt7bavg3qesdhs6it824mhnfgcfe8il.apps.googleusercontent.com&
code_challenge=Uk_xqM911XAjUuG4kIAFFRfNRnYi2ciYdFU7rlo2NoI&
code_challenge_method=S256&
nonce=9ab7adfa13a2e8bfd6a0c58fe554549d1a084c3fd333f6c0c63924327727006d&
redirect_uri=http%3A%2F%2F127.0.0.1%3A58340&response_type=code&
scope=openid+email&state=DvmigvUDZDziYcInEEwRL1x9mXwZLPON
~~~

https://smallstep.com/docs/step-cli/reference/oauth

**Comment by maraino** [comment]
Hi @89z, to use the out-of-band flow you should use the `--console` flag. And in case you need to use a specific port you can also use `--listen :10000` (`--listen [<ip>]:<port>`).

We use the flag `--redirect-url` to redirect users to an external page where they can see some docs or instructions on what to do next. This redirection takes place after the oauth flow finishes.

We should fix the docs to clarify this.

**Comment by 89z** [comment]
Thanks - this works as expected:

~~~
step oauth --console
~~~

I agree, that documentation on this item could be better. Thanks again
