### ISSUE TITLE
step v0.15.17+ on Darwin (arm64) is killed when run

### ISSUE THREAD

**Issue by carlashley** [smallstep/cli#520]
### Subject of the issue
step v0.16.1 for Darwin (arm64) is killed when run on macOS 11.5.2.
For example:
```
[user@local]:~ # step --version
zsh: killed     step --version
```
This occurs on all releases after v0.15.16 (this is the last release that works correctly on my Apple Silicon Mac).

### Your environment
* OS - macOS 11.5.2 (20G95)
* Version - v0.15.17 through to v0.16.1
* Shell - `/bin/zsh` - zsh 5.8 (x86_64-apple-darwin20.0)

### Steps to reproduce
Download any of the Darwin `arm64` releases from v0.15.17 to v0.16.1(and including).
Un-tar them in the Download directory
```
tar -xvf [steptarfile]
sudo cp [stepfolder]/bin/step /usr/local/bin/step && sudo chown root:wheel /usr/local/bin/step
step --version
ssh [host]
```

### Expected behaviour
The step version output should print to screen and (presuming ssh config is setup to use step) subsequently ssh into the specified server.

### Actual behaviour
step is killed

### Additional context
The arch type reported back for versions v0.15.17 to v0.16.1 is:
```
[user@local]:~ # file /usr/local/bin/step
/usr/local/bin/step: Mach-O 64-bit executable arm64
```
This is the same arch type that v0.15.16 reports back, reverting back to v0.15.16 works.

This `zsh: killed     step --version` message is something I've seen other binaries report back when they're not `arm64` compatible.

**Comment by dopey** [comment]
Hey @carlashley How are you installing `step`?

**Comment by carlashley** [comment]
I'm not in a position to use `homebrew` for reasons, but it would be interesting if the issue exists/doesn't exist there.

**Comment by dopey** [comment]
No worries. Knowing whether homebrew version is working on arm64 mac would help to pinpoint the issue. Hoping that we would have heard by now if there was an issue with the homebrew build for arm64.

We'll do our best to take a look this week. Not sure that any of us have a new enough mac to be on arm64. Maybe someone from the community can corroborate? I can also ping our discord to see if anyone there has a new enough macbook.

**Comment by maraino** [comment]
@carlashley Is it possible that macOS Gatekeeper is killing the app? Do you get the same problem if you go to Finder and try to open it using your mouse right click->open? Do you get the "are you sure you want to open it" message? 

I don't have access to an ARM mac to test it.

**Comment by carlashley** [comment]
@maraino So I grabbed v0.16.1 again and re-ran through installing it and it's working fine. I suspect you were right and I had not included removing the quarantine xattr's from the tarball and extracted files.

Sorry for the false alarm.
