### ISSUE TITLE
Using `--bundle` switch in `step ca certificate` requests results in "too many positional arguments" error

### ISSUE THREAD

**Issue by DL444** [smallstep/cli#521]
### Subject of the issue
Using `--bundle` switch in `step ca certificate` requests results in "too many positional arguments" error

### Your environment
* OS - macOS 11.5
* Version - step CLI 0.15.16

### Steps to reproduce
Request a certificate from a step CA with the following command:
`step ca certificate site.example.com ./cert.crt ./cert.key --ca-url ca.example.com --root ./root.crt --bundle`

### Expected behaviour
A leaf certificate should be issued with the intermediate signing certificate bundled.

### Actual behaviour
The command returns an error with message:
> too many positional arguments were provided in 'step ca certificate \<subject\> \<crt-file\> \<key-file\>'

### Additional context
Try again without the `--bundle` switch:
`step ca certificate site.example.com ./cert.crt ./cert.key --ca-url ca.example.com --root ./root.crt`

The certificate is issued normally.

**Comment by dopey** [comment]
Hey @DL444 👋 

The `step ca certificate` subcommand does not accept a `--bundle` flag. By default `step ca certificate` returns a certificate bundle with `leaf -> intermediate [-> intermediate 2 ...]`. You can see this by running `step certificate inspect ./cert.crt --bundle` on the generated certificate.

**Comment by mmalone** [comment]
I think there's still a bug here in our error messages. The error should indicate that the `--bundle` flag isn't valid. I didn't do a full bisect, but it looks like this is a regression that was introduced a while ago. I tested `v0.14.2` and got the (incorrect) positional argument error. With `v0.11.0` I get the correct error (`Incorrect Usage: flag provided but not defined: -bundle`, followed by the help text).

**Comment by DL444** [comment]
@dopey 
Thanks for your clarification. Just a reminder, I tried the flag after I saw it listed in `step ca certificate --help`. Maybe the help content needs some updating as well.

**Comment by dopey** [comment]
Uh oh! That's not good. Looking into it!

**Comment by dopey** [comment]
Ah, I see it. In the usage. Removing!

**Comment by dopey** [comment]
https://github.com/smallstep/cli/commit/d7300d43a5c66cb70914c6f5e9a2b30727d6c221

**Comment by dopey** [comment]
Thanks @DL444!
