### ISSUE TITLE
Renew Loop when using `step ca renew --daemon`

### ISSUE THREAD

**Issue by mxzinke** [smallstep/cli#523]
The subject is the `step ca renew --daemon` command.

### Environment
* OS - Windows 10 IoT Enterprise Edition
* Version - 0.15.3

### Steps to reproduce
Start a daemon with `step ca renew --daemon` to renew certificates.

### Expected behavior
The daemon will renew the certificate(s) when 2/3 of the expiry time range is reached and a new certificate is created in a given path.

### Actual behavior
The daemon requests every ~4 seconds a new renewed certificate. He is in a loop and will not stop. The logs tell me, that the certificates are at least 24h valid, he does not recognize them.

I can see, that he is creating new certificates on the disk.

### Additional context
It only happens on some of the daemons.

A restart of the daemon does not solve the issue. I solved the issue by removing all certificates and keys. I then restarted the daemon (running within NSSM).

Additionally, I am using the `--exec` option to have a hook after the certificate was renewed.

**Comment by dopey** [comment]
Hey @hostops are you in a position to test against the master build of `step` cli? I can push a release candidate if that makes it easier for you to download and try it. Looking to get some feedback on our fix.

**Comment by hostops** [comment]
It is quite difficult to test since this behavior is not consistent and very rare due to long lifetime of our certificates.
If you can make a new release, I will be happy to use it, but I cannot promise you results sooner than in half a year.
Oh, and also in our case, restart of the daemon solves the issue.

**Comment by dopey** [comment]
No problem. We'll get a new release out in the next week or so. Interesting that a restart solves it though. Guess we'll have to wait a little while to know if it works for you.

**Comment by mxzinke** [comment]
I tested a bit and with the flag `--renew-period=24h` or `--expires-in=24h` flag set, it both renewed in a loop:
```
INFO: 2021/08/24 18:25:15 first renewal in 0s
INFO: 2021/08/24 18:25:15 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:15 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:15 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:15 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:15 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:16 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:16 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:16 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:16 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:16 234.test.**********.de certificate renewed, next in 0s
INFO: 2021/08/24 18:25:16 234.test.**********.de certificate renewed, next in 0s
```

Maybe that helps. Waiting for the next release!

**Comment by mxzinke** [comment]
I am now running version 0.17.1 for a while and so far I couldn't reproduce it.

**Comment by dopey** [comment]
I am going to close this as _hopefully_ fixed. But please reopen or comment if a similar issue comes up again.
