### ISSUE TITLE
When building step cli locally, `make bootstrap` tries to install golangci-lint in `/bin/` (and fails)

### ISSUE THREAD

**Issue by aaribaud** [smallstep/cli#535]
### Subject of the issue
When building step cli locally, `make bootstrap` tries to install golangci-lint in `/bin/` (and fails)

### Your environment
* OS - **Debian**
* Version - **11 (Bullseye)**

### Steps to reproduce
* Install Debian Bullseye (e.g. in a VM). Make sure `git` and `golang` are installed (using `apt` if necessary).
* Clone the step cli repository under go/src/github/smallstep/cli as indicated in `docs/local-development.md`
* Run `make bootstrap` to install `golangci-lint` (normally in `${HOME}/go/bin/`)

### Expected behaviour
`make bootstrap` should install `golangci-lint` in the `${HOME}/go//bin/` (user) directory (built on GOPATH) 

### Actual behaviour
`make bootstrap` attempts to install `golangci-lint` in the `/bin/` (system) directory (and fails, of course)

### Additional context
Analysis of make/common.mk shows a call to `$(go env GOPATH)`, which is interpreted as a *Make* construct rather than the *Bash* construct it is probably intended to be. If a `$` sign is prepended (i.e., `$$(go env GOPATH)`), then `make bootstrap` correctly installs `golangci-lint` under `${HOME}/go/bin/`.

**Comment by aaribaud** [comment]
If this issue is confirmed, I can make a PR for it.

**Comment by dopey** [comment]
Hey @aaribaud thanks for opening the issue. This is surprising to me since all of our CI/CD runs on ubuntu latest and we don't have any issue there with `make bootstrap`. Do you have a sense of why you're seeing this behavior on your distro, but we don't see it on others?

**Comment by maraino** [comment]
@aaribaud I think you're right, the command should have `$$`. 
What I'm not sure @dopey if this will break CI/CD. It will if `$GOPATH/bin` is not in the path.

**Comment by maraino** [comment]
@dopey in any case CI/CD should probably use the GitHub action instead of this...

**Comment by dopey** [comment]
CI/CD is already using the action so @aaribaud go ahead with the PR and we'll merge it in.
