### ISSUE TITLE
`ca init --dns=csv` validated as single DNS name, not a CSV of them

### ISSUE THREAD

**Issue by labichn** [smallstep/cli#537]
### Subject of the issue
The value passed to the `--dns` flag of `step ca init` is validated incorrectly.

The issue seems to be [here][init.go#L372]. The `ui.DNS()` [validator][validators.go#L46] tests for a single DNS name, not a CSV of them.

### Your environment
* OS - Arch Linux
* Version - Smallstep CLI/0.16.1 (linux/amd64) Release Date: 2021-07-12

### Steps to reproduce
```bash
$ step ca init --dns=[::1] --address=:443 --name=ca --provisioner=jwk --password-file=<(echo foo)
# Works fine
$ step ca init --dns=localhost,127.0.0.1 ...
# Works because 'localhost,127.0.0.1' is a valid host per https://pkg.go.dev/net#SplitHostPort
$ step ca init --dns=localhost,127.0.0.1,[::1] ...
localhost,127.0.0.1,[::1] is not a valid DNS name
```

### Expected behaviour
The third command should continue without error and lead to the expected `ca.json:dnsNames`:
 ```bash
$ step ca init --dns=localhost,127.0.0.1,[::1] --address=:443 --name=ca --provisioner=jwk --password-file=<(echo foo)
$ jq .dnsNames $STEPPATH/config/ca.json
[
    "localhost",
    "127.0.0.1",
    "[::1]"
]
```

### Actual behaviour
The validation error `localhost,127.0.0.1,[::1] is not a valid DNS name` is printed to stderr.

[init.go#L372]: https://github.com/smallstep/cli/blob/master/command/ca/init.go#L372
[validators.go#L46]: https://github.com/smallstep/cli/blob/master/ui/validators.go#L46

**Comment by tashian** [comment]
Hi @dopey I just added a branch on smallstep/certificates to have the docker entrypoint script pass multiple `--dns` values. Once you have a fix here I can test it out.
