### ISSUE TITLE
Add ACME support for letsencrypt to command line

### ISSUE THREAD

**Issue by sourishkrout** [smallstep/cli#55]
Provide CLI subcommand to launch a web server that will successfully respond to ACME's HTTP challenge and obtains web-PKI certs for nginx, apache, or any other server that ones to run over TLS.

**Comment by dopey** [comment]
[step-ca](github.com/smallstep/certificates) supports ACME and the cli has functionality to act as an ACME client. The spirit of the issue has been accomplished so we'll call this 'done'.
