### ISSUE TITLE
`ssh certificate` password file handling is broken

### ISSUE THREAD

**Issue by labichn** [smallstep/cli#552]
### Subject of the issue
Commit ea26436d93a43a59da38b32fbe857d269ce4ce81 seems to have broken how `ssh certificate` handles password files. These errors can be reproduced in the latest master.

See the Steps to reproduce below for errors that occur when (1) no password files are provided, (2) the provisioner password file is provided, and (3) both the provisioner password file and the CA/SSH key password file are provided. (3) is technically a feature request, see Additional context for details.

### Your environment
* OS - Arch Linux
* Bad commit - ea26436d93a43a59da38b32fbe857d269ce4ce81
* Good commit - f7c25aa39dd7f8bdc9b534f364d82424b561f66a

### Steps to reproduce

```bash
$ PASS_JWK=jwk
$ PASS_KEY=key
$ export STEPPATH=$(mktemp -d)
$ git checkout ea26436d93a43a59da38b32fbe857d269ce4ce81
$ make build
$ ./bin/step ca init \
    --ssh \
    --dns localhost,127.0.0.1 \
    --address=:443 \
    --name=ca \
    --provisioner=jwk \
    --provisioner-password-file=<(echo $PASS_JWK) \
    --password-file=<(echo $PASS_KEY)
#
# 1. Should create keypair and certificate interactively, errors instead:
$ ./bin/step ssh certificate foo ssh_host_ecdsa_key \
    --host --offline --insecure --no-password
error reading : open  failed: no such file or directory
#
# 2. Should create keypair and certificate after entering the CA/SSH key
#    password 3 times, errors instead:
$ ./bin/step ssh certificate foo ssh_host_ecdsa_key \
    --host --offline --insecure --no-password \
    --provisioner jwk \
    --provisioner-password-file <(echo $PASS_JWK)
badger 2021/09/26 20:39:49 INFO: All 0 tables opened in 0s
badger 2021/09/26 20:39:49 INFO: Replaying file id: 0 at offset: 0
badger 2021/09/26 20:39:49 INFO: Replay took: 328.71µs
error decrypting /tmp/tmp.Wf7wE6uHIG/secrets/intermediate_ca_key: x509: decryption password incorrect
#
# 3. This error is the expected behavior:
$ ./bin/step ssh certificate foo ssh_host_ecdsa_key \
    --host --offline --insecure --no-password \
    --provisioner jwk \
    --provisioner-password-file <(echo $PASS_JWK) \
    --password-file <(echo $PASS_KEY)
flag '--no-password' is incompatible with '--password-file'
```

### Expected behaviour

Commands (1) and (2) should create a host SSH keypair and certificate (last working commit is f7c25aa39dd7f8bdc9b534f364d82424b561f66a).

Command (3) throws the error `flag '--no-password' is incompatible with '--password-file'`.

### Actual behaviour

Commands (1) and (2) throw errors.

Command (3) has the expected behavior: it throws the error `flag '--no-password' is incompatible with '--password-file'`.

### Additional context

Command (3) throws the error `flag '--no-password' is incompatible with '--password-file'` because for the command `ssh certificate` the flag `--password-file` accepts the password used to encrypt the generated SSH key, not the CA/SSH key password like the commands `ca init` and `ca token`.

It would be nice to have a way to provide the CA/SSH key password with command `ssh certificate` when invoked `--offline`, either with the `--password-file` flag or some other flag. I'm glad to submit (3) as an enhancement request if you'd prefer.

**Comment by dopey** [comment]
Hey @labichn , thanks for opening the issue!

I think #553 addresses (1) and (2), but not (3). Unfortunately, we have a case of overloading a single term. We've used `password-file` too liberally and now we have conflicting methods in different commands. 

We'll have to figure out what to do here. @maraino has suggested allowing users to set the passwords for all the CA keys (x509 and SSH signing keys) in the ca.json - rather than trying to cover all those keys with flags. I think this solution would be ok, since these passwords would only be required for the `offline` use case. Any thoughts there?

**Comment by maraino** [comment]
Once we release a `step` with @dopey fix, you can do this
```shell
step ssh certificate --offline \
--token $(step ca token --ssh --offline --provisioner jwk --provisioner-password-file <(echo $PASS) mariano) \
--insecure --no-password mariano mariano
```

**Comment by labichn** [comment]
Hey @dopey, I can confirm that max/remove-ssh-pass-hack fixes (1) and (2), thanks!

@maraino's idea to add the password/password-file for the CA keys into ca.json would solve my offline use-case (3). It'd be ideal if ca.json could specify a password-file that expands environment variables in the path (like systemd's ${CREDENTIALS_DIRECTORY}).

@maraino, I still need to enter the CA/SSH key password 3 times while generating the certificate with `ssh certificate --offline --token`. I also get the following error after entering the password. Am I doing something wrong?

```bash
# On max/remove-ssh-pass-hack
$ STEPDEBUG=1 \
  ./bin/step ssh certificate mariano mariano \
    --offline --insecure --no-password \
    --token $(./bin/step ca token mariano \
                --ssh --offline \
                --provisioner jwk \
                --provisioner-password-file <(echo $PASS_JWK) \
                --password-file <(echo $PASS_KEY))
badger 2021/09/27 19:05:42 INFO: All 0 tables opened in 0s
badger 2021/09/27 19:05:42 INFO: Replaying file id: 0 at offset: 0
badger 2021/09/27 19:05:42 INFO: Replay took: 615.086µs
✔ Provisioner: jwk (JWK) [kid: Fj1IYqUxdtCu57b4BvzboOo5FTDX9xCsZeCCIuyFJgo]
badger 2021/09/27 19:05:42 INFO: All 0 tables opened in 0s
badger 2021/09/27 19:05:42 INFO: Replaying file id: 0 at offset: 0
badger 2021/09/27 19:05:42 INFO: Replay took: 613.919µs
Please enter the password to decrypt /tmp/tmp.Wf7wE6uHIG/secrets/intermediate_ca_key:
Please enter the password to decrypt /tmp/tmp.Wf7wE6uHIG/secrets/ssh_host_ca_key: █
Please enter the password to decrypt /tmp/tmp.Wf7wE6uHIG/secrets/ssh_user_ca_key:
authority.authorizeToken: token issued before the bootstrap of certificate authority
authority.authorizeSSHSign
github.com/smallstep/certificates/errs.Wrap
	/home/nick/go/pkg/mod/github.com/smallstep/certificates@v0.17.3/errs/error.go:103
github.com/smallstep/certificates/authority.(*Authority).authorizeSSHSign
	/home/nick/go/pkg/mod/github.com/smallstep/certificates@v0.17.3/authority/authorize.go:335
github.com/smallstep/certificates/authority.(*Authority).Authorize
	/home/nick/go/pkg/mod/github.com/smallstep/certificates@v0.17.3/authority/authorize.go:213
github.com/smallstep/cli/utils/cautils.(*OfflineCA).SSHSign
	/home/nick/code/ext/cli/utils/cautils/offline.go:315
github.com/smallstep/cli/command/ssh.certificateAction
	/home/nick/code/ext/cli/command/ssh/certificate.go:387
github.com/smallstep/cli/command.ActionFunc.func1
	/home/nick/code/ext/cli/command/command.go:48
github.com/urfave/cli.HandleAction
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:522
github.com/urfave/cli.Command.Run
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).RunAsSubcommand
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405
github.com/urfave/cli.Command.startApp
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372
github.com/urfave/cli.Command.Run
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102
github.com/urfave/cli.(*App).Run
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
	/home/nick/code/ext/cli/cmd/step/main.go:99
runtime.main
	/usr/lib/go/src/runtime/proc.go:255
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1581
authority.Authorize
github.com/smallstep/certificates/errs.Wrap
	/home/nick/go/pkg/mod/github.com/smallstep/certificates@v0.17.3/errs/error.go:103
github.com/smallstep/certificates/authority.(*Authority).Authorize
	/home/nick/go/pkg/mod/github.com/smallstep/certificates@v0.17.3/authority/authorize.go:214
github.com/smallstep/cli/utils/cautils.(*OfflineCA).SSHSign
	/home/nick/code/ext/cli/utils/cautils/offline.go:315
github.com/smallstep/cli/command/ssh.certificateAction
	/home/nick/code/ext/cli/command/ssh/certificate.go:387
github.com/smallstep/cli/command.ActionFunc.func1
	/home/nick/code/ext/cli/command/command.go:48
github.com/urfave/cli.HandleAction
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:522
github.com/urfave/cli.Command.Run
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173
github.com/urfave/cli.(*App).RunAsSubcommand
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405
github.com/urfave/cli.Command.startApp
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372
github.com/urfave/cli.Command.Run
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102
github.com/urfave/cli.(*App).Run
	/home/nick/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277
main.main
	/home/nick/code/ext/cli/cmd/step/main.go:99
runtime.main
	/usr/lib/go/src/runtime/proc.go:255
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1581

The request lacked necessary authorization to be completed. Please see the certificate authority logs for more info.
```

**Comment by dopey** [comment]
Hey @labichn I spoke with mariano and we agree that using the `step ca token` command from within `step ssh certificate` is unnecessary. Doing it the way you did originally is preferred. 

But to close the loop on the error you're seeing, that's because the token that was generated before the CA had started up, which will always be the case if you're using `offline` mode and calling `step ca token` as a subprocess. To avoid these errors you could add `disableIssuedAtCheck: true,` under the `authority` attribute in your ca.json.

However, rather than doing the above, you should use `step ssh certificate` as you did in your original issue statement (without trying to pass the the token - and, instead creating one as part of the command).

**Comment by labichn** [comment]
> To avoid these errors you could add disableIssuedAtCheck: true, under the authority attribute in your ca.json.

:pray: This was going to be my next bug report, thanks for this info! This'll let me make a ready-to-deploy image with a token baked in, rather than having to generate the host SSH keypair on the image build machine.

Using the token with `disableIssuedAtCheck: true` worked like a charm, but I still needed to enter the CA/SSH key password 3 times during SSH certificate creation. I'm looking forward to being able to configure a `password-file` in ca.json to have this working 100% `offline`. Thanks so much for your prompt responses.

**Comment by dopey** [comment]
Now that #553 is closed, I'm going to mark this issue as closed and open another for having passwords for CA,SSH keys in the ca.json file. Please let me know if that's not quite right, and we can reopen this one.
