### ISSUE TITLE
Let's Encrypt: Unable to validate challenge

### ISSUE THREAD

**Issue by isodude** [smallstep/cli#567]
### Subject of the issue
I'm unable to issue certificates towards Let's Encrypt, my own CA works flawless.

### Your environment
* OS - CentOS 6/CentOS 7
* Version - 2021-10-16

### Steps to reproduce
step ca certificate --force --contact mailto:$email --webroot /var/www/html --acme https://acme-v02.api.letsencrypt.org/directory --san $HOSTNAME $HOSTNAME fullchain.pem privkey.pem

### Expected behaviour
Certificate was successfully validated

### Actual behaviour
Using Webroot Mode HTTP challenge to validate $HOSTNAME ........... Error!
Unable to validate challenge: &{ID: AccountID: AuthorizationID: Value: Type:http-01 Status:pending Token:$TOKEN ValidatedAt: URL:https://acme-v02.api.letsencrypt.org/acme/chall-v3/$CHALLANGE Error:<nil>}

### Additional context
I cUrled towards the URL and it shows
```
{
  "type": "http-01",
  "status": "valid",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/$CHALLANGE",
  "token": "$TOKEN",
  "validationRecord": [
    {
      "url": "http://$HOSTNAME/.well-known/acme-challenge/$ACMECHALLENGE",
      "hostname": "$HOSTNAME",
      "port": "80",
      "addressesResolved": [
        "$IPADDRESS"
      ],
      "addressUsed": "$IPADDRESS"
    }
  ],
  "validated": "2021-10-18T11:57:34Z"
}
```

During strace in seems that
* Let's encrypt promptly catches the acme-challenge without trouble
* step only tries _once_ to get the ValidatedAt URL.

**Comment by isodude** [comment]
Yup, it is running and answering the request.
________________________________

**Comment by dopey** [comment]
Hey @isodude, I'm unable to reproduce: 

```
max@ip-172-31-3-165:~$ step ca certificate --force --contact mailto:max@smallstep.com --webroot /tmp/acme-html --acme https://acme-staging-v02.api.letsencrypt.org/directory --san max-acme-test.step.toys max-acme-test.step.toys localhost.crt localhost.key
Using Webroot Mode HTTP challenge to validate max-acme-test.step.toys .. done!
Waiting for Order to be 'ready' for finalization .. done!
Finalizing Order .. done!
✔ Certificate: localhost.crt
✔ Private Key: localhost.key
```

Is it possible your `/var/www/html` server is not publicly routable?

**Comment by isodude** [comment]
It actually got it working, once. Other acme-clients like certbot does not have a problem. Step does not have a problem if I'm running towards my own CA.

The odd thing is that it fetches the validateat-url at a state where it is pending, but before it times out the validation goes through without step fetching it again.
