### ISSUE TITLE
`step ca renew --daemon` does not exit when certificate expires

### ISSUE THREAD

**Issue by rvichery** [smallstep/cli#573]
### Subject of the issue
When executing `step ca renew --daemon`, I am expecting the daemon to fail if the certificate expires while the daemon is running. This happened during one of our CA outage where the cert expired before the CA was back up and running.

### Your environment
* OS - Debian 10
* Version - Smallstep CLI/0.16.0 (linux/amd64) - Release Date: 2021-07-09 00:24 UTC

### Steps to reproduce
1- Issue a certificate valid for N hours
2- Start `step ca renew --daemon` to renew that certificate
3- Stop the CA server for more than N hours
4- `step ca renew --daemon` will not exit and keep running

### Expected behaviour
When the certificate is expired, I am guessing that `step ca renew` won't be able to recover and as such the process should be exited.

### Actual behaviour
`step ca renew` keeps running even though it will never be able to renew the certificate.

**Comment by mmalone** [comment]
When we implement renew after expiry (https://github.com/smallstep/certificates/issues/177) I think we'll actually _want_ `step ca certificate --daemon` to continue retrying after expiration, that way you can mark an expired certificate as renewable, and your running daemons will pick up a new cert.

**Comment by rvichery** [comment]
@mmalone thanks for the explanation. Makes sense once smallstep/certificates#177 is implemented. Until it is implemented we will then switch to using a crontab with a re-issuer script instead of `--daemon` mode.
