### ISSUE TITLE
PKCS#11 key support for certificate create and certificate sign

### ISSUE THREAD

**Issue by hongkongkiwi** [smallstep/cli#583]
I would like to use private keys stored in PKCS11 keystores for clients to use `step certificate create`, `step certificate sign`. 

I don't think that `step ca init` is required as we have another separate app for that at the moment and it's only used one time.

An example usage for create would be be: 
`step certificate create --csr --key "pkcs11:mykey" "mysubject" cert.csr`

As per the docs, passing -key means the key shouldn't be created, only used from the pkcs11 store.

The reason for this change is so that private keys do not touch the filesystem at all, it would vastly increase the utility of the step certificate cli command most especially step create as we can create csr from secure keys.

For PKCS11 support using this [aws kms pkcs11 aws plugin](https://github.com/JackOfMostTrades/aws-kms-pkcs11) to allow me to use private keys hosted in KMS on the local system. Alternatively, if the step create command could support directly using KMS keys that would also be useful.... e.g.
-key "awskms:<myid>".

**Comment by maraino** [comment]
This will be part of the project to support KMS (awskms, azurekms (key vault), cloudkms, pkcs11, yubikey, and perhaps with the ssh-agent). As I said in [here](https://github.com/smallstep/cli/issues/517#issuecomment-969242841) until that is done, the `step-*-init` can be useful.

Note that azurekms is now implemented `step ca init` that is why we don't have `step-azurekms-init`

**Comment by gdbelvin** [comment]
Any update on this? 
I would like to create an RSA key via PCKS11 for scep. Currently step-pkcs11-init does not support RSA keys.

**Comment by maraino** [comment]
@gdbelvin no updates on this, but you should be able to create RSA keys changing the `SignatureAlgorithm` to something like `SHA256WithRSA`, and adding the desired `Bits` in the calls to [CreateKeyRequest](https://pkg.go.dev/github.com/smallstep/certificates@v0.20.0/kms/apiv1#CreateKeyRequest)

Let me know if that doesn't work.

**Comment by maraino** [comment]
Hi @hongkongkiwi, I released last month https://github.com/smallstep/step-kms-plugin. This plugin works with the latest version in master and allows you to use `step certificate create` and `step certificate sign` to sign certificates using PKCS#11, as well as other supported KMSs. You can see how to use it in the [README.md](https://github.com/smallstep/step-kms-plugin#readme)
