### ISSUE TITLE
Add an option to `step ca certificate` that would return the full chain (including) root in the .crt result.

### ISSUE THREAD

**Issue by dopey** [smallstep/cli#584]
This would save users time and headache from having to concatenate their own chains and possibly making errors in the process.

**Comment by maraino** [comment]
Doing two requests? Or adding the root to the response?

By the way, the response from step-ca has the deprecated `"crt"` (server certificate) and `"ca"` (intermediate) parameters.

**Comment by dopey** [comment]
> Doing two requests? Or adding the root to the response?

Open to discussion.

**Comment by gdbelvin** [comment]
I'm not sure the root should be included. The use case here is to generate a certificate file that is suitable for use by the host webserver. Typically these files contain the full certificate chain, excluding the root, so that clients can validate the certificate against their local root store.
