### ISSUE TITLE
Support installation of self-signed root certs into your local trust store

### ISSUE THREAD

**Issue by sourishkrout** [smallstep/cli#59]

**Comment by dopey** [comment]
Added a feature to `step` that allows installing and uninstalling certificates from a local truststore. Adding internal PKI root certificates to your local truststore allows users to browse internal admin sites without warnings from the browser and enables local integration testing.

```
step certificate install root-ca.crt
```

We've also added an option to install the root certificate to the system truststore when bootstrapping a development environment from the `step` Certificate Authority:

```
step ca bootstrap --install
```
