### ISSUE TITLE
certificate topic

### ISSUE THREAD

**Issue by 89z** [smallstep/cli#592]
### What would you like to be added

The word `certificate` should be added to the description or topics, so that people searching for `certificate` will find this repo.

### Why this is needed

Currently if you search for `certificate language:go`, you wont find this repo, as that word is not in the description or topics. This is bad, because this tool can create self-signed certificates, and other features.

https://github.com/smallstep/cli#features

**Comment by maraino** [comment]
Thanks @89z, I've just added

**Comment by 89z** [comment]
Thank you!
