### ISSUE TITLE
step completion sub-command

### ISSUE THREAD

**Issue by ooraini** [smallstep/cli#622]
### What would you like to be added
It's common to see the sub-command `completion` followed by the shell's name to generate the completion script to standard out. The user can redirect the output to the appropriate file for their shell.

The output of `step completion bash` would be the same as:
[https://github.com/smallstep/cli/blob/master/autocomplete/bash_autocomplete](https://github.com/smallstep/cli/blob/master/autocomplete/bash_autocomplete)
But without the shebang.

### Why this is needed
I think it's better UX for the user. When I try to install a completion for any tool, the first place I would look for is the `completion` sub-command.

And for people who like to automate the installations of their favorite CLIs, it's very convenient in scripts.

**Comment by dopey** [comment]
Hey @ooraini thanks for opening the issue! Sounds like a great idea and we would definitely appreciate such a contribution.

If anyone from the community is looking for guidance on how to get started, let us know and we'll point you in the right direction.

Cheers 🍻
