### ISSUE TITLE
step ca revoke provisioner argument

### ISSUE THREAD

**Issue by amalaguti** [smallstep/cli#641]
### What would you like to be added
when doing `step ca revoke serial_number` the provisioner information is asked to the user.
Why there is no option to pass the provisioner ? Like --provisioner ?

### Why this is needed
To automate cert revocation using cert serial number

**Comment by dopey** [comment]
Hey @amalaguti thanks for opening the issue! We agree with you. Before I respond to the issue, I'm going let me recommend a workaround. 

`step ca revoke` takes a token argument. So you can generate a token doing `step ca token --revoke <serial>` and then use that token in `step ca revoke --token <token>`.

Now, about adding a provisioner flag. We can do that .. but it's a little complicated. You'll probably want a flag to authenticate to that provisioner as well. For JWK provisioners that's `--password-file` or `--provisioner-password-file`. For X5C provisioners thats `--x5c-cert` and `x5c-key`. For K8SSA provisioners that's another flag. Etc. You get the point. Basically, we're not sure we want to implement all the possible flags when an alternative command (`step ca token`) already exists and serves this function better.

Practically, `--provisioner` and `--password-file` would be the most popular (we think), and if someone from the community wanted to send us a PR adding those, we would probably accept it. 

The main problem with adding a `--provisioner`

**Comment by amalaguti** [comment]
@dopey Hi Max, thanks for your recommended workaround, that helps a lot, 
in fact I had tried it but in my rush I put the arguments in bad order and got a `not enough positional arguments were provided in 'step ca token <subject>'`, and that made me think that it was not possible to automate it and lead me to open this issue

Now I tried paying more attention and got it working as you suggested using the token, which allows me to automate it.
` step ca token \
>   --provisioner="OpenVPN Client" \
>   --password-file=REDACTED \
>   --revoke "338973696275802951633129079530789925664"`

Thanks a lot for the quick response.

**Comment by dopey** [comment]
I'm going to close this issue for now. cheers 🍻
