### ISSUE TITLE
Add build for arm7l

### ISSUE THREAD

**Issue by FallingSnow** [smallstep/cli#656]
I'd like to be able to run step on my router but it has an `arm7l` architecture. However trying to run the `arm7` build from the releases page I get `Illegal instruction`.

```
# uname -a
Linux DD-WRT R6300 4.4.302 #5348 SMP Sat Feb 26 10:44:06 +07 2022 armv7l DD-WRT
# tar -xf step_linux_0.18.2_armv7.tar
# cd step_0.18.2/bin
# ./step
Illegal instruction
```

**Comment by tashian** [comment]
Hi @FallingSnow, thanks for reporting this.

Have you tried the arm5 or arm6 binaries?
One of those might work.
I'm not sure how we would build directly for `arm7l` in Go.
The [Go docs for `$GOOS`, `$GOARCH`, and `$GOARM`](https://go.dev/doc/install/source#environment) don't seem to list this arch as an option.

**Comment by FallingSnow** [comment]
I have tried arm6 binaries with the same result.
I did a little searching too. Compiling arm7l  with Go doesn't seem straightforward. Not really sure how to proceed, might just use a different machine.
Gonna close for now unless I make any progress.

**Comment by FallingSnow** [comment]
I tried armv5 binary. Seems to be working. Thanks!
