### ISSUE TITLE
step ca bootstrap  - does not work when smallstep CA runs on port 443 (root user account)

### ISSUE THREAD

**Issue by deskpil0t** [smallstep/cli#678]
### ca bootstrap - error downloading root certificate: json: cannot unmarshal number into Go value of type errs.ErrorResponse

When the smallstep ca.json is set to use port :443 I get the above error (as root user)
When the smallstep ca.json is set to use port :443 I do not get the abover error (as root user)
When the smallstep ca.json is set to use port :1443 I do not get the abover error (as step user)

(Remote machine for bootstrapping)
sudo step ca bootstrap --ca-url "https://10.1.1.2" --fingerprint abc1234xxxx
error downloading root certificate: json: cannot unmarshal number into Go value of type errs.ErrorResponse

sudo step ca bootstrap --ca-url "https://10.1.1.2:443" --fingerprint abc1234xxxx
error downloading root certificate: json: cannot unmarshal number into Go value of type errs.ErrorResponse

sudo step ca bootstrap --ca-url "https://10.1.1.2:444" --fingerprint abc1234xxxx
-Would you like to overwrite /root/.step/certs/root_ca.crt [y/n]: y
The root certificate has been saved in /root/.step/certs/root_ca.crt.
- Would you like to overwrite /root/.step/config/defaults.json [y/n]: y
The authority configuration has been saved in /root/.step/config/defaults.json.

### Your environment
* OS - Ubuntu 
* Version -  Linux rpi4a 5.4.0-1059-raspi #67-Ubuntu SMP PREEMPT Mon Apr 11 14:16:01 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Steps to reproduce (on CA server)
Install Go go1.18.2.linux-arm64.tar.gz
Install step  Smallstep CLI/0.19.0 (linux/arm64) Release Date: 2022-04-19T23:08:30Z
Install step-ca Smallstep CA/0.19.0 (linux/arm64) Release Date: 2022-04-19T23:42:03Z

/etc/profile
export PATH=$PATH:/usr/local/go/bin
export STEPPATH=/etc/step-ca

Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

sudo su -
mkdir /etc/step-ca
step ca init --ssh

chose standalone
pki: Smallstep
dns names:  10.1.1.2
port:  :443
1st prov:  bob@smallstep.com
password: 1234567890

step-ca /etc/step-ca/config/ca.json --password-file ./password.txt&

##
root@rpi4b:/etc/step-ca# badger 2022/05/11 15:22:35 INFO: All 0 tables opened in 0s
2022/05/11 15:22:35 Starting Smallstep CA/0.19.0 (linux/arm64)
2022/05/11 15:22:35 Documentation: https://u.step.sm/docs/ca
2022/05/11 15:22:35 Community Discord: https://u.step.sm/discord
2022/05/11 15:22:35 Config file: /etc/step-ca/config/ca.json
2022/05/11 15:22:35 The primary server URL is https://10.1.1.2:443
2022/05/11 15:22:35 Root certificates are available at https://10.1.1.2:443/roots.pem
2022/05/11 15:22:35 X.509 Root Fingerprint: 7d275b11b21ee24781b05b07d820b54d72c73db48236d2f017364f36e8cf8240
2022/05/11 15:22:35 SSH Host CA Key is ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLrNH7Gs5TP97Th2QUo/fb399sDproBkIiSILx8+DIdOfuSCisAGHxBBBz5fEaXEPtfauaTDPcBLKPR/ORpY3b4=

2022/05/11 15:22:35 SSH User CA Key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJaj/87lgdD8dr5NSxtjAD15RYw78wHrX8VQsM5XdNXGEUWv3x200rvvswPiTdTHng0lKyUy+DmRXtQd41HPgxE=

2022/05/11 15:22:35 Serving HTTPS on :443 ...

### Actual behaviour
Other server (same environment)
root@rpi4a:~# step ca bootstrap --ca-url "https://10.1.1.2" --fingerprint abc1234xxxx
error downloading root certificate: json: cannot unmarshal number into Go value of type errs.ErrorResponse

### Expected behaviour
root@rpi4a:~# step ca bootstrap --ca-url="https://10.1.1.2:444" --fingerprint abc1234xxxx
The root certificate has been saved in /etc/step-ca/certs/root_ca.crt.
The authority configuration has been saved in /etc/step-ca/config/defaults.json.

### Additional context
I tried using the apt version of go as well.
I tried downgrading to a 18.2 release of step and step-ca
I was originally trying to get it to work with NETCAP to bind to port 443, but was having problems, so i just tried a higher number port completely, then tried to just see if i could get it to run as root locally instead of as a service.

I don't know if this is step-cli side issue or a step-server side issue.  The service can run on either 443 or 444 without any problem.

**Comment by maraino** [comment]
Hi @deskpil0t, do you see any errors on the CA?

And what do you see if you try:
```
curl -k https://10.1.1.2/root/7d275b11b21ee24781b05b07d820b54d72c73db48236d2f017364f36e8cf8240
```

**Comment by deskpil0t** [comment]
to answer your question:
when runing on port 443:  I get a 404 not found
when running on port 444: I get a public key
 (details and comparison can be found in the troubleshooting log files and comparison).  


based on your command i did some curl with verbose debugging.  It appears that 
when i run it as port 443 smallstep/certificates returns:

 Server certificate:
*  subject: CN=TRAEFIK DEFAULT CERT
*  start date: May 13 14:51:27 2022 GMT
*  expire date: May 13 14:51:27 2023 GMT
*  issuer: CN=TRAEFIK DEFAULT CERT
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0

when running on port 444 i get:
 Server certificate:
*  subject: CN=Step Online CA
*  start date: May 13 15:05:49 2022 GMT
*  expire date: May 14 15:06:49 2022 GMT
*  issuer: O=Smallstep; CN=Smallstep Intermediate CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

so it looks like it is an error on the smallsteps/certificate side and not the smallstep/step cli side.  Is there a way to move the issue or do i need to make a new issue on the other project.




[443-verbose.txt](https://github.com/smallstep/cli/files/8689019/443-verbose.txt)
[444-verbose.txt](https://github.com/smallstep/cli/files/8689020/444-verbose.txt)
[smallstep-troubleshooting-log.txt](https://github.com/smallstep/cli/files/8689021/smallstep-troubleshooting-log.txt)
[ca.json.txt](https://github.com/smallstep/cli/files/8689022/ca.json.txt)

**Comment by maraino** [comment]
It looks like you're running [`traefik`](https://traefik.io/traefik/) on 443 port and it's the one responding instead of `step-ca`. Our subject, will be always `CN=Step Online CA`, there's a way to change it in the [ca.json](https://github.com/smallstep/certificates/blob/ea084d71fb7b2ab8c2e3fc81e20e84ee49f6cc88/authority/config/config.go#L74), but you're not doing it.

**Comment by deskpil0t** [comment]
at a glance, i would agree with you.  except i have checked and nothing is using port 443 except for smallstep.

**root@rpi4b:~# ps -ef | grep step_ca**
root       11078   10930  0 17:01 pts/1    00:00:00 grep --color=auto step_ca

**root@rpi4b:~# netstat -an | grep :443**<br>

**root@rpi4b:~# step-ca /etc/step-ca/config/ca.json --password-file /etc/step-ca/password.txt &**
[1] 11084

badger 2022/05/13 17:01:40 INFO: All 1 tables opened in 2ms
badger 2022/05/13 17:01:40 INFO: Replaying file id: 0 at offset: 12696
badger 2022/05/13 17:01:40 INFO: Replay took: 11.222µs
2022/05/13 17:01:41 Starting Smallstep CA/0.19.0 (linux/arm64)
2022/05/13 17:01:41 Documentation: https://u.step.sm/docs/ca
2022/05/13 17:01:41 Community Discord: https://u.step.sm/discord
2022/05/13 17:01:41 Config file: /etc/step-ca/config/ca.json
2022/05/13 17:01:41 The primary server URL is https://10.1.1.2:443
2022/05/13 17:01:41 Root certificates are available at https://10.1.1.2:443/roots.pem
2022/05/13 17:01:41 X.509 Root Fingerprint: 7d275b11b21ee24781b05b07d820b54d72c73db48236d2f017364f36e8cf8240
2022/05/13 17:01:41 SSH Host CA Key is ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLrNH7Gs5TP97Th2QUo/fb399sDproBkIiSILx8+DIdOfuSCisAGHxBBBz5fEaXEPtfauaTDPcBLKPR/ORpY3b4=

2022/05/13 17:01:41 SSH User CA Key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJaj/87lgdD8dr5NSxtjAD15RYw78wHrX8VQsM5XdNXGEUWv3x200rvvswPiTdTHng0lKyUy+DmRXtQd41HPgxE=

2022/05/13 17:01:41 Serving HTTPS on :443 ...

**root@rpi4b:~# netstat -tulpn | grep step**
tcp6       0      0 :::443                  :::*                    LISTEN      11084/step-ca

**Comment by maraino** [comment]
> root@rpi4b:~# netstat -tulpn | grep step
tcp6 0 0 :::443 :::* LISTEN 11084/step-ca

Is `step-ca` listening on tcp6 only? You were doing tcp4 requests. And did you grep by 443 instead of just `step`. I'm pretty sure you have traefik there, in a process? in a docker container? in a k8s ingress?

**Comment by deskpil0t** [comment]
I’ll do some more commands.  But It’s a raspberry pi.   I might have played with some minicube stuff in the past but I’m pretty sure I deleted it.   Certainly nothing active  or at the OS level

**Comment by tashian** [comment]
> > root@rpi4b:~# netstat -tulpn | grep step
> > tcp6 0 0 :::443 :::* LISTEN 11084/step-ca
> 
> Is `step-ca` listening on tcp6 only? You were doing tcp4 requests. And did you grep by 443 instead of just `step`. I'm pretty sure you have traefik there, in a process? in a docker container? in a k8s ingress?

@maraino I just looked at `netstat` output in my homelab and it will display `tcp6` for listeners that are bound to both ipv4 and ipv6 addresses, and I think that's what's happening here because their step-ca log output shows "Serving HTTPS on :443 ..."

Not sure what is going on here exactly. It seems like a local config issue, but that's just my hunch.

**Comment by deskpil0t** [comment]
This was a user environment issue.  pebcak  or (ID10T).  After formatting the device and rebuilding the operating system.  Everything works as it shoud.  I am sorry for bothering everyone.

**Comment by mikeschinkel** [comment]
@deskpil0t — I am running into the same issue however my Step CA is a Docker container running in Portainer which is also running Traefik via a Docker container.  I know it has been a year since the issue, but do you happen to remember the exact problem or possibly how you configured it?  I've tried rebuilding my setup but to no avail.

Thank you in advance for any help you can provide.

**Comment by mikeschinkel** [comment]
I was able to solve this issue myself.  I got the error when using:

```
step ca bootstrap --ca-url https://step-ca.local --install --fingerprint <my_ca_fingerprint>
```
But when I added port `9000` it worked:

```
step ca bootstrap --ca-url https://step-ca.local:9000 --install --fingerprint <my_ca_fingerprint>
```

So mine too was a pebcak / (`ID10T`) error. 😬
