### ISSUE TITLE
Offline mode doesn't work with `--password-file`

### ISSUE THREAD

**Issue by hslatman** [smallstep/cli#679]
### Subject of the issue
When using the offline mode for signing certificates (and potentially other operations performed using `--offline`) the `--password-file` flag is not accepted.

### Steps to reproduce

```console
step ca certificate name name.crt name.key --ca-config /path/to/ca.json --provisioner-password-file=provisioner-pass.txt --offline --password-file /path/to/intermediate/pass.txt
```

### Expected behaviour
The certificate is created without prompting for a password

### Actual behaviour
An error is shown stating too many arguments for the command, meaning the `--password-file` flag is not parsed as one.

### Additional context
It seems most of the logic already exists for handling the `--password-file` flag. The flag itself is not added to (all) commands that could make use of it, resulting in it not being parsed nor used as such. 

A quick trial adding the `PasswordFile` flag to the flags available to the `step ca certificate` command resulted in the flag being parsed and used and thus did _not_ result in a prompt for the password.

**Comment by dopey** [comment]
We added the `--password-file` flag for `step ca [sign|certificate]`. #680
