### ISSUE TITLE
Add a command to extract keys from certificates and CSRs

### ISSUE THREAD

**Issue by maraino** [smallstep/cli#68]
### Description
Add a command to extract the public keys from certificate and certificate signing requests.

Related to #67

**Comment by dopey** [comment]
Added the `key` subcommand under `step certificate` for extracting public keys from certificates.

```
bin/step certificate key foo.crt
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEm/qCb5HP4TZ2B5bS6twBOMkqOCMQ
ZsrADFyr/QXaWnItnsXFiFzEExTTdF11MhBVFztE5hVLp33JBNFgmQxoRw==
-----END PUBLIC KEY-----
```

Added the ability to use certificates in place of public keys on the command line (where public keys are required). A common use case for this flexibility can be found in the `step crypto` subcommands where you may need to provide a public key to verify a signature but the public key is stored as an X509 Certificate.
