### ISSUE TITLE
Command line alternative to use --provisioner keycloak

### ISSUE THREAD

**Issue by GuidoBrugnara** [smallstep/cli#685]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Why is this needed?

Using this command:
`step ssh login 'MyLogin' --provisioner keycloak 
`
it is necessary to run the command from a GUI because a browser is opened from which authentication is requested.

Is there a command-line alternative?

**Comment by maraino** [comment]
Currently, any supported OIDC flow always requires user authentication through the web. Even the oob, which will be replaced with the device_code flow, will require signing in using a browser. 

However, there might be ways with some idPs to get an OIDC token and pass it using the `--token` flag, either using `curl` or `step oauth` or a script like [this](https://stackoverflow.com/a/54110718), I haven't tried that. Another option would be using OIDC with service accounts, it is not supported but it might work.

Alternatively, you can always use a different provisioner that doesn't have that limitation, but it might have others.

**Comment by dopey** [comment]
Related Issue: #675

**Comment by GuidoBrugnara** [comment]
Very interesting, thank you.
