### ISSUE TITLE
Allow to use certificates as key parameters

### ISSUE THREAD

**Issue by maraino** [smallstep/cli#69]
### Description 
Some commands like `step crypto jwt verify` should accept certificates as `--key` parameters, we can easily extract a public key from it and verify the JWT.

Related to #67

**Comment by dopey** [comment]
Added the ability to use certificates in place of public keys on the command line (where public keys are required). A common use case for this flexibility can be found in the `step crypto` subcommands where you may need to provide a public key to verify a signature but the public key is stored as an X509 Certificate.
