### ISSUE TITLE
[Bug]: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by ryanc-me** [smallstep/cli#703]
### Steps to Reproduce

 * Configure an OAUTH/OIDC provisioner (e.g. Outlook)
 * Attemp to SSH into a server

### Your Environment

* OS - Windows 11
* `step` CLI Version - `Smallstep CLI/0.20.0 (windows/amd64), Release Date: 2022-05-26T18:40:14Z`

### Expected Behavior

The SSH login works correctly

### Actual Behavior

The following error:
```bash
PS C:\Users\ryan> ssh some-ssh-server
✔ Provisioner: Outlook (OIDC) [client: xxx]
error listening on localhost:60234: listen tcp 127.0.0.1:60234: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
error running: step oauth --oidc --bare --provider https://login.microsoftonline.com/xxx/v2.0/.well-known/openid-configuration --client-id xxx --client-secret xxx --listen localhost:60234: exit status 1
```

Importantly:
```bash
An attempt was made to access a socket in a way forbidden by its access permissions.
```

### Additional Context

It seems MS recently pushed an update that either:
 1. Enables the `ExcludedPortRange` feature, or
 2. Added some new port ranges to the list

To check, open a PowerShell window and run:
```powershell
PS C:\Users\ryan> netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5357        5357
     50000       50059     *
     52368       52467
     59899       59998
     60052       60151
     60152       60251
     60345       60444
     60505       60604
     60605       60704
     60890       60989
     60990       61089

* - Administered port exclusions.

PS C:\Users\ryan>
```

Apparently, this includes the range step-cli is using for OAUTH/OIDC logins (port `60234` in the error above).

**Temporary fix**

As per [this SO thread](https://superuser.com/questions/1579346/many-excludedportranges-how-to-delete-hyper-v-is-disabled) (run in an admin powershell):
```powershell
reg add HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /d 0 /f
net stop hns
net start hns
```

I'm posting this mainly in case other Windows step-cli users face the same issue. Google results were a mixed bag - there are a lot of older IIS/.NET related SO threads, which weren't overly helpful.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dopey** [comment]
Hey @ryanc-me 👋 Thanks for opening the issue!

What's the output of `step ca provisioner list`? I'm curious if there is a port hardcoded in your OIDC provisioner listenAddress field. Generally, unless you've configured a consistent port, you'll get a different port each time the command is run and the OS is responsible for giving you a port that will not conflict with anything else. 

So, either your operating system is, for some reason, returning random ports that are in an excluded range (shouldn't be happening), or this port (60234) has been configured on your provisioner. Let us know about the provisioner settings, and we'll continue debugging from there.

**Comment by ryanc-me** [comment]
Hey @dopey, thank you for that suggestion! It looks like the port/address is indeed hardcoded in our provisioner config:
```jsonc
{
      "type": "OIDC",
      "name": "Outlook",
      "listenAddress": "localhost:60234",
      // snip
}
```

When I'm back at work tomorrow, I'll try removing the `listenAddress` key and double-check that it's still working.

Unfortunately I can't remember where I got the provisioner config (whether it was from [the docs](https://smallstep.com/docs/step-ca/provisioners#oauthoidc-single-sign-on), or we used `step ca provisioner add`), but I have a feeling this was a mistake on our/my side.

**Comment by dopey** [comment]
It's possible that for some reason, your setup requires a `listenAddress`. I know that Okta requires port 10000. I'm not sure about Outlook. If indeed you must set a `listenAddress`, then hopefully you can change it to one that isn't in an excluded range. If you don't need the port, then removing that listenAddress from the configuration should get you working again :] Let me know!

**Comment by ryanc-me** [comment]
Hi @dopey! Sorry about the delay here.

I've been doing some testing this morning. It looks like Azure AD _only_ allows a redirect URL using the `HTTP` scheme when the address name is exactly `localhost`. It doesn't allow `127.0.0.1`, which is what step-ca uses when I remove the `listenAddress` key. See their docs on it [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#supported-schemes).

Configuring the OIDC in Azure with a redirect URL like `http://localhost` will allow any arbitrary port (so will work with step-ca's auto-port thing), but again, only when the name is `localhost` - [see here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions).

So, it looks like we're stuck with a hardcoded address because of Microsoft's strict rules. 🙃

FWIW, maybe some day there could be a provisioner option to pass `http://localhost:xxxx` instead of `http://127.0.0.1:xxx` as the redirect URL? I'm not sure if there are any security implications there, but it would be very useful for us!

For the short-term, I think we'll switch to a different hardcoded port lower in the range, to avoid those restricted Windows ports.

**Comment by dopey** [comment]
Hey @ryanc-me thanks for the update! Would you mind creating a separate issue to track that feature request? You can link directly back to this issue, or just copy paste this comment for the "Why is this necessary?" question.
