### ISSUE TITLE
How to Install step-cli on RPi Zero 2 W?

### ISSUE THREAD

**Issue by AlexLandherr** [smallstep/cli#711]
I'm trying to install step-cli on a RPi Zero 2 W running Raspberry Pi OS and can't find any instructions for how to do it for my particular Pi.
I already have a working CA on another RPi 4B 2GB.

The RPi Zero 2 W is running an Nginx server with a small test page, I need the certificate from my CA to get HTTPS working.

I find no ARM 32-bit guide at all. Does anyone know how to do this?

**Comment by maraino** [comment]
Raspberry Pi Zero 2 W should support 64-pit OSs too, but if you have a 32-bit OS you will probably need one of these builds:
- [step_linux_0.21.0_armv7.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv7.tar.gz)
- [step_linux_0.21.0_armv6.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv6.tar.gz)
- [step_linux_0.21.0_armv5.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv5.tar.gz)

Can you let us know which one worked?

**Comment by AlexLandherr** [comment]
> Raspberry Pi Zero 2 W should support 64-pit OSs too, but if you have a 32-bit OS you will probably need one of these builds:
> 
> - [step_linux_0.21.0_armv7.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv7.tar.gz)
> 
> - [step_linux_0.21.0_armv6.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv6.tar.gz)
> 
> - [step_linux_0.21.0_armv5.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv5.tar.gz)
> 
> 
> 
> Can you let us know which one worked?

I'll try them today.

**Comment by AlexLandherr** [comment]
> Raspberry Pi Zero 2 W should support 64-pit OSs too, but if you have a 32-bit OS you will probably need one of these builds:
> 
> - [step_linux_0.21.0_armv7.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv7.tar.gz)
> 
> - [step_linux_0.21.0_armv6.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv6.tar.gz)
> 
> - [step_linux_0.21.0_armv5.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv5.tar.gz)
> 
> 
> 
> Can you let us know which one worked?

I got these two working:
- [step_linux_0.21.0_armv7.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv7.tar.gz)
- [step_linux_0.21.0_armv5.tar.gz](https://github.com/smallstep/cli/releases/download/v0.21.0/step_linux_0.21.0_armv5.tar.gz)

As for v6 I didn't need to try it. My OS was Raspberry Pi OS Lite 32-bit.

**Comment by maraino** [comment]
I guess all three should work, use armv7 as it will use more advanced futures of your processor. Or to be sure you can also run `cat /proc/cpuinfo`

**Comment by AlexLandherr** [comment]
> I guess all three should work, use armv7 as it will use more advanced futures of your processor. Or to be sure you can also run `cat /proc/cpuinfo`

I am presently using armv7. Thanks for the help!
