### ISSUE TITLE
Support root/intermediate key URNs to be passed as parameters when using --kms=azurekms

### ISSUE THREAD

**Issue by rjfmachado** [smallstep/cli#721]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

step ca init can be automated for standalone CA's backed by Azure Key vault for the exception of these URN inputs.

## Why is this needed?

I'm working on a sample for Azure users https://github.com/rjfmachado/step-ca-azure, this is the missing step to get the CA deployed with minimal configuration.

**Comment by maraino** [comment]
Hi @rjfmachado, what exactly do you want? using already created keys in Azure Key Vault? Or defining the key URIs so it doesn't prompt. 

You can already do the first by combining `step` manually compiled from `master` with [`step-kms-plugin`](https://github.com/smallstep/step-kms-plugin), using `step certificate create` with the right combination of flags:
* `--kms "azurekms:" --key "azurekms:vault=my-vault;name=root-key"` to sign the root. 
* `--kms "azurekms:" --ca root_ca.crt --ca-key "azurekms:vault=my-vault;name=root-key" --key "azurekms:vault=my-vault;name=intermediate-key"` to sign the intermediate . 

The README.md in `step-kms-plugin` shows how to create a full PKI using a PKCS#11 module, to use azurekms (Azure Key Vault) should be similar but using `azurekms:`-like URIs. Then you just need to replace the configuration in the ca.json.

If it's the second thing, yes, we should definitively add flags for it.

**Comment by rjfmachado** [comment]
Thank you for the details, my primary goal for now is indeed the 2nd, as that would allow the sample deployment linked above to work end to end. Goal there is to solve for a simple use case with Azure and demo usage of managed identity and later on MySQL and maybe scale sets for HA.
But I'm definitely interested in the 1st approach once the compilation step is no longer needed, I'm assuming once you're out of beta?

I do have some learnings around the usage of Azure Managed Identities that I think could go into your documentation, should I open a separate issue for that?

**Comment by maraino** [comment]
> I do have some learnings around the usage of Azure Managed Identities that I think could go into your documentation, should I open a separate issue for that?

We have a repo for that, https://github.com/smallstep/docs
