### ISSUE TITLE
step should skip some checks when manipulating the ca.json

### ISSUE THREAD

**Issue by maraino** [smallstep/cli#722]
### Description

When `step` manipulates the ca.json to add a new provisioner, for example, while running
```console
step ca provisioner add registration \
  --type x5c --x5c-root x5c/intermediate_crt.pem  \
  --create --ca-config $PWD/ca-staging/config/ca.json
```

The cli will try to validate the full ca.json, including unrelated things like the SSH templates. This might cause errors when `step` uses a different context than the one we want to manipulate. 

See https://github.com/smallstep/certificates/discussions/963#discussioncomment-2997365 for more information.

**Comment by maraino** [comment]
If we skip the validation of the Config, this will work.

```diff
diff --git a/command/ca/provisioner/provisioner.go b/command/ca/provisioner/provisioner.go
index b910fd7..dd9333e 100644
--- a/command/ca/provisioner/provisioner.go
+++ b/command/ca/provisioner/provisioner.go
@@ -122,6 +122,7 @@ func newCRUDClient(cliCtx *cli.Context, cfgFile string) (crudClient, error) {
                        return cautils.NewAdminClient(cliCtx)
                }
                ui.Println()
+               cfg.SkipValidation = true
                return newCaConfigClient(context.Background(), cfg, cfgFile)
        default:
                return nil, errs.FileError(err, cfgFile)
```

@dopey, do you think this will cause any harm?

**Comment by maraino** [comment]
At the same time if we disable the validation enabling vaultcas is not required (#724)

**Comment by hslatman** [comment]
I assume `cfg.SkipValidation` would skip validation entirely? If validation of the command input is performed before changing the contents of `ca.json` and the internal representation, then it could work, but I think it would still make sense to validate the entire configuration every time it's changed, because settings may be related to each other.

**Comment by dopey** [comment]
@maraino where is the validation actually run? Like, where will that attribute be consumed?

We're already skipping initialization. I don't see any harm in skipping validation, since we're validating the provisioners using the provisioner collection API. I just don't see where it's applied.

**Comment by maraino** [comment]
@dopey authority's `func New(cfg *config.Config, opts ...Option) (*Authority, error)`, called in `newCaConfigClien` validates the config, see [this](https://github.com/smallstep/certificates/blob/ffe7c00a1040722c7606bced81a5a4ecc8bd8fe5/authority/authority.go#L102-L106):
```go
func New(cfg *config.Config, opts ...Option) (*Authority, error) {
	err := cfg.Validate()
	if err != nil {
		return nil, err
	}
```

`cfg.Validate()` will return nil if SkipValidation is set to true.

**Comment by dopey** [comment]
@maraino any reason not to use an options func like `WithSkipValidate()` like is already done for `WithSkipInit()`?

**Comment by maraino** [comment]
> @maraino any reason not to use an options func like WithSkipValidate() like is already done for WithSkipInit()?

To do that, we will need to change how the `New` method works. The options passed to the method act on top of the authority, not on the configuration.
