### ISSUE TITLE
[Bug]: Vaultcas: Can't add ACME provisioner using "step ca provisioner add acme --type ACME"

### ISSUE THREAD

**Issue by itmwiw** [smallstep/cli#723]
### Steps to Reproduce

Configure step-ca in Vault ra mode: https://smallstep.com/docs/step-ca/registration-authority-ra-mode#hashicorp-vault-ra-mode. Once everything is working fine and you are able to issue a certificate using the JWK provisioner, try adding an ACME provisioner.

### Your Environment

* OS - Linux
* `step-ca` Version - 0.20.0

### Expected Behavior

provisioner added succesfully 

### Actual Behavior

got an error message: "error loading authority: unsupported cas type vaultcas"

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment]
The problem is that vaultcas is not enabled, and this is required because of how the ca.json is loaded into memory. I'm about to commit a patch to enable it.
