### ISSUE TITLE
Allow x5c commands to acquire keys/certificates from platform keystores (CAPI/Keychain/etc)

### ISSUE THREAD

**Issue by unreality** [smallstep/cli#767]
## X5C Provisioner Improvements

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Windows and MacOS have secure key and certificate storage (TPM and Secure Enclave respectively). Linux can also access the platform TPM if available. It would be useful to allow the x5c provisioner process to sign its token using one of the keys in the platform store instead of only on disk.

On Windows 10, the Crypto API (aka CAPI) and Next-Gen Crypto API (nCrypt) could be used which would allow users to sign the request with smart cards/yubikeys as well. CAPI can be called from golang reasonably easily with `syscall`, but I am unsure of how to call the required Secure Enclave methods on MacOS

## Why is this needed?

This would take advantage of the platform specific secure key storage to avoid having to load and store keys on disk.

**Comment by maraino** [comment]
To support this, we will need to create a KMS or a subset of this for TPM (@hslatman) and Secure Enclave (@maraino) in `go.step.sm/crypto`. Then use `step-kms-plugin` in more places of `step`.

Right now it is possible to create tokens using `step-kms-plugin` with yubikeys, pkcs#11, cloud kms, ... but it's not straightforward. 

We could simplify the flags, but with existing KMSs something like this should be supported:

```shell
step ca certificate \
  --kms 'yubikey:?pin-value=123456' \
  --x5c-cert 'yubikey:slot-id=82' \
  --x5c-key 'yubikey:slot-id=82' \
  --provisioner X5C \
  localhost localhost.crt localhost.key
```

**Comment by unreality** [comment]
@maraino would you accept a pull that added a new kms of 'capi' that used the windows CAPI/nCrypt to find certs/keys and raise notimplemented errors on other platforms?

**Comment by hslatman** [comment]
Adding a `capi` KMS sounds reasonable to me. If you're going to use `syscall`, it can probably live in `step-kms-plugin`. I feel it's somewhat of a bigger lift, so it probably needs @maraino's approval too and maybe some internal discussion. 

I'm working on some TPM things. The library supports Windows too. That means we'll have multiple "interfaces" to the same underlying cryptographic hardware, I guess? I don't think that's a big problem, though.

**Comment by unreality** [comment]
The advantage of using syscall and CAPI would be that it allows end-users to do actions. As far as i'm aware, interacting with the TPM requires administrator privileges?

**Comment by maraino** [comment]
> @maraino would you accept a pull that added a new kms of 'capi' that used the windows CAPI/nCrypt to find certs/keys and raise not implemented errors on other platforms?

As @hslatman mentioned, the initial PR should be a KMS in `go.step.sm/crypto` implementing as much as possible of the `KeyManager` and `CertificateManager` interface, see [here](https://github.com/smallstep/crypto/blob/0a1ad491de6168fbf6911588678428af799c5854/kms/apiv1/options.go#L13-L31)

This KMS will probably be directly available with a new release in `step-kms-plugin`, so you would be able to load certificates, create keys, sign, ... basically do all the operations implemented.

The second phase will be integrating that plugin in the `step ca` commands, right now, the plugin is just integrated into `step certificate create` and `step certificate sign`. I can help with that.
