### ISSUE TITLE
[Bug]: Invoking "step certificate create" fails with "Too many positional arguments" when using "--set" or "--set-file" options

### ISSUE THREAD

**Issue by danmenes** [smallstep/cli#782]
### Steps to Reproduce

I am attempting to pass command line parameters to set values for custom extensions on a certificate. The following command successfully creates a certificate, but there are no values for the custom parameters.

step certificate create "redatced" "redacted.cert" "redacted.key" --template=vehicle.template --password-file="redacted.keypass" --ca="redacted-ca.crt" --ca-key="redacted-ca.key" --ca-password-file="redacted-ca.keypass" --not-before="-1h" --not-after="2032-10-21T00:00:00Z"

I then attempt to add the missing parameters:

step certificate create "redatced" "redacted.cert" "redacted.key" --template=vehicle.template --password-file="redacted.keypass" --ca="redacted-ca.crt" --ca-key="redacted-ca.key" --ca-password-file="redacted-ca.keypass" --not-before="-1h" --not-after="2032-10-21T00:00:00Z"
--set="hashedVin=${HASHED_VIN}"

or

step certificate create "redatced" "redacted.cert" "redacted.key" --template=vehicle.template --password-file="redacted.keypass" --ca="redacted-ca.crt" --ca-key="redacted-ca.key" --ca-password-file="redacted-ca.keypass" --not-before="-1h" --not-after="2032-10-21T00:00:00Z" --set-file=parameters.txt

In both cases, the command fails with the response "too many positional arguments were provided in 'step certificate create <subject> <crt-file> <key-file>'"

### Your Environment

* OS - Ubuntu 22.04 
* `step` CLI Version - 0.21.0

### Expected Behavior

Certificates are created with data included in custom extensions

### Actual Behavior

Certificate is not created. Error is reported as "too many positional arguments were provided in 'step certificate create <subject> <crt-file> <key-file>'"

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment]
I'm not able to reproduce your problem with 0.22.0:

```console
$ step version
Smallstep CLI/0.22.0 (darwin/amd64)
Release Date: 2022-08-26 06:50 UTC
$ echo foo > password.txt
$ step certificate create --profile root-ca --password-file password.txt "Test Root" root.crt root.key
Your certificate has been saved in root.crt.
Your private key has been saved in root.key.
$ cat vehicle.tpl
{
	"subject": {
		"commonName": {{ toJson .Insecure.User.hashedVin }}
	},
	"sans": {{ toJson .SANs }},
{{- if typeIs "*rsa.PublicKey" .Insecure.CR.PublicKey }}
	"keyUsage": ["keyEncipherment", "digitalSignature"],
{{- else }}
	"keyUsage": ["digitalSignature"],
{{- end }}
	"extKeyUsage": ["serverAuth", "clientAuth"]
}
$ export HASHED_VIN=$(uuidgen)
$ step certificate create "test.example.org"  "test.cert"  "test.key" --template=vehicle.tpl --password-file="password.txt" --ca="root.crt" --ca-key="root.key" --ca-password-file="password.txt" --not-before="-1h" --not-after="2032-10-21T00:00:00Z" --set="hashedVin=${HASHED_VIN}"
Your certificate has been saved in test.cert.
Your private key has been saved in test.key.
$ step certificate inspect test.cert --format json | jq .subject
{
  "common_name": [
    "CCA72287-0254-4E53-BC46-2DE333AA6D6F"
  ]
}
```

**Comment by danmenes** [comment]
That is fascinating.

ubuntu@primary:~$ step version
Smallstep CLI/0.21.0 (linux/amd64)
Release Date: 2022-07-06T22:23:54Z
ubuntu@primary:~$ echo foo > password.txt
ubuntu@primary:~$ step certificate create --profile root-ca --password-file password.txt "Test Root" root.crt root.key
✔ Would you like to overwrite root.key [y/n]: y
✔ Would you like to overwrite root.crt [y/n]: y
Your certificate has been saved in root.crt.
Your private key has been saved in root.key.
ubuntu@primary:~$ cat vehicle.tpl
{ "subject": { "commonName": {{ toJson .Insecure.User.hashedVin }} }, "sans": {{ toJson .SANs }},{{- if typeIs "*rsa.PublicKey" .Insecure.CR.PublicKey }} "keyUsage": ["keyEncipherment", "digitalSignature"],{{- else }} "keyUsage": ["digitalSignature"],{{- end }} "extKeyUsage": ["serverAuth", "clientAuth"]}
ubuntu@primary:~$ echo ${HASHED_VIN}
0123456789abcdef
ubuntu@primary:~$ step certificate create "test.example.org"  "test.cert"  "test.key" --template=vehicle.tpl --password-file="password.txt" --ca="root.crt" --ca-key="root.key" --ca-password-file="password.txt" --not-before="-1h" --not-after="2032-10-21T00:00:00Z" --set="hashedVin=${HASHED_VIN}"
too many positional arguments were provided in 'step certificate create <subject> <crt-file> <key-file>'

What am I doing different?

**Comment by danmenes** [comment]
Updating to 0.22.0 fixes the issue. Thank you.

**Comment by maraino** [comment]
I've downgraded to v0.21.0, and I'm able to reproduce it. And after looking at it, the problem is that `--set` is not a valid flag on v0.21.0, and for some reason, it is the 4th argument, the extra one. 

It used to complain about invalid flags, and I don't know what changed, it doesn't do that now.
