### ISSUE TITLE
Offline mode for step ca certificate

### ISSUE THREAD

**Issue by maraino** [smallstep/cli#84]
Create an offline mode for `step ca certificate` that uses the configuration file created with `step ca init`

**Comment by dopey** [comment]
This feature adds support for an offline mode to `step ca certificate`. Offline mode is useful for generating certificates without running an online Step CA while continuing to use the secure Step provisioner flow for authentication. 

```
$ step ca init
^^^ creates ca.json
...
$ step ca certificate --offline foo
^^^ implicitly uses configuration from ca.json
```
