### ISSUE TITLE
[Bug]: differences between step certificate inspect and step certificate fingerprint

### ISSUE THREAD

**Issue by glance-** [smallstep/cli#893]
### Steps to Reproduce

Given a certificate, say /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt , from now on called $CERT

step certificate inspect $CERT works just fine, also step certificate fingerprint $CERT

It's quite common that there will be other things in a certificate file, like the output from step certificate inspect / openssl x509 -tex well as the pem data.

openssl x509 -in $CERT -text > /tmp/cert.pem
step certificate inspect /tmp/cert.pem works just fine, but

step certificate fingerprint /tmp/cert.pem
error parsing /tmp/cert.pem: x509: malformed certificate

Also, step certificate inspect gladly consumes stdin but step certificate fingerprint doesn't.

### Your Environment

Smallstep CLI/0.23.5-rc.3-23-g848ae613 (linux/amd64)
Release Date: 2023-03-29 08:22 UTC

### Expected Behavior

I'd expect related commands like step certificate inspect and step certificate fingerprint to have a similar interaction.

### Actual Behavior

step certificate inspect is way nicer to interact with, and gladly finds the actual data in a pem-file but step certificate fingerprint is way more picky.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dopey** [comment]
Fixed with #1007

**Comment by dopey** [comment]
Will go out in the next release (which should be soon - matter of weeks).
