### ISSUE TITLE
Allow setting the mode for certificate and key files.

### ISSUE THREAD

**Issue by the-maldridge** [smallstep/cli#924]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

By default certificates/keys written by the `step` commands are only readable by the user that ran the command.  Under normal circumstances I would agree that this is a fine security precaution, but when running `step` as a daemon and consuming the certificates with other daemons it results in kludges to make the certificates readable to consumers.  In these cases I would like to change the permissions to `0640`.  Since I can do this with the `--exec` hook, there technically exists a workaround, but its not particularly elegant. 

## Why is this needed?

It would make it easier to consume certificates that are managed by automation, generally boosting the ease of deploying TLS.

**Comment by maraino** [comment]
Hi @the-maldridge, when you run `step ca renew --daemon`, the certificate will keep the previous permissions. The same will happen with `step ca rekey --daemon`.

So as long you change the permissions once, the first time you create the files, it will always keep the same permissions.

I'm going to close this issue. Feel free to reopen it if this doesn't respond to your issue.

**Comment by the-maldridge** [comment]
Sorry a crucial bit of information I had left out that changes this slightly:

To ensure the certificates can't be compromised by the physical theft of a machine, I have step putting them in `/run/step` which is on a ramdisk.  This means that every time it starts up I'd need to change the permissions of the certificate.  This also applies to anyone using systemd with RuntimeDirectory since that will get GC'd on shutdown.

**Comment by maraino** [comment]
I suppose you have a systemd service/job or an `ExecStartPre` that creates the initial certificate. Can you change the permissions there?

**Comment by the-maldridge** [comment]
Hmm, I suppose I could.  My systemd job has an ExecStartPre that does the initial acquisition of the certificate before handing off to the daemon to renew it.  Does the certificate need to have valid content when the initial pull happens, or is it sufficient for it to just be a zero byte file with the right permissions?

**Comment by maraino** [comment]
A zero-byte file should be enough.
