### ISSUE TITLE
[Bug]: download links are beoken ( dl.step.sm unavailable)

### ISSUE THREAD

**Issue by atimgraves** [smallstep/cli#938]
### Steps to Reproduce

go to https://github.com/smallstep/cli/releases/latest
click on a download ( [step_linux_0.24.4_amd64.tar.gz](https://dl.step.sm/gh-release/cli/gh-release-header/v0.24.4/step_linux_0.24.4_amd64.tar.gz) in my case, points to https://dl.step.sm/gh-release/cli/gh-release-header/v0.24.4/step_linux_0.24.4_amd64.tar.gz )
can't access site "Hmm. We’re having trouble finding that site.

We can’t connect to the server at dl.step.sm."

### Your Environment

* OS - Macos & Linux
Failes using web browser, wget and curl from multiple locations
* n/a

### Expected Behavior

download of the selected version

### Actual Behavior

dl.step.sm is unavailable error message

### Additional Context

have tries this using multiple tools, web browsers and from several regions, the same issue everywhere
Been happenign since at least 18:00 UK 15th may and still happening as of time of bug filing

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
Hi @atimgraves, thank you for creating this issue. We're aware of the issue with the domain and are working on it to fix it.
In the meantime, releases for both our CA and the CLI can be downloaded from GitHub: https://github.com/smallstep/certificates/releases and https://github.com/smallstep/cli/releases, respectively.

I'll leave this open for others to see 🙂

**Comment by hslatman** [comment]
The domain is being resolved correctly again. Things should be looking better now. 

Will leave this open for a bit for others to see.

**Comment by 3rd-st-ninja** [comment]
This is happening again

**Comment by hslatman** [comment]
@3rd-st-ninja I don't see this happening, at least not for one of the above links.

Is it possible this was a temporary or local issue?

We currently also have `dl.smallstep.com` as domain for downloads available, so you can try that as an alternative.

**Comment by dopey** [comment]
In fact, all documentation links on the website should be using `dl.smallstep.com` at this point. @3rd-st-ninja did you find a link that still points to `dl.step.sm`?

**Comment by 3rd-st-ninja** [comment]
Apologies for the late reply.  Turns out, my firewall is blocking dl.smallstep.com (but no other page on smallstep.com domain).  Sorry for the fire drill.
